"""Tied-recurrence submission (generated by lab/make_tied.py).

config: {"act": "gelu", "batch_size": 128, "beta": 0.0, "d_model": 128, "ent_pen": 0.0, "eval_batch_size": null, "eval_loops": 4, "ff_mult": 4, "gate_init": 2.0, "inject": true, "iter_mode": "fixed", "loops": 4, "lr": 0.001, "max_steps": 4000, "n_dec": 0, "n_enc": 1, "num_heads": 4, "prior_lambda": 0.3, "ramp": 1, "sched": "none", "state_mode": "res", "tau": 1.0, "warmup": 0, "wd": 0.1}
"""

from __future__ import annotations

import math

import torch
import torch.nn.functional as F
from torch import Tensor, nn

from benchmark import (
    ModelSpec,
    OptimizerBundle,
    OptimizerSpec,
    Submission,
    assert_model_state,
)

D_MODEL = 128
NUM_HEADS = 4
FF_MULT = 4
ACT = "gelu"
N_ENC = 1
N_DEC = 0
LOOPS = 4
EVAL_LOOPS = 4
INJECT = True
STATE_MODE = "res"
GATE_INIT = 2.0
TAU = 1.0
ITER_MODE = "fixed"
BETA = 0.0
WARMUP = 0
RAMP = 1
PRIOR_LAMBDA = 0.3
ENT_PEN = 0.0
LR = 0.001
WD = 0.1
SCHED = "none"
_MAX_STEPS = 4000
_BATCH_SIZE = 128
_EVAL_BATCH_SIZE = None


_PER_STEP_LOGITS = ITER_MODE in ("ponder", "tgather")
_REEMBED = STATE_MODE in ("reembed", "reembed_st")


class Config:
    def __init__(self, vocab_size: int, max_seq_len: int) -> None:
        self.vocab_size = vocab_size
        self.max_seq_len = max_seq_len


class RMSNorm(nn.Module):
    def __init__(self, width: int) -> None:
        super().__init__()
        self.weight = nn.Parameter(torch.ones(width))

    def forward(self, x: Tensor) -> Tensor:
        return F.rms_norm(x, (x.shape[-1],), self.weight)


class Block(nn.Module):
    """Pre-norm transformer block.  One instance of this is the tied step."""

    def __init__(self) -> None:
        super().__init__()
        hidden = FF_MULT * D_MODEL
        self.attention_norm = RMSNorm(D_MODEL)
        self.qkv = nn.Linear(D_MODEL, 3 * D_MODEL)
        self.out = nn.Linear(D_MODEL, D_MODEL)
        self.mixer_norm = RMSNorm(D_MODEL)
        self.up = nn.Linear(D_MODEL, 2 * hidden if ACT == "swiglu" else hidden)
        self.down = nn.Linear(hidden, D_MODEL)

    def forward(self, x: Tensor, mask4: Tensor | None) -> Tensor:
        batch, length, _ = x.shape
        h = self.attention_norm(x)
        q, k, v = self.qkv(h).chunk(3, dim=-1)
        q = q.view(batch, length, NUM_HEADS, -1).transpose(1, 2)
        k = k.view(batch, length, NUM_HEADS, -1).transpose(1, 2)
        v = v.view(batch, length, NUM_HEADS, -1).transpose(1, 2)
        a = F.scaled_dot_product_attention(q, k, v, attn_mask=mask4)
        a = a.transpose(1, 2).contiguous().view(batch, length, D_MODEL)
        x = x + self.out(a)
        m = self.mixer_norm(x)
        if ACT == "swiglu":
            u, g = self.up(m).chunk(2, dim=-1)
            m = self.down(F.silu(g) * u)
        else:
            m = self.down(F.gelu(self.up(m)))
        return x + m


class Model(nn.Module):
    def __init__(self, spec: ModelSpec) -> None:
        super().__init__()
        self.config = Config(spec.vocab_size, spec.max_seq_len)
        self.token_embedding = nn.Embedding(spec.vocab_size, D_MODEL)
        self.position_embedding = nn.Embedding(spec.max_seq_len, D_MODEL)
        self.enc = nn.ModuleList([Block() for _ in range(N_ENC)])
        self.core = Block()  # ONE shared block -- the tied step
        self.dec = nn.ModuleList([Block() for _ in range(N_DEC)])
        self.final_norm = RMSNorm(D_MODEL)
        self.head = nn.Linear(D_MODEL, spec.vocab_size, bias=False)
        self.head.weight = self.token_embedding.weight
        self.loop_norm = RMSNorm(D_MODEL)
        if STATE_MODE == "gate":
            self.gate = nn.Parameter(torch.full((D_MODEL,), float(GATE_INIT)))
        if ITER_MODE == "ponder":
            self.halt = nn.Linear(D_MODEL, 1)
            with torch.no_grad():
                self.halt.bias.fill_(0.0)
        # non-persistent -> excluded from the model-state ceiling and from the
        # evaluator's "state unchanged during eval" check.
        self.register_buffer(
            "_step", torch.zeros((), dtype=torch.float32), persistent=False
        )

    # -- helpers -------------------------------------------------------------
    def _decode(self, h: Tensor, mask4: Tensor | None) -> Tensor:
        g = h
        for blk in self.dec:
            g = blk(g, mask4)
        return self.head(self.final_norm(g))

    def _reembed(self, z: Tensor, pemb: Tensor) -> tuple[Tensor, Tensor]:
        """Project the state back onto the token-embedding manifold."""
        p = F.softmax(z.float() / TAU, dim=-1)
        ent = -(p * torch.log(p.clamp_min(1e-9))).sum(-1).mean()
        if STATE_MODE == "reembed_st":
            idx = p.argmax(dim=-1)
            hard = F.one_hot(idx, p.shape[-1]).to(p.dtype)
            p = hard + p - p.detach()  # straight-through: exact forward, live grad
        emb = self.token_embedding.weight
        return (p.to(emb.dtype) @ emb) + pemb, ent

    # -- forward -------------------------------------------------------------
    def forward(
        self,
        input_ids: Tensor,
        attention_mask: Tensor | None = None,
    ) -> tuple[Tensor, object]:
        _, length = input_ids.shape
        device = input_ids.device
        if self.training:
            self._step += 1.0
        positions = torch.arange(length, device=device)
        pemb = self.position_embedding(positions)
        h0 = self.token_embedding(input_ids) + pemb
        mask = attention_mask if attention_mask is not None else (input_ids != 0)
        if mask.dim() == 2:
            valid = mask.to(device=device, dtype=torch.bool)
            mask4 = valid[:, None, None, :]
        else:
            mask4 = mask.to(device=device, dtype=torch.bool)[:, None, :, :]
            valid = mask4[:, 0, 0, :]
        maskf = valid.to(h0.dtype)
        denom = maskf.sum(dim=1, keepdim=True).clamp_min(1.0)

        h = h0
        for blk in self.enc:
            h = blk(h, mask4)
        base = h

        loops = LOOPS if self.training else EVAL_LOOPS
        per_step: list[Tensor] = []
        lams: list[Tensor] = []
        ent_sum = h0.new_zeros(())
        last_z: Tensor | None = None
        for _ in range(loops):
            inp = h + base if INJECT else h
            y = self.core(inp, mask4)
            h = h + torch.sigmoid(self.gate) * (y - h) if STATE_MODE == "gate" else y
            if STATE_MODE == "renorm":
                h = self.loop_norm(h)
            z = None
            if _REEMBED:
                z = self.head(self.loop_norm(h))
                last_z = z
                h, ent = self._reembed(z, pemb)
                ent_sum = ent_sum + ent
            if _PER_STEP_LOGITS:
                per_step.append(z if z is not None else self._decode(h, mask4))
            if ITER_MODE == "ponder":
                pooled = (self.loop_norm(h) * maskf[..., None]).sum(1) / denom
                lams.append(torch.sigmoid(self.halt(pooled).float()).squeeze(-1))
        if _REEMBED and loops > 0:
            ent_sum = ent_sum / float(loops)

        ent_reg = ENT_PEN * ent_sum if (_REEMBED and ENT_PEN != 0.0) else None

        if ITER_MODE == "fixed":
            logits = last_z if last_z is not None else self._decode(h, mask4)
            return logits, ent_reg

        stack = torch.stack(per_step, dim=0).float()  # [K,B,L,V]
        logp = F.log_softmax(stack, dim=-1)

        if ITER_MODE == "tgather":
            # DIAGNOSTIC ONLY / COMPLIANCE-UNCERTAIN: reads T from the prompt.
            tval = _decode_time_steps(input_ids, valid)
            idx = tval.clamp(1, loops).long() - 1  # [B]
            sel = F.one_hot(idx, loops).to(logp.dtype).permute(1, 0)  # [K,B]
            return (logp * sel[:, :, None, None]).sum(0), ent_reg

        # -- ponder: PonderNet marginal likelihood over the halting step -----
        lam = torch.stack(lams, dim=0)  # [K,B]
        remain = torch.cumprod(
            torch.cat([torch.ones_like(lam[:1]), 1.0 - lam[:-1]], dim=0), dim=0
        )
        p = remain * lam
        p = torch.cat([p[:-1], remain[-1:]], dim=0)  # last step absorbs the rest
        p = p / p.sum(0, keepdim=True).clamp_min(1e-9)
        logpk = torch.log(p.clamp_min(1e-9))  # [K,B]
        logits = torch.logsumexp(logpk[:, :, None, None] + logp, dim=0)

        prior = PRIOR_LAMBDA * (1.0 - PRIOR_LAMBDA) ** torch.arange(
            loops, device=device, dtype=p.dtype
        )
        prior = (prior / prior.sum()).clamp_min(1e-9)[:, None]
        kl = (p * (logpk - torch.log(prior))).sum(0).mean()
        ramp = max(float(RAMP), 1.0)
        sched = ((self._step - float(WARMUP)) / ramp).clamp(0.0, 1.0)
        reg = BETA * sched.detach() * kl
        if ent_reg is not None:
            reg = reg + ent_reg
        return logits, reg


def _decode_time_steps(input_ids: Tensor, valid: Tensor) -> Tensor:
    """DIAGNOSTIC ONLY. Parse the integer T out of the prompt tokens."""
    t_marker = 4
    digit_offset = 7
    after = (input_ids == t_marker).cumsum(dim=1) > 0
    sel = (after & (input_ids >= digit_offset) & valid).long()
    digits = (input_ids - digit_offset).clamp(0, 9)
    value = torch.zeros(input_ids.shape[0], device=input_ids.device, dtype=torch.long)
    for j in range(input_ids.shape[1]):
        s = sel[:, j]
        value = value * (9 * s + 1) + digits[:, j] * s
    return value


def training_loss(logits: Tensor, labels: Tensor, aux: object) -> Tensor:
    loss = F.cross_entropy(logits.float(), labels)
    if torch.is_tensor(aux):
        loss = loss + aux.to(loss.dtype)
    return loss


def build_model(spec: ModelSpec) -> Model:
    model = Model(spec)
    assert_model_state(model, spec)
    return model


def build_optimizer(model: nn.Module, spec: OptimizerSpec) -> OptimizerBundle:
    opt = torch.optim.AdamW(
        model.parameters(),
        lr=LR,
        betas=(0.9, 0.95),
        weight_decay=WD,
        capturable=spec.device_type == "cuda",
    )
    sched = None
    if SCHED == "cosine":
        horizon = float(_MAX_STEPS or 1000)
        sched = torch.optim.lr_scheduler.LambdaLR(
            opt,
            lambda s: 0.5 * (1.0 + math.cos(math.pi * min(float(s), horizon) / horizon)),
        )
    return OptimizerBundle(opt, sched)


SUBMISSION = Submission(
    build_model=build_model,
    build_optimizer=build_optimizer,
    training_loss=training_loss,
    batch_size=_BATCH_SIZE,
    max_steps=_MAX_STEPS,
    eval_batch_size=_EVAL_BATCH_SIZE,
)
