"""hard-add-only: an ADDITION-ONLY modular squaring transducer.

WHY THIS SHAPE
--------------
`explore/alu-relational` established that `DigitALU`'s `Tmul` -- the 10x10
single-digit product table -- is *unidentifiable*: not from the end-of-chain
label, not from any generic algebraic law.  So this model does not contain one.
`x^2 mod N` is accumulated over the digits of `x`,

    x^2 = sum_i  (d_i * x) * 10^i          place value, fixed structure
    d_i * x     = one element of the chain  x, x+x, (x+x)+x, ...
                  generated by the LEARNED adder, selected by a LEARNED table

so every learned arithmetic tensor in the model is an adder cell, a subtractor
cell, or one of ~17 selector/constant cells.  The place-value shifts, the tree
summation and the conditional-subtract reduction are `explore/alu-depth`'s
`tree:quotient` schedule, unchanged; the only difference from `DigitALU` is that
the S^2 `Tmul` digit products are replaced by S full-width multiples of `x`
drawn from the adder chain.

COMPLIANCE (rule 2: choose structure, learn the function)
--------------------------------------------------------
Every tensor here is initialised at random and trained in this run.  Nothing is
constructed, frozen, or read from disk; there is no lookup indexed by a residue,
no modular-exponentiation routine, and no Python control flow that decodes the
prompt.  What the *architecture* supplies is a schedule: base-10 place value,
"the leaf at place i is some element of the chain generated by repeatedly
applying the learned binary operation to x", and "reduce by subtracting some
multiple of N".  The middle clause is the one this branch had to rule on; the
ruling, with the argument on both sides, is in lab/reports/hard-add-only.md
section 2.  The narrower reading is implemented here: `Tpick` (digit -> chain
element) is LEARNED, exactly as the quotient selector is, so the architecture
never asserts `d*x = x added d times`.

Front end: `explore/digit-carry`'s marker-relative pointer (bottleneck 3,
solved).  Depth: one weight-tied block applied LOOPS times with an ordered
learned selector (`explore/depth-controller`).  Both are solved components
reused so that the arithmetic is the only thing under test; LOOPS=4 caps this
submission's reachable Max T at 4 by design.
"""

from __future__ import annotations

import torch
import torch.nn.functional as F
from torch import Tensor, nn

from benchmark import (
    ModelSpec,
    OptimizerBundle,
    OptimizerSpec,
    Submission,
    assert_model_state,
)

D_MODEL = 64
LOOPS = 4
ANNEAL_STEPS = 2000
RAND_LOOPS = 1
LR = 0.0
WD = 0.0
DIGIT_TAU = 0.2
EMB_INIT = 0.02
VINIT_SCALE = 8.0
MAX_QUOT = 10
N_CARRY = 2
N_BORROW = 2
TAB_INIT = 0.5
PICK = "learned"          # "learned" (shipped) | "fixed" (borderline variant)
_MAX_STEPS = None
_BATCH_SIZE = 128
O_LO, O_HI = -2, 9
NEG = -1e4


class Config:
    def __init__(self, vocab_size: int, max_seq_len: int) -> None:
        self.vocab_size = vocab_size
        self.max_seq_len = max_seq_len


class MarkerPointer(nn.Module):
    """Anchor each digit on the marker that terminates its own field."""

    def __init__(self, d_model: int, n_slot: int) -> None:
        super().__init__()
        self.n_off = O_HI - O_LO + 1
        self.probe = nn.Linear(d_model, 3, bias=False)
        self.R = nn.Parameter(torch.randn(n_slot, 4, self.n_off) * 0.5)
        self.G = nn.Parameter(torch.randn(n_slot, 4) * 0.5)

    def forward(self, emb: Tensor, mask: Tensor) -> Tensor:
        b, L, _ = emb.shape
        sc = self.probe(emb).transpose(1, 2)
        sc = sc.masked_fill(~mask[:, None, :], NEG)
        a = F.softmax(sc, dim=-1)
        idx = mask.long().sum(-1) - 1
        a = torch.cat([a, F.one_hot(idx, L).to(a.dtype)[:, None]], dim=1)
        rels = []
        for o in range(O_LO, O_HI + 1):
            if o >= 0:
                rels.append(F.pad(a[:, :, o:], (0, o)))
            else:
                rels.append(F.pad(a[:, :, : L + o], (-o, 0)))
        rel = torch.stack(rels, dim=-1)
        logit = (torch.einsum("balo,sao->bsl", rel, self.R)
                 + torch.einsum("bal,sa->bsl", a.cumsum(-1), self.G))
        logit = logit.masked_fill(~mask[:, None, :], NEG)
        return torch.einsum("bsl,bld->bsd", F.softmax(logit, dim=-1), emb)


class AddStep(nn.Module):
    """One modular squaring, with an adder as the only arithmetic primitive.

    Learned tensors
      Tadd  (10,10,Ca) -> 10+Ca     digit add with carry
      Tsub  (10,10,Cb) -> 10+Cb     digit subtract with borrow
      Tpick (10,10)                 input digit -> chain element
      zero, carry0, borrow0, sel    constants and the quotient scorer
    There is no product table.
    """

    def __init__(self, slots: int, max_quot: int = MAX_QUOT) -> None:
        super().__init__()
        self.S = slots
        self.W = slots + 1
        self.Fw = 2 * slots
        self.Ca, self.Cb = N_CARRY, N_BORROW
        self.needed = list(range(max_quot + 2))
        self.xneeded = list(range(10))
        s = TAB_INIT
        self.Tadd = nn.Parameter(torch.randn(10, 10, self.Ca, 10 + self.Ca) * s)
        self.Tsub = nn.Parameter(torch.randn(10, 10, self.Cb, 10 + self.Cb) * s)
        self.Tpick = nn.Parameter(torch.randn(10, 10) * s)
        self.zero = nn.Parameter(torch.randn(10) * s)
        self.carry0 = nn.Parameter(torch.randn(self.Ca) * s)
        self.borrow0 = nn.Parameter(torch.randn(self.Cb) * s)
        self.sel = nn.Linear(2 * self.Cb, 1)

    # ---- machinery ----
    def add_scan(self, r: Tensor, a: Tensor) -> Tensor:
        """r, a: (n, W, 10) -> (n, W, 10)."""
        n = r.shape[0]
        c = F.softmax(self.carry0, -1)[None].expand(n, self.Ca)
        outs = []
        for m in range(r.shape[1]):
            o = torch.einsum("nu,nv,nc,uvco->no", r[:, m], a[:, m], c, self.Tadd)
            outs.append(F.softmax(o[..., :10], -1))
            c = F.softmax(o[..., 10:], -1)
        return torch.stack(outs, 1)

    def tree_sum(self, regs: list[Tensor]) -> Tensor:
        while len(regs) > 1:
            carry = [regs[-1]] if len(regs) % 2 else []
            pairs = [(regs[i], regs[i + 1]) for i in range(0, len(regs) - 1, 2)]
            n = regs[0].shape[0]
            out = self.add_scan(torch.cat([x for x, _ in pairs], 0),
                                torch.cat([y for _, y in pairs], 0))
            regs = [out[i * n:(i + 1) * n] for i in range(len(pairs))] + carry
        return regs[0]

    def chain(self, zero_reg: Tensor, one_reg: Tensor,
              needed: list[int]) -> dict[int, Tensor]:
        """{m * one_reg} by repeated application of the LEARNED adder."""
        have = {0: zero_reg, 1: one_reg}
        target = set(needed)
        while not target <= set(have):
            newly = []
            for t in sorted(target - set(have)):
                cand = [a for a in have if a <= t - a and (t - a) in have]
                if cand:
                    newly.append((t, max(cand), t - max(cand)))
            if not newly:
                mx = max(have)
                newly = [(2 * mx, mx, mx)]
            A = torch.cat([have[a] for _, a, _ in newly], 0)
            B = torch.cat([have[b] for _, _, b in newly], 0)
            out = self.add_scan(A, B)
            k = A.shape[0] // len(newly)
            for i, (t, _, _) in enumerate(newly):
                have[t] = out[i * k:(i + 1) * k]
        return have

    def quot_reduce(self, r: Tensor, mults: Tensor) -> Tensor:
        """r (b,W,10), mults (b,M,W,10) -> (b,W,10).  One learned quotient
        digit: subtract every candidate multiple, score the borrow-out pairs,
        take the learned convex combination."""
        b, W = r.shape[0], self.W
        M = mults.shape[1]
        rr = r[:, None].expand(b, M, W, 10).reshape(b * M, W, 10)
        ss = mults.reshape(b * M, W, 10)
        c = F.softmax(self.borrow0, -1)[None].expand(b * M, self.Cb)
        outs = []
        for m in range(W):
            o = torch.einsum("nu,nv,nc,uvco->no", rr[:, m], ss[:, m], c,
                             self.Tsub)
            outs.append(F.softmax(o[..., :10], -1))
            c = F.softmax(o[..., 10:], -1)
        t = torch.stack(outs, 1).view(b, M, W, 10)
        cb = c.view(b, M, self.Cb)
        pair = torch.cat([cb[:, :-1], cb[:, 1:]], dim=-1)
        w = F.softmax(self.sel(pair).squeeze(-1), -1)
        return torch.einsum("bm,bmwo->bwo", w, t[:, :-1])

    def forward(self, s: Tensor, nd: Tensor) -> Tensor:
        """s (b,S,10) digits of x LSB-first, nd (b,W,10) digits of N."""
        b, S, W, Fw = s.shape[0], self.S, self.W, self.Fw
        z = F.softmax(self.zero, -1)[None].expand(b, 10)
        zr = z[:, None].expand(b, W, 10)
        hn = self.chain(zr, nd, self.needed)
        mults = torch.stack([hn[m] for m in self.needed], 1)   # (b,M,W,10)
        xr = torch.cat([s, z[:, None].expand(b, W - S, 10)], 1)
        hx = self.chain(zr, xr, self.xneeded)
        Xm = torch.stack([hx[m] for m in self.xneeded], 1)     # (b,10,W,10)
        pk = F.softmax(self.Tpick, -1)
        leaves = []
        for i in range(S):
            w = s[:, i] if PICK == "fixed" else torch.einsum(
                "bu,um->bm", s[:, i], pk)
            v = torch.einsum("bm,bmwo->bwo", w, Xm)            # (b,W,10)
            cols = [z] * Fw
            for j in range(W):
                if i + j < Fw:
                    cols[i + j] = v[:, j]
            leaves.append(torch.stack(cols, 1))
        Pr = self.tree_sum(leaves)                             # (b,Fw,10)
        r = zr
        for t in range(Fw - 1, -1, -1):
            r = torch.cat([Pr[:, t:t + 1], r[:, :W - 1]], dim=1)
            if t <= S:
                r = self.quot_reduce(r, mults)
        return torch.log(r[:, :S] + 1e-9)


class Model(nn.Module):
    def __init__(self, spec: ModelSpec) -> None:
        super().__init__()
        self.config = Config(spec.vocab_size, spec.max_seq_len)
        self.vocab = spec.vocab_size
        self.S = max(3, (spec.max_seq_len - 5) // 2)
        self.emb = nn.Embedding(spec.vocab_size, D_MODEL)
        nn.init.normal_(self.emb.weight, std=EMB_INIT)
        n_slot = 3 * self.S
        self.ptr = MarkerPointer(D_MODEL, n_slot)
        with torch.no_grad():
            # structured but fully trainable init of the PARSER (digit-carry):
            # slot p of x reads 1+p before [T], of N reads 1+p before [X], of
            # T reads p before the end.  No arithmetic is supplied.
            self.ptr.R.zero_()
            self.ptr.G.zero_()
            for p in range(self.S):
                for s_, (a, o, opn) in (
                    (p, (2, 1 + p, 1)),
                    (self.S + p, (1, 1 + p, 0)),
                    (2 * self.S + p, (3, p, 2)),
                ):
                    self.ptr.R[s_, a, o - O_LO] = VINIT_SCALE
                    self.ptr.R[s_, opn, -O_LO] = 0.5 * VINIT_SCALE
                    self.ptr.G[s_, opn] = VINIT_SCALE
        self.digit = nn.Linear(D_MODEL, 10)
        self.step = AddStep(self.S)
        self.loc = nn.Sequential(
            nn.Linear(self.S * 10, 64), nn.GELU(), nn.Linear(64, 1))
        self.head = nn.Linear(10, spec.vocab_size)
        self.register_buffer("nstep", torch.zeros((), dtype=torch.long),
                             persistent=False)

    def forward(self, input_ids: Tensor, attention_mask: Tensor | None = None):
        b, L = input_ids.shape
        if attention_mask is None:
            mask = torch.ones(b, L, dtype=torch.bool, device=input_ids.device)
        else:
            mask = attention_mask.to(torch.bool)
            if mask.dim() == 3:
                mask = mask[:, 0]
        e = self.emb(input_ids)
        slots = self.ptr(e, mask)
        dg = F.softmax(self.digit(slots) / DIGIT_TAU, dim=-1)
        sx, sn, st = dg[:, : self.S], dg[:, self.S: 2 * self.S], dg[:, 2 * self.S:]
        z = F.softmax(self.step.zero, -1)[None, None].expand(b, 1, 10)
        nd = torch.cat([sn, z], dim=1)                       # (b, S+1, 10)

        loops = LOOPS
        if self.training and RAND_LOOPS:
            self.nstep += 1
            loops = int(torch.randint(1, LOOPS + 1, (1,)).item())
        state = sx
        outs = []
        for _ in range(loops):
            out = self.step(state, nd)
            outs.append(out)
            state = F.softmax(out, dim=-1)
        stacked = torch.stack(outs, dim=1)

        loc = self.loc(st.flatten(1))
        grid = torch.arange(loops, device=e.device, dtype=loc.dtype)[None, :]
        frac = (self.nstep.float() / ANNEAL_STEPS).clamp(max=1.0)
        sigma = (1.0 - 0.9 * frac).clamp(min=0.1)
        w = F.softmax(-((grid - loc) ** 2) / (2 * sigma ** 2), dim=-1)
        mixed = torch.einsum("bt,btsd->bsd", w, stacked)

        logits = input_ids.new_zeros(b, L, self.vocab, dtype=mixed.dtype)
        last = mask.long().sum(-1) - 1
        vals = self.head(mixed)
        for p in range(self.S):
            pos = (last - p).clamp(min=0)
            logits.scatter_(1, pos[:, None, None].expand(-1, 1, self.vocab),
                            vals[:, p][:, None, :])
        return logits, None


def build_model(spec: ModelSpec) -> Model:
    model = Model(spec)
    assert_model_state(model, spec)
    return model


def build_optimizer(model: nn.Module, spec: OptimizerSpec) -> OptimizerBundle:
    decay = [p for p in model.parameters() if p.ndim >= 2]
    no_decay = [p for p in model.parameters() if p.ndim < 2]
    return OptimizerBundle(
        torch.optim.AdamW(
            [{"params": decay, "weight_decay": WD},
             {"params": no_decay, "weight_decay": 0.0}],
            lr=LR, betas=(0.9, 0.95),
            capturable=spec.device_type == "cuda",
        )
    )


SUBMISSION = Submission(
    build_model=build_model,
    build_optimizer=build_optimizer,
    batch_size=_BATCH_SIZE,
    max_steps=_MAX_STEPS,
)
