"""alu-optimizer: G_soap_3e3 (generated by lab/make_optsub.py)."""

from __future__ import annotations

import math

import torch
import torch.nn.functional as F
from torch import Tensor, nn

from benchmark import (
    ModelSpec,
    OptimizerBundle,
    OptimizerSpec,
    Submission,
    assert_model_state,
)

CFG = {   'd': 128,
    'heads': 4,
    'mlp': 4,
    'blocks': 2,
    'loops': 1,
    'tie_head': True,
    'init': 'default',
    'init_gain': 1.0,
    'emb_init': 0.02,
    'opt': 'soap',
    'lr': 0.003,
    'lr_hidden': 0.02,
    'muon_mom': 0.95,
    'ns_steps': 5,
    'betas': [0.9, 0.98],
    'eps': 1e-08,
    'wd': 0.1,
    'wd_emb': 0.1,
    'emb_renorm': 0.0,
    'renorm_clip': True,
    'gf_alpha': 0.98,
    'gf_lambda': 0.0,
    'perp': False,
    'sched': 'const',
    'warmup': 0,
    'lr_floor': 0.0,
    'max_steps': 10000,
    'batch_size': 128,
    'eval_batch_size': 512,
    'loss': 'ce',
    'ls': 0.0,
    'focal_gamma': 2.0,
    'hard_tau': 1.0,
    'soap_freq': 10,
    'soap_max_dim': 512,
    'soap_merge': 1,
    'soap_beta': 0.95,
    'soap_warmup': 0,
    'ade_alpha': 8.0,
    'ade_beta2': 0.999,
    'ade_beta3': 0.9999,
    'ade_warmup': 0}


class Config:
    def __init__(self, vocab_size: int, max_seq_len: int) -> None:
        self.vocab_size = vocab_size
        self.max_seq_len = max_seq_len


class RMSNorm(nn.Module):
    def __init__(self, width: int) -> None:
        super().__init__()
        self.weight = nn.Parameter(torch.ones(width))

    def forward(self, x: Tensor) -> Tensor:
        return F.rms_norm(x, (x.shape[-1],), self.weight)


class Block(nn.Module):
    def __init__(self, d: int, heads: int, mult: int) -> None:
        super().__init__()
        self.heads = heads
        self.n1 = RMSNorm(d)
        self.qkv = nn.Linear(d, 3 * d, bias=False)
        self.proj = nn.Linear(d, d, bias=False)
        self.n2 = RMSNorm(d)
        self.up = nn.Linear(d, mult * d, bias=False)
        self.down = nn.Linear(mult * d, d, bias=False)

    def forward(self, x: Tensor, mask: Tensor | None) -> Tensor:
        b, l, d = x.shape
        h = self.n1(x)
        q, k, v = self.qkv(h).chunk(3, dim=-1)
        q = q.view(b, l, self.heads, -1).transpose(1, 2)
        k = k.view(b, l, self.heads, -1).transpose(1, 2)
        v = v.view(b, l, self.heads, -1).transpose(1, 2)
        a = F.scaled_dot_product_attention(q, k, v, attn_mask=mask)
        a = a.transpose(1, 2).reshape(b, l, d)
        x = x + self.proj(a)
        return x + self.down(F.gelu(self.up(self.n2(x))))


class Model(nn.Module):
    def __init__(self, spec: ModelSpec) -> None:
        super().__init__()
        self.config = Config(spec.vocab_size, spec.max_seq_len)
        d = CFG["d"]
        self.tok = nn.Embedding(spec.vocab_size, d)
        self.pos = nn.Embedding(spec.max_seq_len, d)
        self.blocks = nn.ModuleList(
            Block(d, CFG["heads"], CFG["mlp"]) for _ in range(CFG["blocks"])
        )
        self.loops = CFG["loops"]
        self.nf = RMSNorm(d)
        self.head = nn.Linear(d, spec.vocab_size, bias=False)
        if CFG["tie_head"]:
            self.head.weight = self.tok.weight
        self._init()

    def _init(self) -> None:
        scale = CFG["emb_init"]
        nn.init.normal_(self.tok.weight, std=scale)
        nn.init.normal_(self.pos.weight, std=scale)
        if CFG["init"] == "ortho":
            for m in self.modules():
                if isinstance(m, nn.Linear):
                    w = m.weight
                    if w.shape[0] >= w.shape[1]:
                        nn.init.orthogonal_(w, gain=CFG["init_gain"])
                    else:
                        t = torch.empty(w.shape[1], w.shape[0], device=w.device)
                        nn.init.orthogonal_(t, gain=CFG["init_gain"])
                        with torch.no_grad():
                            w.copy_(t.T)
        elif CFG["init"] == "small":
            for m in self.modules():
                if isinstance(m, nn.Linear):
                    nn.init.normal_(m.weight, std=CFG["init_gain"] / m.weight.shape[1] ** 0.5)

    def forward(
        self,
        input_ids: Tensor,
        attention_mask: Tensor | None = None,
    ) -> tuple[Tensor, None]:
        b, l = input_ids.shape
        mask = None
        if attention_mask is not None:
            mask = attention_mask.to(torch.bool)
            if mask.dim() == 2:
                mask = mask[:, None, None, :]
            else:
                mask = mask[:, None, :, :]
        positions = torch.arange(l, device=input_ids.device)
        x = self.tok(input_ids) + self.pos(positions)
        for _ in range(self.loops):
            for blk in self.blocks:
                x = blk(x, mask)
        return self.head(self.nf(x)), None


# ---------------------------------------------------------------------------
# optimizer: one custom torch.optim.Optimizer covering every trainable tensor
# ---------------------------------------------------------------------------

def _newtonschulz5(G: Tensor, steps: int) -> Tensor:
    """Orthogonalize G (Muon's zeroth-power via quintic Newton-Schulz)."""
    a, b, c = 3.4445, -4.7750, 2.0315
    X = G.to(torch.bfloat16)
    X = X / (X.norm() + 1e-7)
    transposed = X.shape[0] > X.shape[1]
    if transposed:
        X = X.T
    for _ in range(steps):
        A = X @ X.T
        B = b * A + c * (A @ A)
        X = a * X + B @ X
    if transposed:
        X = X.T
    return X.to(G.dtype)


# ---------------------------------------------------------------------------
# SOAP (Vyas et al. 2024) and AdEMAMix (Pagliardini et al. 2024), inlined.
# Verified in lab/test_optim_extra.py; see lab/optim_extra.py for the annotated
# source these are copied from.
# ---------------------------------------------------------------------------

def _merge_dims(shape, max_dim):
    new, cur = [], 1
    for sh in shape:
        if cur * sh > max_dim:
            if cur > 1:
                new.append(cur)
                cur = sh
            else:
                new.append(sh)
                cur = 1
        else:
            cur = cur * sh
    if cur > 1 or not new:
        new.append(cur)
    return tuple(new)


def _eigvecs(gg):
    d = gg.shape[-1]
    a = gg.float() + 1e-30 * torch.eye(d, device=gg.device)
    try:
        _, q = torch.linalg.eigh(a)
    except Exception:
        _, q = torch.linalg.eigh(a.double())
        q = q.float()
    return torch.flip(q, dims=[-1]).to(gg.dtype)


def _mm_axis(x, q, axis, back=False):
    x = x.movedim(axis, -1)
    shp = x.shape
    x2 = x.reshape(shp[0], -1, shp[-1])
    out = torch.bmm(x2, q.transpose(1, 2) if back else q)
    return out.reshape(shp).movedim(-1, axis)


def _reorder_axis(x, axis, idx):
    x = x.movedim(axis, -1)
    shp = x.shape
    x2 = x.reshape(shp[0], -1, shp[-1])
    out = torch.gather(x2, 2, idx[:, None, :].expand(-1, x2.shape[1], -1))
    return out.reshape(shp).movedim(-1, axis)


class SOAP(torch.optim.Optimizer):
    """Adam run in the eigenbasis of Shampoo's Kronecker-factored
    preconditioner.  Both moments live in the rotated basis (paper Alg. 1)."""

    def __init__(self, params, lr=1e-3, betas=(0.9, 0.95), shampoo_beta=0.95,
                 eps=1e-8, weight_decay=0.0, precondition_frequency=10,
                 max_precond_dim=512, merge_dims=True, batch_dims=0,
                 precondition_1d=True, precond_warmup=0):
        super().__init__(params, dict(
            lr=lr, betas=betas, shampoo_beta=shampoo_beta, eps=eps,
            weight_decay=weight_decay,
            precondition_frequency=precondition_frequency,
            max_precond_dim=max_precond_dim, merge_dims=merge_dims,
            batch_dims=batch_dims, precondition_1d=precondition_1d,
            precond_warmup=precond_warmup, scale=1.0))

    def _work_shape(self, p, group):
        bd = group["batch_dims"]
        rest = tuple(p.shape[bd:])
        if group["merge_dims"] and len(rest) > 1:
            rest = _merge_dims(rest, group["max_precond_dim"])
        b = 1
        for s in p.shape[:bd]:
            b *= s
        return b, rest

    def _accum(self, st, gw, group):
        beta = group["shampoo_beta"]
        nd = gw.dim() - 1
        if nd == 1 and not group["precondition_1d"]:
            return
        for i in range(nd):
            if st["GG"][i] is None:
                continue
            x = gw.movedim(1 + i, 1).reshape(gw.shape[0], gw.shape[1 + i], -1)
            st["GG"][i].lerp_(torch.bmm(x, x.transpose(1, 2)), 1.0 - beta)

    def _refresh(self, st, group, force=False):
        for i, gg in enumerate(st["GG"]):
            if gg is None:
                continue
            if st["Q"][i] is None or force:
                st["Q"][i] = _eigvecs(gg)
                continue
            q = st["Q"][i]
            est = torch.einsum("bij,bik,bkj->bj", q, gg, q)
            idx = est.argsort(dim=-1, descending=True)
            q = torch.gather(q, 2, idx[:, None, :].expand(-1, q.shape[1], -1))
            st["exp_avg_sq"] = _reorder_axis(st["exp_avg_sq"], 1 + i, idx)
            st["rot_avg"] = _reorder_axis(st["rot_avg"], 1 + i, idx)
            try:
                qn, _ = torch.linalg.qr(torch.bmm(gg, q))
            except Exception:
                qn = _eigvecs(gg)
            st["Q"][i] = qn

    def _project(self, x, st, back=False):
        for i, q in enumerate(st["Q"]):
            if q is not None:
                x = _mm_axis(x, q, 1 + i, back=back)
        return x

    @torch.no_grad()
    def step(self, closure=None):
        loss = None
        if closure is not None:
            with torch.enable_grad():
                loss = closure()
        for group in self.param_groups:
            b1, b2 = group["betas"]
            lr = group["lr"] * group["scale"]
            eps, wd = group["eps"], group["weight_decay"]
            for p in group["params"]:
                if p.grad is None:
                    continue
                g = p.grad
                st = self.state[p]
                b, rest = self._work_shape(p, group)
                nd = len(rest)
                if len(st) == 0:
                    st["step"] = 0
                    st["warm"] = 0
                    st["rot_avg"] = torch.zeros(b, *rest, device=p.device,
                                                dtype=p.dtype)
                    st["exp_avg_sq"] = torch.zeros(b, *rest, device=p.device,
                                                   dtype=p.dtype)
                    mx = group["max_precond_dim"]
                    ok = nd > 1 or group["precondition_1d"]
                    st["GG"] = [
                        torch.zeros(b, d, d, device=p.device, dtype=p.dtype)
                        if (ok and 1 < d <= mx) else None for d in rest]
                    st["Q"] = [None] * nd
                    self._accum(st, g.reshape(b, *rest), group)
                    self._refresh(st, group)
                    continue
                gw = g.reshape(b, *rest)
                if st["warm"] < group["precond_warmup"]:
                    st["warm"] += 1
                    self._accum(st, gw, group)
                    self._refresh(st, group, force=True)
                    continue
                gp = self._project(gw, st)
                st["step"] += 1
                k = st["step"]
                st["exp_avg_sq"].mul_(b2).addcmul_(gp, gp, value=1.0 - b2)
                st["rot_avg"].mul_(b1).add_(gp, alpha=1.0 - b1)
                bc1, bc2 = 1.0 - b1 ** k, 1.0 - b2 ** k
                denom = (st["exp_avg_sq"] / bc2).sqrt_().add_(eps)
                upd = self._project(st["rot_avg"] / bc1 / denom, st,
                                    back=True).reshape(p.shape)
                if wd:
                    p.mul_(1.0 - lr * wd)
                p.add_(upd, alpha=-lr)
                self._accum(st, gw, group)
                if k % group["precondition_frequency"] == 0:
                    self._refresh(st, group)
        return loss


def _ade_alpha(step, alpha, warmup):
    if warmup <= 0 or step >= warmup:
        return alpha
    return alpha * step / float(warmup)


def _ade_beta3(step, beta_end, beta_start, warmup):
    if warmup <= 0 or step >= warmup:
        return beta_end

    def hl(b):
        return math.log(0.5) / math.log(b + 1e-12) - 1.0

    a = step / float(warmup)
    return math.pow(0.5, 1.0 / ((1.0 - a) * hl(beta_start)
                                + a * hl(beta_end) + 1.0))


class AdEMAMix(torch.optim.Optimizer):
    """Fast EMA + un-bias-corrected slow EMA (beta3 ~ 0.9999), over Adam's
    second moment.  alpha and beta3 are warmed up as in the paper."""

    def __init__(self, params, lr=1e-3, betas=(0.9, 0.999, 0.9999), alpha=8.0,
                 eps=1e-8, weight_decay=0.0, warmup=0):
        b1, b2, b3 = betas
        super().__init__(params, dict(
            lr=lr, betas=(b1, b2, b3), alpha=alpha, eps=eps,
            weight_decay=weight_decay, warmup=warmup, beta3_start=b1,
            scale=1.0))

    @torch.no_grad()
    def step(self, closure=None):
        loss = None
        if closure is not None:
            with torch.enable_grad():
                loss = closure()
        for group in self.param_groups:
            b1, b2, b3 = group["betas"]
            lr = group["lr"] * group["scale"]
            eps, wd, warm = group["eps"], group["weight_decay"], group["warmup"]
            for p in group["params"]:
                if p.grad is None:
                    continue
                g = p.grad
                st = self.state[p]
                if len(st) == 0:
                    st["step"] = 0
                    st["m1"] = torch.zeros_like(p)
                    st["m2"] = torch.zeros_like(p)
                    st["nu"] = torch.zeros_like(p)
                st["step"] += 1
                k = st["step"]
                a_t = _ade_alpha(k, group["alpha"], warm)
                b3_t = _ade_beta3(k, b3, group["beta3_start"], warm)
                m1, m2, nu = st["m1"], st["m2"], st["nu"]
                m1.mul_(b1).add_(g, alpha=1.0 - b1)
                m2.mul_(b3_t).add_(g, alpha=1.0 - b3_t)
                nu.mul_(b2).addcmul_(g, g, value=1.0 - b2)
                denom = (nu / (1.0 - b2 ** k)).sqrt_().add_(eps)
                upd = (m1 / (1.0 - b1 ** k) + a_t * m2) / denom
                if wd:
                    p.mul_(1.0 - lr * wd)
                p.add_(upd, alpha=-lr)
        return loss


class GrokOpt(torch.optim.Optimizer):
    """AdamW / Muon / schedule-free-AdamW with optional Grokfast gradient EMA.

    Group flags:
      mode      : "adamw" | "muon" | "sf"
      wd        : decoupled weight decay
      renorm    : if > 0, project rows to this L2 norm after the update
    Grokfast (Lee et al. 2024): keep an EMA of the gradient and add it back,
    amplifying the slow component that drives delayed generalization.
    """

    def __init__(self, groups) -> None:
        defaults = dict(
            lr=1e-3,
            betas=(0.9, 0.98),
            eps=1e-8,
            wd=0.0,
            mode="adamw",
            ns_steps=5,
            renorm=0.0,
            gf_alpha=0.0,
            gf_lambda=0.0,
            perp=False,
            scale=1.0,
        )
        super().__init__(groups, defaults)

    @torch.no_grad()
    def step(self, closure=None):  # noqa: C901
        loss = None
        if closure is not None:
            with torch.enable_grad():
                loss = closure()
        for group in self.param_groups:
            mode = group["mode"]
            lr = group["lr"] * group["scale"]
            wd = group["wd"]
            b1, b2 = group["betas"]
            eps = group["eps"]
            gfa, gfl = group["gf_alpha"], group["gf_lambda"]
            for p in group["params"]:
                if p.grad is None:
                    continue
                g = p.grad
                st = self.state[p]
                if len(st) == 0:
                    st["k"] = 0
                    if gfl > 0.0:
                        st["gf"] = torch.zeros_like(p)
                    if mode == "muon":
                        st["m"] = torch.zeros_like(p)
                    elif mode == "sf":
                        st["z"] = p.detach().clone()
                        st["v"] = torch.zeros_like(p)
                    else:
                        st["m"] = torch.zeros_like(p)
                        st["v"] = torch.zeros_like(p)
                st["k"] += 1
                k = st["k"]
                if gfl > 0.0:
                    st["gf"].mul_(gfa).add_(g, alpha=1.0 - gfa)
                    g = g + gfl * st["gf"]
                if group["perp"]:
                    # orthogonal-gradient (perp-Grad): drop the component of the gradient parallel to the
                    # weights, so the loss cannot be reduced by merely scaling up
                    # the memorising solution (Prieto et al. 2025).
                    wn = p.pow(2).sum()
                    g = g - p * ((g * p).sum() / wn.clamp_min(1e-12))

                if mode == "muon":
                    m = st["m"]
                    m.mul_(b1).add_(g)
                    upd = g.add(m, alpha=b1) if group["nesterov"] else m
                    if upd.ndim == 2:
                        upd = _newtonschulz5(upd, group["ns_steps"])
                        upd = upd * max(1.0, upd.shape[0] / upd.shape[1]) ** 0.5
                    if wd:
                        p.mul_(1.0 - lr * wd)
                    p.add_(upd, alpha=-lr)
                elif mode == "sf":
                    # Schedule-Free AdamW (Defazio et al. 2024)
                    z, v = st["z"], st["v"]
                    v.mul_(b2).addcmul_(g, g, value=1.0 - b2)
                    bc2 = 1.0 - b2 ** k
                    denom = v.div(bc2).sqrt_().add_(eps)
                    gn = g.div(denom)
                    if wd:
                        gn = gn.add(p, alpha=wd)
                    lr_eff = lr * (bc2 ** 0.5)
                    group["_lrmax"] = max(group.get("_lrmax", 0.0), lr_eff)
                    weight = float(k) ** 2
                    group["_wsum"] = group.get("_wsum", 0.0) + weight
                    ckp1 = weight / group["_wsum"]
                    p.lerp_(z, ckp1)
                    p.add_(gn, alpha=lr_eff * (b1 * (1.0 - ckp1) - 1.0))
                    z.sub_(gn, alpha=lr_eff)
                else:  # adamw
                    m, v = st["m"], st["v"]
                    m.mul_(b1).add_(g, alpha=1.0 - b1)
                    v.mul_(b2).addcmul_(g, g, value=1.0 - b2)
                    bc1 = 1.0 - b1 ** k
                    bc2 = 1.0 - b2 ** k
                    denom = v.sqrt().div_(bc2 ** 0.5).add_(eps)
                    if wd:
                        p.mul_(1.0 - lr * wd)
                    p.addcdiv_(m, denom, value=-lr / bc1)

                r = group["renorm"]
                if r > 0.0 and p.ndim == 2:
                    n = p.norm(dim=-1, keepdim=True).clamp_min(1e-9)
                    p.mul_((r / n).clamp_max(1.0) if CFG["renorm_clip"] else (r / n))
        return loss


class Sched:
    """Participant LR schedule; evaluator calls step() once per optimizer step."""

    def __init__(self, opt, kind: str, total: int, warmup: int, floor: float) -> None:
        self.opt = opt
        self.kind = kind
        self.total = max(1, total)
        self.warmup = warmup
        self.floor = floor
        self.k = 0
        self._apply()

    def _factor(self) -> float:
        k, tot, w = self.k, self.total, self.warmup
        if self.kind == "const":
            return 1.0 if k >= w else (k + 1) / max(1, w)
        if k < w:
            return (k + 1) / max(1, w)
        t = min(1.0, (k - w) / max(1, tot - w))
        if self.kind == "cosine":
            return self.floor + (1.0 - self.floor) * 0.5 * (1.0 + math.cos(math.pi * t))
        if self.kind == "linear":
            return self.floor + (1.0 - self.floor) * (1.0 - t)
        return 1.0

    def _apply(self) -> None:
        f = self._factor()
        for g in self.opt.param_groups:
            g["scale"] = f

    def step(self) -> None:
        self.k += 1
        self._apply()


def build_model(spec: ModelSpec) -> Model:
    model = Model(spec)
    assert_model_state(model, spec)
    return model


def build_optimizer(model: nn.Module, spec: OptimizerSpec) -> OptimizerBundle:
    hidden, other = [], []
    for name, p in model.named_parameters():
        if not p.requires_grad:
            continue
        if p.ndim == 2 and not name.startswith(("tok", "pos", "head")):
            hidden.append(p)
        else:
            other.append(p)
    common = dict(
        betas=tuple(CFG["betas"]),
        eps=CFG["eps"],
        gf_alpha=CFG["gf_alpha"],
        gf_lambda=CFG["gf_lambda"],
        perp=bool(CFG["perp"]),
        nesterov=True,
        ns_steps=CFG["ns_steps"],
    )
    if CFG["opt"] in ("soap", "ademamix"):
        params = hidden + other
        if CFG["opt"] == "soap":
            opt = SOAP(params, lr=CFG["lr"], betas=tuple(CFG["betas"])[:2],
                       weight_decay=CFG["wd"], eps=CFG["eps"],
                       shampoo_beta=CFG["soap_beta"],
                       precondition_frequency=CFG["soap_freq"],
                       max_precond_dim=CFG["soap_max_dim"],
                       merge_dims=bool(CFG["soap_merge"]),
                       precond_warmup=CFG["soap_warmup"])
        else:
            opt = AdEMAMix(params, lr=CFG["lr"],
                           betas=(CFG["betas"][0], CFG["ade_beta2"],
                                  CFG["ade_beta3"]),
                           alpha=CFG["ade_alpha"], eps=CFG["eps"],
                           weight_decay=CFG["wd"], warmup=CFG["ade_warmup"])
        sched = Sched(opt, CFG["sched"], CFG["max_steps"], CFG["warmup"],
                      CFG["lr_floor"])
        return OptimizerBundle(opt, sched)
    if CFG["opt"] == "muon":
        groups = [
            dict(params=hidden, mode="muon", lr=CFG["lr_hidden"], wd=CFG["wd"],
                 betas=(CFG["muon_mom"], 0.0), eps=CFG["eps"], gf_alpha=CFG["gf_alpha"],
                 gf_lambda=CFG["gf_lambda"], nesterov=True, ns_steps=CFG["ns_steps"],
                 perp=bool(CFG["perp"]), renorm=0.0),
            dict(params=other, mode="adamw", lr=CFG["lr"], wd=CFG["wd_emb"],
                 renorm=CFG["emb_renorm"], **common),
        ]
    else:
        mode = "sf" if CFG["opt"] == "sf" else "adamw"
        groups = [
            dict(params=hidden, mode=mode, lr=CFG["lr"], wd=CFG["wd"], renorm=0.0,
                 **common),
            dict(params=other, mode=mode, lr=CFG["lr"], wd=CFG["wd_emb"],
                 renorm=CFG["emb_renorm"], **common),
        ]
    groups = [g for g in groups if g["params"]]
    opt = GrokOpt(groups)
    sched = Sched(opt, CFG["sched"], CFG["max_steps"], CFG["warmup"], CFG["lr_floor"])
    return OptimizerBundle(opt, sched)


def training_loss(logits: Tensor, labels: Tensor, aux) -> Tensor:
    """logits [n_valid_tokens, V], labels [n_valid_tokens] (already flattened)."""
    kind = CFG["loss"]
    if kind == "stablemax":
        # StableMax cross-entropy (Prieto et al. 2025): replaces exp() with a
        # linear/reciprocal surrogate so late-training logit growth cannot be
        # absorbed by float rounding ("softmax collapse").
        x = logits.float()
        x = x - x.mean(dim=-1, keepdim=True)
        # clamp each branch separately: computing 1/(1-x) on the x>=0 side would
        # produce inf at x=1 and torch.where would then back-propagate NaN.
        sx = torch.where(
            x >= 0,
            x.clamp_min(0.0) + 1.0,
            1.0 / (1.0 - x.clamp_max(0.0)),
        )
        logp = torch.log(sx.clamp_min(1e-30)) - torch.log(
            sx.sum(dim=-1, keepdim=True).clamp_min(1e-30)
        )
        return F.nll_loss(logp, labels)
    if kind == "ce":
        return F.cross_entropy(logits, labels, label_smoothing=CFG["ls"])
    per = F.cross_entropy(logits, labels, reduction="none", label_smoothing=CFG["ls"])
    if kind == "focal":
        pt = torch.exp(-per.detach())
        return ((1.0 - pt) ** CFG["focal_gamma"] * per).mean()
    if kind == "hard":
        # all-or-nothing scoring means the WORST token decides the sequence:
        # re-weight tokens by a softmax over their own loss (temperature tau).
        w = torch.softmax(per.detach() / CFG["hard_tau"], dim=0)
        return (w * per).sum()
    if kind == "maxent":
        # smooth maximum over tokens
        return CFG["hard_tau"] * torch.logsumexp(per / CFG["hard_tau"], dim=0)
    raise ValueError(kind)


SUBMISSION = Submission(
    build_model=build_model,
    build_optimizer=build_optimizer,
    training_loss=None if (CFG["loss"] == "ce" and CFG["ls"] == 0.0) else training_loss,
    batch_size=CFG["batch_size"],
    eval_batch_size=CFG["eval_batch_size"],
    max_steps=CFG["max_steps"],
)
