"""GRNet submission (generated by lab/make_grnet.py).

config: quad=1 pos=both W=2 K=256 H=1 tcond=0
        revhead=1 attn=0 lr=0.01 wd=0.3 batch=512
"""

from __future__ import annotations

import torch
import torch.nn.functional as F
from torch import Tensor, nn

from benchmark import (
    ModelSpec,
    OptimizerBundle,
    OptimizerSpec,
    Submission,
    assert_model_state,
)

WIDTH = 2
N_FREQ = 256
N_HARM = 1
USE_QUAD = 1
POS_MODE = "both"
USE_TCOND = 0
REV_HEAD = 1
ATTN_LOOPS = 0
D_ATTN = 128
_LR = 0.01
_WD = 0.3
_BATCH = 512
_MAX_STEPS = None


class Config:
    def __init__(self, vocab_size: int, max_seq_len: int) -> None:
        self.vocab_size = vocab_size
        self.max_seq_len = max_seq_len


class RMSNorm(nn.Module):
    def __init__(self, width: int) -> None:
        super().__init__()
        self.weight = nn.Parameter(torch.ones(width))

    def forward(self, x: Tensor) -> Tensor:
        return F.rms_norm(x, (x.shape[-1],), self.weight)


class PosTokenPool(nn.Module):
    """sum_p  E[pos_p, tok_p]  -- the exact shape of a place-valued decimal sum.

    Indexing the table by (position, token) rather than adding a position
    embedding to a token embedding is what makes a *product* of position and
    digit (i.e. 10^i * d_i) representable at all.
    """

    def __init__(self, max_seq_len: int, vocab_size: int, width: int, n_out: int) -> None:
        super().__init__()
        self.vocab_size = vocab_size
        self.max_seq_len = max_seq_len
        tables = 2 if POS_MODE == "both" else 1
        self.tables = nn.ModuleList(
            nn.Embedding(max_seq_len * vocab_size, width * n_out) for _ in range(tables)
        )
        for table in self.tables:
            nn.init.normal_(table.weight, std=0.2)
        self.n_out = n_out
        self.width = width

    def forward(self, abs_idx: Tensor, rev_idx: Tensor, fkeep: Tensor) -> Tensor:
        idxs = []
        if POS_MODE in ("abs", "both"):
            idxs.append(abs_idx)
        if POS_MODE in ("rev", "both"):
            idxs.append(rev_idx)
        total = None
        for table, idx in zip(self.tables, idxs):
            term = (table(idx) * fkeep).sum(dim=1)
            total = term if total is None else total + term
        return total.view(-1, self.n_out, self.width)


class AttnStack(nn.Module):
    """Optional small bidirectional attention stack, used only to let the model
    resolve where the x-field and T-field are when the prompt length varies."""

    def __init__(self, max_seq_len: int, vocab_size: int) -> None:
        super().__init__()
        self.embed = nn.Embedding(max_seq_len * vocab_size, D_ATTN)
        self.norm1 = RMSNorm(D_ATTN)
        self.qkv = nn.Linear(D_ATTN, 3 * D_ATTN)
        self.proj = nn.Linear(D_ATTN, D_ATTN)
        self.norm2 = RMSNorm(D_ATTN)
        self.up = nn.Linear(D_ATTN, 4 * D_ATTN)
        self.down = nn.Linear(4 * D_ATTN, D_ATTN)

    def forward(self, abs_idx: Tensor, mask: Tensor) -> Tensor:
        x = self.embed(abs_idx)
        for _ in range(ATTN_LOOPS):
            h = self.norm1(x)
            batch, length, _ = h.shape
            q, k, v = self.qkv(h).chunk(3, dim=-1)
            q = q.view(batch, length, 4, -1).transpose(1, 2)
            k = k.view(batch, length, 4, -1).transpose(1, 2)
            v = v.view(batch, length, 4, -1).transpose(1, 2)
            a = F.scaled_dot_product_attention(q, k, v, attn_mask=mask)
            x = x + self.proj(a.transpose(1, 2).contiguous().view(batch, length, D_ATTN))
            x = x + self.down(F.gelu(self.up(self.norm2(x))))
        return x


class Model(nn.Module):
    def __init__(self, spec: ModelSpec) -> None:
        super().__init__()
        self.config = Config(spec.vocab_size, spec.max_seq_len)
        V, L = spec.vocab_size, spec.max_seq_len
        self.vocab_size = V
        self.max_seq_len = L
        n_pool = 2 if USE_QUAD else 1
        self.pool = PosTokenPool(L, V, WIDTH, n_pool)
        feat_in = WIDTH * (2 if USE_QUAD else 1)
        self.to_theta = nn.Linear(feat_in, N_FREQ)
        # A learned per-frequency log-scale.  The useful frequencies span orders
        # of magnitude (a phase must wrap over the whole value range), which an
        # additive optimizer reaches very slowly through a plain linear weight.
        self.theta_scale = nn.Parameter(torch.zeros(N_FREQ))
        n_feat = 2 * N_HARM * N_FREQ
        rows = L if REV_HEAD else 1
        self.readout = nn.Parameter(torch.randn(rows, n_feat, V) * (n_feat ** -0.5))
        self.readout_bias = nn.Parameter(torch.zeros(rows, V))
        if ATTN_LOOPS:
            self.attn = AttnStack(L, V)
            self.attn_theta = nn.Linear(D_ATTN, N_FREQ)
            nn.init.zeros_(self.attn_theta.weight)
            nn.init.zeros_(self.attn_theta.bias)
            self.attn_head = nn.Linear(D_ATTN, V)
            nn.init.zeros_(self.attn_head.weight)
            nn.init.zeros_(self.attn_head.bias)
        if USE_TCOND:
            # A learned per-frequency angle multiplier, read from the prompt by a
            # learned pooled embedding.  theta -> theta * m turns the state's
            # phase into the phase of a learned power of the group element, which
            # is what makes *any* T reachable at constant depth.
            self.t_pool = PosTokenPool(L, V, WIDTH, 1)
            self.t_mlp = nn.Sequential(
                nn.Linear(WIDTH, 4 * WIDTH), nn.GELU(), nn.Linear(4 * WIDTH, N_FREQ)
            )
            nn.init.zeros_(self.t_mlp[-1].weight)
            nn.init.zeros_(self.t_mlp[-1].bias)

    def forward(
        self, input_ids: Tensor, attention_mask: Tensor | None = None
    ) -> tuple[Tensor, None]:
        batch, length = input_ids.shape
        device = input_ids.device
        if attention_mask is None:
            keep = torch.ones(batch, length, dtype=torch.bool, device=device)
            mask = None
        elif attention_mask.dim() == 2:
            keep = attention_mask.to(torch.bool)
            mask = keep[:, None, None, :]
        else:
            mask = attention_mask.to(torch.bool)[:, None, :, :]
            keep = mask.any(dim=1).any(dim=1)

        positions = torch.arange(length, device=device)
        lengths = keep.sum(dim=1, keepdim=True)
        rev = (lengths - 1 - positions[None, :]).clamp_(0, self.max_seq_len - 1)
        abs_idx = positions[None, :].clamp(max=self.max_seq_len - 1) * self.vocab_size
        abs_idx = abs_idx + input_ids
        rev_idx = rev * self.vocab_size + input_ids

        with torch.autocast(device_type=device.type, enabled=False):
            fkeep = keep.float()[..., None]
            pooled = self.pool(abs_idx, rev_idx, fkeep)  # B, n_pool, WIDTH
            if USE_QUAD:
                u, v = pooled[:, 0], pooled[:, 1]
                feats_in = torch.cat((u * v, u), dim=-1)
            else:
                feats_in = pooled[:, 0]
            theta = self.to_theta(feats_in) * torch.exp(self.theta_scale)  # B, K
            if USE_TCOND:
                t = self.t_pool(abs_idx, rev_idx, fkeep)[:, 0]
                theta = theta * (1.0 + self.t_mlp(t))
            parts = []
            for harmonic in range(1, N_HARM + 1):
                ang = theta * float(harmonic)
                parts.append(torch.cos(ang))
                parts.append(torch.sin(ang))
            feats = torch.cat(parts, dim=-1)  # B, 2*H*K
            if REV_HEAD:
                out = torch.einsum("bf,rfv->brv", feats, self.readout) + self.readout_bias
                gather = rev[..., None].expand(batch, length, self.vocab_size)
                logits = out.gather(1, gather)
            else:
                logits = (feats @ self.readout[0] + self.readout_bias[0])[:, None, :]
                logits = logits.expand(batch, length, self.vocab_size)
            logits = logits.contiguous()
        if ATTN_LOOPS:
            hidden = self.attn(abs_idx, mask)
            logits = logits + self.attn_head(hidden).float()
        return logits, None


def build_model(spec: ModelSpec) -> Model:
    model = Model(spec)
    assert_model_state(model, spec)
    return model


def build_optimizer(model: nn.Module, spec: OptimizerSpec) -> OptimizerBundle:
    decay, no_decay = [], []
    for _, param in model.named_parameters():
        (no_decay if param.ndim < 2 else decay).append(param)
    return OptimizerBundle(
        torch.optim.AdamW(
            [
                {"params": decay, "weight_decay": _WD},
                {"params": no_decay, "weight_decay": 0.0},
            ],
            lr=_LR,
            betas=(0.9, 0.95),
            capturable=spec.device_type == "cuda",
        )
    )


SUBMISSION = Submission(
    build_model=build_model,
    build_optimizer=build_optimizer,
    batch_size=_BATCH,
    max_steps=_MAX_STEPS,
)
