"""GRIter submission (generated by lab/make_griter.py).

config: slots=4 loops=1 K=32 H=8 dattn=128
        temp=1.0 lr=0.003 wd=0.1 batch=512
"""

from __future__ import annotations

import torch
import torch.nn.functional as F
from torch import Tensor, nn

from benchmark import (
    ModelSpec,
    OptimizerBundle,
    OptimizerSpec,
    Submission,
    assert_model_state,
)

SLOTS = 4
LOOPS = 1
N_FREQ = 32
N_HARM = 8
D_ATTN = 128
TEMP = 1.0
_LR = 0.003
_WD = 0.1
_BATCH = 512
_MAX_STEPS = None


class Config:
    def __init__(self, vocab_size: int, max_seq_len: int) -> None:
        self.vocab_size = vocab_size
        self.max_seq_len = max_seq_len


class SquaringBlock(nn.Module):
    """One shared step: soft digit slots -> pairwise phase -> soft digit slots."""

    def __init__(self, slots: int, n_freq: int, n_harm: int, alphabet: int) -> None:
        super().__init__()
        self.pairs = [(i, j) for i in range(slots) for j in range(i, slots)]
        self.table = nn.Parameter(
            torch.randn(len(self.pairs), alphabet, alphabet, n_freq) * 0.5
        )
        self.n_harm = n_harm
        feat = 2 * n_harm * n_freq
        self.readout = nn.Parameter(torch.randn(slots, feat, alphabet) * feat**-0.5)
        self.bias = nn.Parameter(torch.zeros(slots, alphabet))

    def forward(self, state: Tensor) -> Tensor:
        theta = None
        for n, (i, j) in enumerate(self.pairs):
            term = torch.einsum("ba,bc,acf->bf", state[:, i], state[:, j], self.table[n])
            theta = term if theta is None else theta + term
        parts = []
        for harmonic in range(1, self.n_harm + 1):
            ang = theta * float(harmonic)
            parts.append(torch.cos(ang))
            parts.append(torch.sin(ang))
        feats = torch.cat(parts, dim=-1)
        return torch.einsum("bf,ifa->bia", feats, self.readout) + self.bias


class Model(nn.Module):
    def __init__(self, spec: ModelSpec) -> None:
        super().__init__()
        self.config = Config(spec.vocab_size, spec.max_seq_len)
        V, L = spec.vocab_size, spec.max_seq_len
        self.vocab_size = V
        self.max_seq_len = L
        self.embed = nn.Embedding(L * V, D_ATTN)
        # learned slot queries: where in the prompt each working digit comes from
        self.slot_query = nn.Parameter(torch.randn(SLOTS, D_ATTN) * D_ATTN**-0.5)
        # learned map from the token alphabet to the model's working alphabet
        self.to_alphabet = nn.Parameter(torch.randn(V, V) * V**-0.5)
        self.block = SquaringBlock(SLOTS, N_FREQ, N_HARM, V)
        # learned selector over composition depth, pooled from the prompt
        self.pool_query = nn.Parameter(torch.randn(D_ATTN) * D_ATTN**-0.5)
        self.selector = nn.Sequential(
            nn.Linear(D_ATTN, 4 * D_ATTN), nn.GELU(), nn.Linear(4 * D_ATTN, LOOPS)
        )
        self.slot_bias = nn.Parameter(torch.zeros(L, V))

    def forward(
        self, input_ids: Tensor, attention_mask: Tensor | None = None
    ) -> tuple[Tensor, None]:
        batch, length = input_ids.shape
        device = input_ids.device
        if attention_mask is None:
            keep = torch.ones(batch, length, dtype=torch.bool, device=device)
        elif attention_mask.dim() == 2:
            keep = attention_mask.to(torch.bool)
        else:
            keep = attention_mask.to(torch.bool).any(dim=1)

        positions = torch.arange(length, device=device).clamp(max=self.max_seq_len - 1)
        hidden = self.embed(positions[None, :] * self.vocab_size + input_ids)

        with torch.autocast(device_type=device.type, enabled=False):
            hidden = hidden.float()
            neg = torch.finfo(hidden.dtype).min
            # slot extraction: S learned queries attend over the prompt
            scores = torch.einsum("bld,sd->bsl", hidden, self.slot_query)
            scores = scores.masked_fill(~keep[:, None, :], neg)
            attn = F.softmax(scores, dim=-1)
            tokens = F.one_hot(input_ids, self.vocab_size).float()
            state = torch.einsum("bsl,blv,vw->bsw", attn, tokens, self.to_alphabet)
            state = F.softmax(state, dim=-1)

            outs = []
            for _ in range(LOOPS):
                step = self.block(state)
                outs.append(step)
                state = F.softmax(step / TEMP, dim=-1)
            stacked = torch.stack(outs, dim=1)  # B, LOOPS, SLOTS, V

            pool_scores = (hidden @ self.pool_query).masked_fill(~keep, neg)
            pooled = (F.softmax(pool_scores, dim=-1)[..., None] * hidden).sum(dim=1)
            weights = F.softmax(self.selector(pooled), dim=-1)
            chosen = torch.einsum("bt,btsv->bsv", weights, stacked)

            # answers are tail-aligned: working slot r feeds prompt position
            # (len-1-r), i.e. slot 0 is the least significant answer digit.
            lengths = keep.sum(dim=1, keepdim=True)
            rev = (lengths - 1 - torch.arange(length, device=device)[None, :]).clamp(
                0, self.max_seq_len - 1
            )
            padded = F.pad(chosen, (0, 0, 0, max(0, self.max_seq_len - SLOTS)))
            logits = padded.gather(
                1, rev.clamp(max=padded.shape[1] - 1)[..., None].expand(
                    batch, length, self.vocab_size
                )
            )
            logits = logits + self.slot_bias[rev]
        return logits.contiguous(), None


def build_model(spec: ModelSpec) -> Model:
    model = Model(spec)
    assert_model_state(model, spec)
    return model


def build_optimizer(model: nn.Module, spec: OptimizerSpec) -> OptimizerBundle:
    decay, no_decay = [], []
    for _, param in model.named_parameters():
        (no_decay if param.ndim < 2 else decay).append(param)
    return OptimizerBundle(
        torch.optim.AdamW(
            [
                {"params": decay, "weight_decay": _WD},
                {"params": no_decay, "weight_decay": 0.0},
            ],
            lr=_LR,
            betas=(0.9, 0.95),
            capturable=spec.device_type == "cuda",
        )
    )


SUBMISSION = Submission(
    build_model=build_model,
    build_optimizer=build_optimizer,
    batch_size=_BATCH,
    max_steps=_MAX_STEPS,
)
