"""grok-optimization: A_wd3.0_bs128_lr1e-3_10k (generated by lab/make_grok.py)."""

from __future__ import annotations

import math

import torch
import torch.nn.functional as F
from torch import Tensor, nn

from benchmark import (
    ModelSpec,
    OptimizerBundle,
    OptimizerSpec,
    Submission,
    assert_model_state,
)

CFG = {   'd': 128,
    'heads': 4,
    'mlp': 4,
    'blocks': 2,
    'loops': 1,
    'tie_head': True,
    'init': 'default',
    'init_gain': 1.0,
    'emb_init': 0.02,
    'opt': 'adamw',
    'lr': 0.001,
    'lr_hidden': 0.02,
    'muon_mom': 0.95,
    'ns_steps': 5,
    'betas': [0.9, 0.98],
    'eps': 1e-08,
    'wd': 3.0,
    'wd_emb': 3.0,
    'emb_renorm': 0.0,
    'renorm_clip': True,
    'gf_alpha': 0.98,
    'gf_lambda': 0.0,
    'sched': 'const',
    'warmup': 0,
    'lr_floor': 0.0,
    'max_steps': 10000,
    'batch_size': 128,
    'eval_batch_size': 512,
    'loss': 'ce',
    'ls': 0.0,
    'focal_gamma': 2.0,
    'hard_tau': 1.0}


class Config:
    def __init__(self, vocab_size: int, max_seq_len: int) -> None:
        self.vocab_size = vocab_size
        self.max_seq_len = max_seq_len


class RMSNorm(nn.Module):
    def __init__(self, width: int) -> None:
        super().__init__()
        self.weight = nn.Parameter(torch.ones(width))

    def forward(self, x: Tensor) -> Tensor:
        return F.rms_norm(x, (x.shape[-1],), self.weight)


class Block(nn.Module):
    def __init__(self, d: int, heads: int, mult: int) -> None:
        super().__init__()
        self.heads = heads
        self.n1 = RMSNorm(d)
        self.qkv = nn.Linear(d, 3 * d, bias=False)
        self.proj = nn.Linear(d, d, bias=False)
        self.n2 = RMSNorm(d)
        self.up = nn.Linear(d, mult * d, bias=False)
        self.down = nn.Linear(mult * d, d, bias=False)

    def forward(self, x: Tensor, mask: Tensor | None) -> Tensor:
        b, l, d = x.shape
        h = self.n1(x)
        q, k, v = self.qkv(h).chunk(3, dim=-1)
        q = q.view(b, l, self.heads, -1).transpose(1, 2)
        k = k.view(b, l, self.heads, -1).transpose(1, 2)
        v = v.view(b, l, self.heads, -1).transpose(1, 2)
        a = F.scaled_dot_product_attention(q, k, v, attn_mask=mask)
        a = a.transpose(1, 2).reshape(b, l, d)
        x = x + self.proj(a)
        return x + self.down(F.gelu(self.up(self.n2(x))))


class Model(nn.Module):
    def __init__(self, spec: ModelSpec) -> None:
        super().__init__()
        self.config = Config(spec.vocab_size, spec.max_seq_len)
        d = CFG["d"]
        self.tok = nn.Embedding(spec.vocab_size, d)
        self.pos = nn.Embedding(spec.max_seq_len, d)
        self.blocks = nn.ModuleList(
            Block(d, CFG["heads"], CFG["mlp"]) for _ in range(CFG["blocks"])
        )
        self.loops = CFG["loops"]
        self.nf = RMSNorm(d)
        self.head = nn.Linear(d, spec.vocab_size, bias=False)
        if CFG["tie_head"]:
            self.head.weight = self.tok.weight
        self._init()

    def _init(self) -> None:
        scale = CFG["emb_init"]
        nn.init.normal_(self.tok.weight, std=scale)
        nn.init.normal_(self.pos.weight, std=scale)
        if CFG["init"] == "ortho":
            for m in self.modules():
                if isinstance(m, nn.Linear):
                    w = m.weight
                    if w.shape[0] >= w.shape[1]:
                        nn.init.orthogonal_(w, gain=CFG["init_gain"])
                    else:
                        t = torch.empty(w.shape[1], w.shape[0], device=w.device)
                        nn.init.orthogonal_(t, gain=CFG["init_gain"])
                        with torch.no_grad():
                            w.copy_(t.T)
        elif CFG["init"] == "small":
            for m in self.modules():
                if isinstance(m, nn.Linear):
                    nn.init.normal_(m.weight, std=CFG["init_gain"] / m.weight.shape[1] ** 0.5)

    def forward(
        self,
        input_ids: Tensor,
        attention_mask: Tensor | None = None,
    ) -> tuple[Tensor, None]:
        b, l = input_ids.shape
        mask = None
        if attention_mask is not None:
            mask = attention_mask.to(torch.bool)
            if mask.dim() == 2:
                mask = mask[:, None, None, :]
            else:
                mask = mask[:, None, :, :]
        positions = torch.arange(l, device=input_ids.device)
        x = self.tok(input_ids) + self.pos(positions)
        for _ in range(self.loops):
            for blk in self.blocks:
                x = blk(x, mask)
        return self.head(self.nf(x)), None


# ---------------------------------------------------------------------------
# optimizer: one custom torch.optim.Optimizer covering every trainable tensor
# ---------------------------------------------------------------------------

def _newtonschulz5(G: Tensor, steps: int) -> Tensor:
    """Orthogonalize G (Muon's zeroth-power via quintic Newton-Schulz)."""
    a, b, c = 3.4445, -4.7750, 2.0315
    X = G.to(torch.bfloat16)
    X = X / (X.norm() + 1e-7)
    transposed = X.shape[0] > X.shape[1]
    if transposed:
        X = X.T
    for _ in range(steps):
        A = X @ X.T
        B = b * A + c * (A @ A)
        X = a * X + B @ X
    if transposed:
        X = X.T
    return X.to(G.dtype)


class GrokOpt(torch.optim.Optimizer):
    """AdamW / Muon / schedule-free-AdamW with optional Grokfast gradient EMA.

    Group flags:
      mode      : "adamw" | "muon" | "sf"
      wd        : decoupled weight decay
      renorm    : if > 0, project rows to this L2 norm after the update
    Grokfast (Lee et al. 2024): keep an EMA of the gradient and add it back,
    amplifying the slow component that drives delayed generalization.
    """

    def __init__(self, groups) -> None:
        defaults = dict(
            lr=1e-3,
            betas=(0.9, 0.98),
            eps=1e-8,
            wd=0.0,
            mode="adamw",
            ns_steps=5,
            renorm=0.0,
            gf_alpha=0.0,
            gf_lambda=0.0,
            scale=1.0,
        )
        super().__init__(groups, defaults)

    @torch.no_grad()
    def step(self, closure=None):  # noqa: C901
        loss = None
        if closure is not None:
            with torch.enable_grad():
                loss = closure()
        for group in self.param_groups:
            mode = group["mode"]
            lr = group["lr"] * group["scale"]
            wd = group["wd"]
            b1, b2 = group["betas"]
            eps = group["eps"]
            gfa, gfl = group["gf_alpha"], group["gf_lambda"]
            for p in group["params"]:
                if p.grad is None:
                    continue
                g = p.grad
                st = self.state[p]
                if len(st) == 0:
                    st["k"] = 0
                    if gfl > 0.0:
                        st["gf"] = torch.zeros_like(p)
                    if mode == "muon":
                        st["m"] = torch.zeros_like(p)
                    elif mode == "sf":
                        st["z"] = p.detach().clone()
                        st["v"] = torch.zeros_like(p)
                    else:
                        st["m"] = torch.zeros_like(p)
                        st["v"] = torch.zeros_like(p)
                st["k"] += 1
                k = st["k"]
                if gfl > 0.0:
                    st["gf"].mul_(gfa).add_(g, alpha=1.0 - gfa)
                    g = g + gfl * st["gf"]

                if mode == "muon":
                    m = st["m"]
                    m.mul_(b1).add_(g)
                    upd = g.add(m, alpha=b1) if group["nesterov"] else m
                    if upd.ndim == 2:
                        upd = _newtonschulz5(upd, group["ns_steps"])
                        upd = upd * max(1.0, upd.shape[0] / upd.shape[1]) ** 0.5
                    if wd:
                        p.mul_(1.0 - lr * wd)
                    p.add_(upd, alpha=-lr)
                elif mode == "sf":
                    # Schedule-Free AdamW (Defazio et al. 2024)
                    z, v = st["z"], st["v"]
                    v.mul_(b2).addcmul_(g, g, value=1.0 - b2)
                    bc2 = 1.0 - b2 ** k
                    denom = v.div(bc2).sqrt_().add_(eps)
                    gn = g.div(denom)
                    if wd:
                        gn = gn.add(p, alpha=wd)
                    lr_eff = lr * (bc2 ** 0.5)
                    group["_lrmax"] = max(group.get("_lrmax", 0.0), lr_eff)
                    weight = float(k) ** 2
                    group["_wsum"] = group.get("_wsum", 0.0) + weight
                    ckp1 = weight / group["_wsum"]
                    p.lerp_(z, ckp1)
                    p.add_(gn, alpha=lr_eff * (b1 * (1.0 - ckp1) - 1.0))
                    z.sub_(gn, alpha=lr_eff)
                else:  # adamw
                    m, v = st["m"], st["v"]
                    m.mul_(b1).add_(g, alpha=1.0 - b1)
                    v.mul_(b2).addcmul_(g, g, value=1.0 - b2)
                    bc1 = 1.0 - b1 ** k
                    bc2 = 1.0 - b2 ** k
                    denom = v.sqrt().div_(bc2 ** 0.5).add_(eps)
                    if wd:
                        p.mul_(1.0 - lr * wd)
                    p.addcdiv_(m, denom, value=-lr / bc1)

                r = group["renorm"]
                if r > 0.0 and p.ndim == 2:
                    n = p.norm(dim=-1, keepdim=True).clamp_min(1e-9)
                    p.mul_((r / n).clamp_max(1.0) if CFG["renorm_clip"] else (r / n))
        return loss


class Sched:
    """Participant LR schedule; evaluator calls step() once per optimizer step."""

    def __init__(self, opt, kind: str, total: int, warmup: int, floor: float) -> None:
        self.opt = opt
        self.kind = kind
        self.total = max(1, total)
        self.warmup = warmup
        self.floor = floor
        self.k = 0
        self._apply()

    def _factor(self) -> float:
        k, tot, w = self.k, self.total, self.warmup
        if self.kind == "const":
            return 1.0 if k >= w else (k + 1) / max(1, w)
        if k < w:
            return (k + 1) / max(1, w)
        t = min(1.0, (k - w) / max(1, tot - w))
        if self.kind == "cosine":
            return self.floor + (1.0 - self.floor) * 0.5 * (1.0 + math.cos(math.pi * t))
        if self.kind == "linear":
            return self.floor + (1.0 - self.floor) * (1.0 - t)
        return 1.0

    def _apply(self) -> None:
        f = self._factor()
        for g in self.opt.param_groups:
            g["scale"] = f

    def step(self) -> None:
        self.k += 1
        self._apply()


def build_model(spec: ModelSpec) -> Model:
    model = Model(spec)
    assert_model_state(model, spec)
    return model


def build_optimizer(model: nn.Module, spec: OptimizerSpec) -> OptimizerBundle:
    hidden, other = [], []
    for name, p in model.named_parameters():
        if not p.requires_grad:
            continue
        if p.ndim == 2 and not name.startswith(("tok", "pos", "head")):
            hidden.append(p)
        else:
            other.append(p)
    common = dict(
        betas=tuple(CFG["betas"]),
        eps=CFG["eps"],
        gf_alpha=CFG["gf_alpha"],
        gf_lambda=CFG["gf_lambda"],
        nesterov=True,
        ns_steps=CFG["ns_steps"],
    )
    if CFG["opt"] == "muon":
        groups = [
            dict(params=hidden, mode="muon", lr=CFG["lr_hidden"], wd=CFG["wd"],
                 betas=(CFG["muon_mom"], 0.0), eps=CFG["eps"], gf_alpha=CFG["gf_alpha"],
                 gf_lambda=CFG["gf_lambda"], nesterov=True, ns_steps=CFG["ns_steps"],
                 renorm=0.0),
            dict(params=other, mode="adamw", lr=CFG["lr"], wd=CFG["wd_emb"],
                 renorm=CFG["emb_renorm"], **common),
        ]
    else:
        mode = "sf" if CFG["opt"] == "sf" else "adamw"
        groups = [
            dict(params=hidden, mode=mode, lr=CFG["lr"], wd=CFG["wd"], renorm=0.0,
                 **common),
            dict(params=other, mode=mode, lr=CFG["lr"], wd=CFG["wd_emb"],
                 renorm=CFG["emb_renorm"], **common),
        ]
    groups = [g for g in groups if g["params"]]
    opt = GrokOpt(groups)
    sched = Sched(opt, CFG["sched"], CFG["max_steps"], CFG["warmup"], CFG["lr_floor"])
    return OptimizerBundle(opt, sched)


def training_loss(logits: Tensor, labels: Tensor, aux) -> Tensor:
    """logits [n_valid_tokens, V], labels [n_valid_tokens] (already flattened)."""
    kind = CFG["loss"]
    if kind == "ce":
        return F.cross_entropy(logits, labels, label_smoothing=CFG["ls"])
    per = F.cross_entropy(logits, labels, reduction="none", label_smoothing=CFG["ls"])
    if kind == "focal":
        pt = torch.exp(-per.detach())
        return ((1.0 - pt) ** CFG["focal_gamma"] * per).mean()
    if kind == "hard":
        # all-or-nothing scoring means the WORST token decides the sequence:
        # re-weight tokens by a softmax over their own loss (temperature tau).
        w = torch.softmax(per.detach() / CFG["hard_tau"], dim=0)
        return (w * per).sum()
    if kind == "maxent":
        # smooth maximum over tokens
        return CFG["hard_tau"] * torch.logsumexp(per / CFG["hard_tau"], dim=0)
    raise ValueError(kind)


SUBMISSION = Submission(
    build_model=build_model,
    build_optimizer=build_optimizer,
    training_loss=None if CFG["loss"] == "ce" and CFG["ls"] == 0.0 else training_loss,
    batch_size=CFG["batch_size"],
    eval_batch_size=CFG["eval_batch_size"],
    max_steps=CFG["max_steps"],
)
