"""algebraic-closure :: d1_drop02

Generated by lab/make_closure.py.  See that file for the compliance record.
"""

from __future__ import annotations

import torch
import torch.nn.functional as F
from torch import Tensor, nn

from benchmark import (
    ModelSpec,
    OptimizerBundle,
    OptimizerSpec,
    Submission,
    assert_model_state,
)

# ------------------------------------------------------------------ config
D_MODEL = 128
NUM_HEADS = 4
NUM_LAYERS = 4
FF_MULT = 4
DIGIT_DIM = 128
OP_DROPOUT = 0.2
LAM_COMPOSE = 0.0
LAM_RAND = 0.0
LAM_IDENT = 0.0
RAND_MODE = "uniform"
SYMMETRIC = False
STRAIGHT_THROUGH = False
LR = 0.001
WD = 0.1
DIAG_EVERY = 200
_BATCH_SIZE = 64
_MAX_STEPS = None

# public token ids (data/squaring_mod.py :: TOKEN_IDS, DIGIT_OFFSET)
TOK_N, TOK_X, TOK_T = 2, 3, 4
DIGIT_OFFSET = 7
NUM_DIGITS = 10
T_SLOTS = 3
_NEG = -20.0


class Config:
    def __init__(self, vocab_size: int, max_seq_len: int) -> None:
        self.vocab_size = vocab_size
        self.max_seq_len = max_seq_len


class RMSNorm(nn.Module):
    def __init__(self, width: int) -> None:
        super().__init__()
        self.weight = nn.Parameter(torch.ones(width))

    def forward(self, x: Tensor) -> Tensor:
        return F.rms_norm(x, (x.shape[-1],), self.weight)


class Block(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.attention_norm = RMSNorm(D_MODEL)
        self.qkv = nn.Linear(D_MODEL, 3 * D_MODEL)
        self.out = nn.Linear(D_MODEL, D_MODEL)
        self.mixer_norm = RMSNorm(D_MODEL)
        self.up = nn.Linear(D_MODEL, FF_MULT * D_MODEL)
        self.down = nn.Linear(FF_MULT * D_MODEL, D_MODEL)

    def forward(self, x: Tensor) -> Tensor:
        residual = x
        y = self.attention_norm(x)
        batch, length, _ = y.shape
        q, k, v = self.qkv(y).chunk(3, dim=-1)
        q = q.view(batch, length, NUM_HEADS, -1).transpose(1, 2)
        k = k.view(batch, length, NUM_HEADS, -1).transpose(1, 2)
        v = v.view(batch, length, NUM_HEADS, -1).transpose(1, 2)
        y = F.scaled_dot_product_attention(q, k, v)
        y = y.transpose(1, 2).contiguous().view(batch, length, D_MODEL)
        x = residual + self.out(y)
        return x + self.down(F.gelu(self.up(self.mixer_norm(x))))


def _place_slots(mask: Tensor, idx: Tensor, vals: Tensor, width: int) -> Tensor:
    """LSD-first place-indexed digit values for one prompt field.

    Pure index arithmetic on token positions: `place` is the distance from the
    last digit of the field.  Absent (high) places read 0, which is exactly the
    decimal leading-zero padding of the same number.
    """
    zero = torch.zeros_like(idx)
    end = torch.where(mask, idx, zero).max(dim=1, keepdim=True).values
    place = end - idx
    ok = mask & (place >= 0) & (place < width)
    tgt = torch.where(ok, place, torch.full_like(place, width))
    buf = torch.zeros(
        idx.shape[0], width + 1, dtype=torch.long, device=idx.device
    )
    buf.scatter_(1, tgt, vals * ok.long())
    return buf[:, :width]


def _slots(input_ids: Tensor, attention_mask: Tensor, places: int):
    """Re-lay `[N] d(N) [X] d(x) [T] d(T)` into canonical LSD-first slots."""
    batch, length = input_ids.shape
    marker = (
        (input_ids == TOK_N) | (input_ids == TOK_X) | (input_ids == TOK_T)
    )
    field = (marker.cumsum(1) - 1).clamp(min=0)
    is_digit = (input_ids >= DIGIT_OFFSET) & attention_mask
    idx = torch.arange(length, device=input_ids.device).unsqueeze(0).expand(
        batch, length
    )
    vals = (input_ids - DIGIT_OFFSET).clamp(min=0)
    n_slots = _place_slots(is_digit & (field == 0), idx, vals, places)
    x_slots = _place_slots(is_digit & (field == 1), idx, vals, places)
    t_slots = _place_slots(is_digit & (field == 2), idx, vals, T_SLOTS)
    return n_slots, x_slots, t_slots


def _kl(pred_logits: Tensor, target_logits: Tensor) -> Tensor:
    """KL(target || pred); 0 exactly when the two agree."""
    tgt = F.softmax(target_logits.float(), dim=-1)
    log_t = F.log_softmax(target_logits.float(), dim=-1)
    log_p = F.log_softmax(pred_logits.float(), dim=-1)
    return (tgt * (log_t - log_p)).sum(-1).mean()


class Model(nn.Module):
    def __init__(self, spec: ModelSpec) -> None:
        super().__init__()
        self.config = Config(spec.vocab_size, spec.max_seq_len)
        # decimal places of N, from public shape metadata only:
        #   max_seq_len = 3 markers + digits(N) + digits(x) + digits(T)
        # and digits(x) <= digits(N), digits(T) <= 2, so this is an upper bound.
        self.places = max(1, (spec.max_seq_len - 3) // 2)
        self.digit_emb = nn.Embedding(NUM_DIGITS, DIGIT_DIM)
        self.digit_up = (
            nn.Linear(DIGIT_DIM, D_MODEL, bias=False)
            if DIGIT_DIM != D_MODEL
            else nn.Identity()
        )
        self.place_emb = nn.Embedding(max(self.places, T_SLOTS), D_MODEL)
        self.field_emb = nn.Embedding(3, D_MODEL)
        self.blocks = nn.ModuleList(Block() for _ in range(NUM_LAYERS))
        self.final_norm = RMSNorm(D_MODEL)
        self.dhead = nn.Linear(D_MODEL, NUM_DIGITS)
        self._calls = 0

    # -- embedding helpers -------------------------------------------------
    def _emb_ids(self, slots: Tensor) -> Tensor:
        return self.digit_up(self.digit_emb(slots))

    def _emb_probs(self, probs: Tensor) -> Tensor:
        return self.digit_up(probs @ self.digit_emb.weight)

    def _reembed(self, logits: Tensor) -> Tensor:
        """Send a digit-logit readout back through the digit bottleneck."""
        probs = F.softmax(logits.float(), dim=-1).to(self.digit_emb.weight.dtype)
        if STRAIGHT_THROUGH:
            hard = F.one_hot(probs.argmax(-1), NUM_DIGITS).to(probs.dtype)
            probs = hard + probs - probs.detach()
        return self._emb_probs(probs)

    def _drop(self, op: Tensor) -> Tensor:
        if OP_DROPOUT <= 0.0 or not self.training:
            return op
        keep = torch.rand(
            op.shape[0], op.shape[1], 1, device=op.device
        ) >= OP_DROPOUT
        return op * keep.to(op.dtype)

    def _t_const(self, batch: int, value: int, device) -> Tensor:
        digits = [(value // (10 ** k)) % 10 for k in range(T_SLOTS)]
        ids = torch.tensor(digits, device=device, dtype=torch.long)
        return self._emb_ids(ids.unsqueeze(0).expand(batch, T_SLOTS))

    # -- the learned map ---------------------------------------------------
    def _core(self, n_e: Tensor, op_e: Tensor, t_e: Tensor) -> Tensor:
        places = op_e.shape[1]
        pl = self.place_emb.weight
        fe = self.field_emb.weight
        h = torch.cat(
            [
                n_e + pl[: n_e.shape[1]] + fe[0],
                op_e + pl[:places] + fe[1],
                t_e + pl[:T_SLOTS] + fe[2],
            ],
            dim=1,
        )
        for block in self.blocks:
            h = block(h)
        head = h[:, n_e.shape[1] : n_e.shape[1] + places]
        return self.dhead(self.final_norm(head))

    def _scatter(
        self, dlog: Tensor, input_ids: Tensor, attention_mask: Tensor
    ) -> Tensor:
        batch, length = input_ids.shape
        places = dlog.shape[1]
        lens = attention_mask.sum(1)
        j = torch.arange(places, device=dlog.device).unsqueeze(0)
        pos = (lens - 1).unsqueeze(1) - j
        pos = torch.where(pos >= 0, pos, torch.full_like(pos, length))
        specials = torch.full(
            (batch, places, DIGIT_OFFSET),
            _NEG,
            dtype=dlog.dtype,
            device=dlog.device,
        )
        src = torch.cat([specials, dlog], dim=-1)
        out = torch.zeros(
            batch,
            length + 1,
            self.config.vocab_size,
            dtype=dlog.dtype,
            device=dlog.device,
        )
        out.scatter_(
            1, pos.unsqueeze(-1).expand(-1, -1, self.config.vocab_size), src
        )
        return out[:, :length]

    # -- composition-law auxiliary ----------------------------------------
    def _closure(self, n_e: Tensor, x_e: Tensor, x_slots: Tensor) -> Tensor:
        batch = n_e.shape[0]
        device = n_e.device
        places = x_e.shape[1]
        t1 = self._t_const(batch, 1, device)
        t2 = self._t_const(batch, 2, device)
        want_rand = LAM_RAND > 0.0 or DIAG_EVERY > 0

        ops = [self._drop(x_e), self._drop(x_e)]
        ts = [t1, t2]
        if want_rand:
            if RAND_MODE == "permute":
                # operands manufactured from the batch: each decimal place is
                # taken from a different, independently shuffled row, so the
                # result is a digit string with the batch's own per-place digit
                # statistics that lies on no row's trajectory.
                perm = torch.argsort(
                    torch.rand(batch, places, device=device), dim=0
                )
                rand_ids = torch.gather(x_slots, 0, perm)
            else:
                rand_ids = torch.randint(
                    0, NUM_DIGITS, (batch, places), device=device
                )
            rand_e = self._emb_ids(rand_ids)
            ops += [rand_e, rand_e]
            ts += [t1, t2]
        n_rep = n_e.repeat(len(ops), 1, 1)
        first = self._core(
            n_rep, torch.cat(ops, 0), torch.cat(ts, 0)
        ).chunk(len(ops), 0)
        a1, a2 = first[0], first[1]

        second_ops = [self._drop(self._reembed(a1))]
        if want_rand:
            second_ops.append(self._reembed(first[2]))
        n_rep2 = n_e.repeat(len(second_ops), 1, 1)
        second = self._core(
            n_rep2,
            torch.cat(second_ops, 0),
            t1.repeat(len(second_ops), 1, 1),
        ).chunk(len(second_ops), 0)
        b2 = second[0]

        total = n_e.new_zeros(())
        kl_c = _kl(b2, a2.detach())
        if SYMMETRIC:
            kl_c = 0.5 * (kl_c + _kl(a2, b2.detach()))
        if LAM_COMPOSE > 0.0:
            total = total + LAM_COMPOSE * kl_c
        kl_r = n_e.new_zeros(())
        if want_rand:
            kl_r = _kl(second[1], first[3].detach())
            if SYMMETRIC:
                kl_r = 0.5 * (kl_r + _kl(first[3], second[1].detach()))
            if LAM_RAND > 0.0:
                total = total + LAM_RAND * kl_r
        if LAM_IDENT > 0.0:
            t0 = self._t_const(batch, 0, device)
            a0 = self._core(n_e, x_e, t0)
            total = total + LAM_IDENT * F.cross_entropy(
                a0.reshape(-1, NUM_DIGITS).float(), x_slots.reshape(-1)
            )

        if DIAG_EVERY > 0 and self._calls % DIAG_EVERY == 0:
            with torch.no_grad():
                r1, r2 = first[2].float(), first[3].float()
                probs = F.softmax(r1, -1)
                ent = -(probs * probs.clamp_min(1e-9).log()).sum(-1).mean()
                pred = r1.argmax(-1)
                idm = (pred == rand_ids).float().mean()
                agr = (pred == r2.argmax(-1)).float().mean()
                counts = F.one_hot(pred, NUM_DIGITS).float().mean(0)
                mode = counts.max(-1).values.mean()
                # identity-collapse on the *batch's own* operands: how often the
                # one-squaring readout simply reproduces the operand it was
                # given.  Compares a model output to a model input; no label is
                # involved.
                idx_rate = (a1.float().argmax(-1) == x_slots).float().mean()
                print(
                    "CLOSURE_DIAG call={} kl_c={:.4f} kl_r={:.4f} "
                    "ent={:.4f} idm={:.4f} agr={:.4f} mode={:.4f} "
                    "idx={:.4f}".format(
                        self._calls,
                        float(kl_c),
                        float(kl_r),
                        float(ent),
                        float(idm),
                        float(agr),
                        float(mode),
                        float(idx_rate),
                    ),
                    flush=True,
                )
        return total

    # -- evaluator entry point --------------------------------------------
    def forward(
        self,
        input_ids: Tensor,
        attention_mask: Tensor | None = None,
    ) -> tuple[Tensor, Tensor | None]:
        if attention_mask is None:
            attention_mask = input_ids != 0
        n_slots, x_slots, t_slots = _slots(input_ids, attention_mask, self.places)
        n_e = self._emb_ids(n_slots)
        x_e = self._emb_ids(x_slots)
        t_e = self._emb_ids(t_slots)
        main = self._core(n_e, self._drop(x_e), t_e)
        logits = self._scatter(main, input_ids, attention_mask)
        if not self.training:
            return logits, None
        self._calls += 1
        aux = None
        if LAM_COMPOSE > 0.0 or LAM_RAND > 0.0 or LAM_IDENT > 0.0 or DIAG_EVERY > 0:
            aux = self._closure(n_e, x_e, x_slots)
        return logits, aux


def build_model(spec: ModelSpec) -> Model:
    if spec.vocab_size != DIGIT_OFFSET + NUM_DIGITS:
        raise ValueError("this submission assumes the public 17-token vocabulary")
    model = Model(spec)
    assert_model_state(model, spec)
    return model


def build_optimizer(model: nn.Module, spec: OptimizerSpec) -> OptimizerBundle:
    decay, no_decay = [], []
    for parameter in model.parameters():
        (decay if parameter.ndim >= 2 else no_decay).append(parameter)
    return OptimizerBundle(
        torch.optim.AdamW(
            [
                {"params": decay, "weight_decay": WD},
                {"params": no_decay, "weight_decay": 0.0},
            ],
            lr=LR,
            betas=(0.9, 0.95),
            capturable=spec.device_type == "cuda",
        )
    )


def training_loss(logits: Tensor, labels: Tensor, auxiliary) -> Tensor:
    loss = F.cross_entropy(logits.float(), labels)
    if auxiliary is None:
        return loss
    return loss + auxiliary.float()


SUBMISSION = Submission(
    build_model=build_model,
    build_optimizer=build_optimizer,
    training_loss=training_loss,
    batch_size=_BATCH_SIZE,
    max_steps=_MAX_STEPS,
)
