"""group-rotation submission (generated by lab/make_gr.py).

config: mixer=std rot=0 gbp=0 fhead=1 tcond=1 tie=1
        D=128 heads=4 loops=8 K=128 harm=1
        lr=0.001 wd=0.1 batch=512
"""

from __future__ import annotations

import math

import torch
import torch.nn.functional as F
from torch import Tensor, nn

from benchmark import (
    ModelSpec,
    OptimizerBundle,
    OptimizerSpec,
    Submission,
    assert_model_state,
)

D_MODEL = 128
NUM_HEADS = 4
NUM_LOOPS = 8
FF_MULT = 4
MIXER = "std"
USE_ROT = 0
USE_GBP = 0
FHEAD = 1
USE_TCOND = 1
TIE_HEAD = 1
N_FREQ = 128
N_HARM = 1
_LR = 0.001
_WD = 0.1
_BATCH = 512
_MAX_STEPS = None


class Config:
    def __init__(self, vocab_size: int, max_seq_len: int) -> None:
        self.vocab_size = vocab_size
        self.max_seq_len = max_seq_len


class RMSNorm(nn.Module):
    def __init__(self, width: int) -> None:
        super().__init__()
        self.weight = nn.Parameter(torch.ones(width))

    def forward(self, x: Tensor) -> Tensor:
        return F.rms_norm(x, (x.shape[-1],), self.weight)


def _cmul(a: Tensor, b: Tensor) -> Tensor:
    """Elementwise complex product on a trailing (..., 2) real/imag axis."""
    ar, ai = a[..., 0], a[..., 1]
    br, bi = b[..., 0], b[..., 1]
    return torch.stack((ar * br - ai * bi, ar * bi + ai * br), dim=-1)


class Block(nn.Module):
    """Transformer block; the channel mixer and an optional complex-rotation
    sublayer are the hypothesis knobs."""

    def __init__(self) -> None:
        super().__init__()
        self.attention_norm = RMSNorm(D_MODEL)
        self.qkv = nn.Linear(D_MODEL, 3 * D_MODEL)
        self.out = nn.Linear(D_MODEL, D_MODEL)
        self.mixer_norm = RMSNorm(D_MODEL)
        hid = FF_MULT * D_MODEL
        self.up = nn.Linear(D_MODEL, hid if MIXER == "std" else 2 * hid)
        self.down = nn.Linear(hid, D_MODEL)
        if USE_ROT:
            self.rot_norm = RMSNorm(D_MODEL)
            self.rot_z = nn.Linear(D_MODEL, D_MODEL)
            self.rot_w = nn.Linear(D_MODEL, D_MODEL)
            self.rot_o = nn.Linear(D_MODEL, D_MODEL)

    def _mix(self, x: Tensor) -> Tensor:
        h = self.up(x)
        if MIXER == "std":
            return self.down(F.gelu(h))
        a, b = h.chunk(2, dim=-1)
        if MIXER == "geglu":
            return self.down(F.gelu(a) * b)
        return self.down(a * b)  # bilinear limit: pure product of two projections

    def _rotate(self, x: Tensor) -> Tensor:
        """Complex latent: the block acts by a learned *rotation*, so composing
        blocks composes angles (the group-representation bet)."""
        h = self.rot_norm(x)
        shape = h.shape[:-1] + (D_MODEL // 2, 2)
        z = self.rot_z(h).view(shape)
        w = self.rot_w(h).view(shape)
        w = w / w.norm(dim=-1, keepdim=True).clamp_min(1e-4)  # unit modulus
        return self.rot_o(_cmul(z, w).reshape(h.shape))

    def forward(self, x: Tensor, mask: Tensor | None) -> Tensor:
        residual = x
        h = self.attention_norm(x)
        batch, length, _ = h.shape
        q, k, v = self.qkv(h).chunk(3, dim=-1)
        q = q.view(batch, length, NUM_HEADS, -1).transpose(1, 2)
        k = k.view(batch, length, NUM_HEADS, -1).transpose(1, 2)
        v = v.view(batch, length, NUM_HEADS, -1).transpose(1, 2)
        x = residual + self.out(
            F.scaled_dot_product_attention(q, k, v, attn_mask=mask)
            .transpose(1, 2)
            .contiguous()
            .view(batch, length, D_MODEL)
        )
        if USE_ROT:
            x = x + self._rotate(x)
        return x + self._mix(self.mixer_norm(x))


class Model(nn.Module):
    def __init__(self, spec: ModelSpec) -> None:
        super().__init__()
        self.config = Config(spec.vocab_size, spec.max_seq_len)
        self.token_embedding = nn.Embedding(spec.vocab_size, D_MODEL)
        self.position_embedding = nn.Embedding(spec.max_seq_len, D_MODEL)
        self.block = Block()
        self.final_norm = RMSNorm(D_MODEL)
        if USE_GBP:
            # (sum_i U e_i) * (sum_j V e_j) = sum_ij (U e_i)(V e_j): every
            # ordered pair of prompt tokens, i.e. an outer-product feature map.
            self.gbp_u = nn.Linear(D_MODEL, D_MODEL)
            self.gbp_v = nn.Linear(D_MODEL, D_MODEL)
            self.gbp_norm = RMSNorm(D_MODEL)
            self.gbp_o = nn.Linear(D_MODEL, D_MODEL)
        if FHEAD:
            self.theta = nn.Linear(D_MODEL, N_FREQ)
            self.fout = nn.Linear(2 * N_HARM * N_FREQ, spec.vocab_size, bias=False)
            nn.init.zeros_(self.fout.weight)
        if USE_TCOND:
            # learned attention pool -> learned per-frequency angle multiplier.
            self.t_query = nn.Parameter(torch.zeros(D_MODEL))
            self.t_mlp = nn.Sequential(
                nn.Linear(D_MODEL, 4 * N_FREQ), nn.GELU(), nn.Linear(4 * N_FREQ, N_FREQ)
            )
            nn.init.zeros_(self.t_mlp[-1].weight)
            nn.init.zeros_(self.t_mlp[-1].bias)
        if FHEAD != 2:
            self.head = nn.Linear(D_MODEL, spec.vocab_size, bias=False)
            if TIE_HEAD:
                self.head.weight = self.token_embedding.weight

    def forward(
        self, input_ids: Tensor, attention_mask: Tensor | None = None
    ) -> tuple[Tensor, None]:
        batch, length = input_ids.shape
        positions = torch.arange(length, device=input_ids.device)
        x = self.token_embedding(input_ids) + self.position_embedding(positions)

        mask = None
        keep = None
        if attention_mask is not None:
            if attention_mask.dim() == 2:
                keep = attention_mask.to(torch.bool)
                mask = keep[:, None, None, :]
            else:
                mask = attention_mask.to(torch.bool)[:, None, :, :]
                keep = mask.any(dim=1).any(dim=1)
        if keep is None:
            keep = torch.ones(batch, length, dtype=torch.bool, device=x.device)
        fkeep = keep.to(x.dtype)[..., None]

        if USE_GBP:
            u = (self.gbp_u(x) * fkeep).sum(dim=1)
            v = (self.gbp_v(x) * fkeep).sum(dim=1)
            x = x + self.gbp_o(self.gbp_norm(u * v))[:, None, :]

        for _ in range(NUM_LOOPS):
            x = self.block(x, mask)
        h = self.final_norm(x)

        if not FHEAD:
            return self.head(h), None

        # --- phase-sensitive readout, computed in fp32 (bf16 phases are useless) ---
        with torch.autocast(device_type=x.device.type, enabled=False):
            hf = h.float()
            theta = self.theta(hf)
            if USE_TCOND:
                score = (hf @ self.t_query.float()).masked_fill(~keep, -1e30)
                pooled = (F.softmax(score, dim=-1)[..., None] * hf).sum(dim=1)
                theta = theta * (1.0 + self.t_mlp(pooled))[:, None, :]
            feats = []
            for harmonic in range(1, N_HARM + 1):
                ang = theta * float(harmonic)
                feats.append(torch.cos(ang))
                feats.append(torch.sin(ang))
            logits = self.fout(torch.cat(feats, dim=-1))
        if FHEAD == 1:
            logits = logits + self.head(h).float()
        return logits, None


def build_model(spec: ModelSpec) -> Model:
    model = Model(spec)
    assert_model_state(model, spec)
    return model


def build_optimizer(model: nn.Module, spec: OptimizerSpec) -> OptimizerBundle:
    decay, no_decay = [], []
    for name, param in model.named_parameters():
        (no_decay if param.ndim < 2 else decay).append(param)
    return OptimizerBundle(
        torch.optim.AdamW(
            [
                {"params": decay, "weight_decay": _WD},
                {"params": no_decay, "weight_decay": 0.0},
            ],
            lr=_LR,
            betas=(0.9, 0.95),
            capturable=spec.device_type == "cuda",
        )
    )


SUBMISSION = Submission(
    build_model=build_model,
    build_optimizer=build_optimizer,
    batch_size=_BATCH,
    max_steps=_MAX_STEPS,
)
