#!/usr/bin/env python
"""Generate `GRPair` submissions: an explicit outer-product (pairwise) phase map.

Motivation (public generator source + elementary number theory only):

  A place-valued decimal string is a sum,  x = sum_i 10^i d_i, so
      x^2 = sum_{i,j} 10^(i+j) d_i d_j .
  If a value is carried by phases -- feature = (cos w v, sin w v) -- then the
  phase of x^2 is a *sum over ordered pairs of prompt slots* of a term that
  depends only on (slot_i, slot_j, digit_i, digit_j).  So a learned table
  indexed by (position-pair, token-pair), summed and read out through cos/sin,
  can represent the squaring map exactly, and -- crucially -- reduction mod N is
  free, because a phase is periodic.

  This differs from the pooled-product model in one important way: the network
  never has to *search for a frequency*.  Every quantity it learns is an angle,
  so there is no rugged continuous-scale optimisation between it and the group
  solution.  If the Fourier route is learnable at all, it should be learnable
  here.

Nothing is hard-coded: the table is randomly initialised and trained; no
modulus, phi, discrete log, or modular exponentiation appears in the forward
pass, and no Python control flow reads `input_ids`.

Usage:
  python lab/make_grpair.py --name gp_rev --posmode rev --freqs 128
"""

from __future__ import annotations

import argparse
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

TEMPLATE = '''"""GRPair submission (generated by lab/make_grpair.py).

config: pos={posmode} K={freqs} H={harm} tcond={tcond} order={order}
        lr={lr} wd={wd} embstd={embstd} batch={batch}
"""

from __future__ import annotations

import torch
import torch.nn.functional as F
from torch import Tensor, nn

from benchmark import (
    ModelSpec,
    OptimizerBundle,
    OptimizerSpec,
    Submission,
    assert_model_state,
)

N_FREQ = {freqs}
N_HARM = {harm}
POS_MODE = "{posmode}"
USE_TCOND = {tcond}
ORDER = {order}
EMB_STD = {embstd}
_LR = {lr}
_WD = {wd}
_BATCH = {batch}
_MAX_STEPS = {steps}


class Config:
    def __init__(self, vocab_size: int, max_seq_len: int) -> None:
        self.vocab_size = vocab_size
        self.max_seq_len = max_seq_len


class PairPhase(nn.Module):
    """theta = sum over slot pairs of a learned angle indexed by
    (slot_i, slot_j, token_i, token_j).  ORDER=1 restricts to the diagonal
    (a purely additive/linear phase map) -- the control for "is the
    multiplicative interaction what matters?"."""

    def __init__(self, max_seq_len: int, vocab_size: int, n_freq: int, reverse: bool) -> None:
        super().__init__()
        self.reverse = reverse
        self.vocab_size = vocab_size
        self.max_seq_len = max_seq_len
        if ORDER == 2:
            pairs = [
                (i, j) for i in range(max_seq_len) for j in range(i, max_seq_len)
            ]
        else:
            pairs = [(i, i) for i in range(max_seq_len)]
        self.n_pairs = len(pairs)
        left = torch.tensor([p[0] for p in pairs], dtype=torch.long)
        right = torch.tensor([p[1] for p in pairs], dtype=torch.long)
        base = torch.arange(self.n_pairs, dtype=torch.long) * vocab_size * vocab_size
        # non-persistent: index bookkeeping, excluded from the state budget
        self.register_buffer("left", left, persistent=False)
        self.register_buffer("right", right, persistent=False)
        self.register_buffer("base", base, persistent=False)
        self.table = nn.Embedding(self.n_pairs * vocab_size * vocab_size, n_freq)
        nn.init.normal_(self.table.weight, std=EMB_STD)

    def forward(self, input_ids: Tensor, keep: Tensor) -> Tensor:
        batch, length = input_ids.shape
        device = input_ids.device
        if self.reverse:
            lengths = keep.sum(dim=1, keepdim=True)
            slots = torch.arange(self.max_seq_len, device=device)[None, :]
            src = (lengths - 1 - slots).clamp(0, length - 1)
            tokens = input_ids.gather(1, src)
            present = (slots < lengths) & (slots >= 0)
        else:
            pad = self.max_seq_len - length
            tokens = F.pad(input_ids, (0, pad)) if pad > 0 else input_ids[:, : self.max_seq_len]
            present = F.pad(keep, (0, pad)) if pad > 0 else keep[:, : self.max_seq_len]
        ti = tokens[:, self.left]
        tj = tokens[:, self.right]
        valid = (present[:, self.left] & present[:, self.right]).float()
        idx = self.base[None, :] + ti * self.vocab_size + tj
        return (self.table(idx) * valid[..., None]).sum(dim=1)


class Model(nn.Module):
    def __init__(self, spec: ModelSpec) -> None:
        super().__init__()
        self.config = Config(spec.vocab_size, spec.max_seq_len)
        V, L = spec.vocab_size, spec.max_seq_len
        self.vocab_size = V
        self.max_seq_len = L
        modes = ["rev", "abs"] if POS_MODE == "both" else [POS_MODE]
        self.phase = nn.ModuleList(
            PairPhase(L, V, N_FREQ, reverse=(m == "rev")) for m in modes
        )
        n_feat = 2 * N_HARM * N_FREQ
        self.readout = nn.Parameter(torch.randn(L, n_feat, V) * (n_feat**-0.5))
        self.readout_bias = nn.Parameter(torch.zeros(L, V))
        if USE_TCOND:
            # A learned per-frequency angle *multiplier*: theta -> theta * m.
            # In a representation where a group element is carried by phase this
            # is exponentiation, i.e. any power of the element at constant depth.
            # m is produced by a learned pooled read of the prompt.
            self.t_table = nn.Embedding(L * V, 4 * N_FREQ)
            nn.init.normal_(self.t_table.weight, std=EMB_STD)
            self.t_mlp = nn.Sequential(
                nn.GELU(), nn.Linear(4 * N_FREQ, N_FREQ)
            )
            nn.init.zeros_(self.t_mlp[-1].weight)
            nn.init.zeros_(self.t_mlp[-1].bias)

    def forward(
        self, input_ids: Tensor, attention_mask: Tensor | None = None
    ) -> tuple[Tensor, None]:
        batch, length = input_ids.shape
        device = input_ids.device
        if attention_mask is None:
            keep = torch.ones(batch, length, dtype=torch.bool, device=device)
        elif attention_mask.dim() == 2:
            keep = attention_mask.to(torch.bool)
        else:
            keep = attention_mask.to(torch.bool).any(dim=1)

        with torch.autocast(device_type=device.type, enabled=False):
            theta = self.phase[0](input_ids, keep)
            for extra in self.phase[1:]:
                theta = theta + extra(input_ids, keep)
            if USE_TCOND:
                positions = torch.arange(length, device=device).clamp(
                    max=self.max_seq_len - 1
                )
                t_idx = positions[None, :] * self.vocab_size + input_ids
                pooled = (self.t_table(t_idx) * keep.float()[..., None]).sum(dim=1)
                theta = theta * (1.0 + self.t_mlp(pooled))
            parts = []
            for harmonic in range(1, N_HARM + 1):
                ang = theta * float(harmonic)
                parts.append(torch.cos(ang))
                parts.append(torch.sin(ang))
            feats = torch.cat(parts, dim=-1)
            out = torch.einsum("bf,rfv->brv", feats, self.readout) + self.readout_bias
            lengths = keep.sum(dim=1, keepdim=True)
            positions = torch.arange(length, device=device)[None, :]
            rev = (lengths - 1 - positions).clamp(0, self.max_seq_len - 1)
            logits = out.gather(1, rev[..., None].expand(batch, length, self.vocab_size))
        return logits.contiguous(), None


def build_model(spec: ModelSpec) -> Model:
    model = Model(spec)
    assert_model_state(model, spec)
    return model


def build_optimizer(model: nn.Module, spec: OptimizerSpec) -> OptimizerBundle:
    decay, no_decay = [], []
    for _, param in model.named_parameters():
        (no_decay if param.ndim < 2 else decay).append(param)
    return OptimizerBundle(
        torch.optim.AdamW(
            [
                {{"params": decay, "weight_decay": _WD}},
                {{"params": no_decay, "weight_decay": 0.0}},
            ],
            lr=_LR,
            betas=(0.9, 0.95),
            capturable=spec.device_type == "cuda",
        )
    )


SUBMISSION = Submission(
    build_model=build_model,
    build_optimizer=build_optimizer,
    batch_size=_BATCH,
    max_steps=_MAX_STEPS,
)
'''


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", required=True)
    ap.add_argument("--freqs", type=int, default=128)
    ap.add_argument("--harm", type=int, default=1)
    ap.add_argument("--posmode", default="rev", choices=("abs", "rev", "both"))
    ap.add_argument("--order", type=int, default=2, choices=(1, 2))
    ap.add_argument("--tcond", type=int, default=0, choices=(0, 1))
    ap.add_argument("--embstd", type=float, default=0.5)
    ap.add_argument("--lr", type=float, default=1e-2)
    ap.add_argument("--wd", type=float, default=0.1)
    ap.add_argument("--batch", type=int, default=512)
    ap.add_argument("--steps", default="None")
    ap.add_argument("--outdir", default="submissions/group-rotation")
    args = ap.parse_args()

    source = TEMPLATE.format(
        freqs=args.freqs,
        harm=args.harm,
        posmode=args.posmode,
        order=args.order,
        tcond=args.tcond,
        embstd=args.embstd,
        lr=args.lr,
        wd=args.wd,
        batch=args.batch,
        steps=args.steps,
    )
    out = REPO / args.outdir / args.name / "submission.py"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(source)
    print(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
