#!/usr/bin/env python
"""Emit `submissions/hard-digitalu-hf1/submission.py` -- `DigitALU` at
Hard-faithful scale with every correction this project earned applied at once.

  parser (MarkerPointer, `explore/digit-carry`, verified 1.000 at T=16/32/64)
    -> DigitALU x k   -- tree:quotient graph (`explore/alu-depth`)
    -> counted-halting depth controller (`explore/depth-controller`, MAX_T=64)

DIFFERENCES FROM `submissions/depth-controller`, and why each one is here:

  * **tree:quotient instead of serial.**  The reduction was 80-86% of the
    sequential depth and 10 of its 11 tied conditional subtractions are no-ops.
    `alu-depth` replaced them with a balanced product tree plus one learned
    quotient digit and one subtraction: same hypothesis class, same discrete
    alphabet, constructed ceiling 1.000 soft AND argmax-hard, and at these
    slot counts **129 sequential soft steps instead of 1,537** (S=7).
  * **untied.**  `alu-credit` measured that weight ties help *repair* near a
    solution and HURT learning from random init (the one seed that succeeds
    untied fails when tied, `local_ce` 0.0050 -> 0.1187).  Two different
    problems; the ties are not carried across.
  * **small embedding init.**  `nn.Embedding`'s default `N(0,1)` put the hosted
    Hard run's step-1 loss at 79.936 instead of `ln 17 = 2.833`.  This model's
    head is not tied to the embedding, so the toll is smaller here than for the
    baseline, but the init is fixed anyway -- it is free.
  * **a chosen batch size** -- the evaluator's DataLoader has no
    `persistent_workers`, so batch size is a free throughput knob.

Everything is learned from random init.  No modular-exponentiation routine, no
digit-multiplication rule, no carry rule, no lookup of answers, no `torch.load`.
The construction used in the lab to certify the ceiling appears nowhere here.

Usage:  python lab/make_dalu.py --loops 16 --batch-size 128 --max-steps 800
"""

from __future__ import annotations

import argparse
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

TEMPLATE = '''"""hard-digitalu-hf1: marker-relative parser + tree:quotient DigitALU +
counted-halting depth controller.  Every tensor learned from random init.

See lab/reports/hard-digitalu-hf1.md.  Generated by lab/make_dalu.py with
LOOPS={train_loops} EVAL_LOOPS={eval_loops} MAXQ={max_quot} batch={batch_size}.
"""

from __future__ import annotations

import torch
import torch.nn.functional as F
from torch import Tensor, nn

from benchmark import (
    ModelSpec,
    OptimizerBundle,
    OptimizerSpec,
    Submission,
    assert_model_state,
)

D_MODEL = 32
EMB_INIT = 0.02           # the hosted run's step-1 loss was 79.936, not ln 17
N_CARRY = 2
N_BORROW = 2
MAX_QUOT = {max_quot}     # alphabet of the learned quotient digit
TRAIN_LOOPS_EASY = 3
TRAIN_LOOPS_DEEP = {train_loops}
EVAL_LOOPS = {eval_loops}
DIGIT_TAU = 0.5
IDENTITY_INIT = 5.0
CONS_W = 0.1
CONS_J = 8
CONS_LOOPS = 4
SEL_EPS = 1e-6
SEL_THRESH_EASY = -3.0
SEL_THRESH_DEEP = 0.0
LR = {lr}
SEL_LR = 1e-1
WD = 0.0
O_LO = -2
NEG = -1e4
_MAX_STEPS = {max_steps}
_BATCH_SIZE = {batch_size}
_EVAL_BATCH_SIZE = {eval_batch_size}


class Config:
    def __init__(self, vocab_size: int, max_seq_len: int) -> None:
        self.vocab_size = vocab_size
        self.max_seq_len = max_seq_len


class MarkerPointer(nn.Module):
    """Learned differentiable field-relative pointer (explore/digit-carry).
    A digit's place value is its offset from the end of ITS OWN field, so each
    slot learns which marker terminates its field and how far before it to
    read.  `G` scores cumulative anchor mass -- the differentiable form of a
    field's opening boundary."""

    def __init__(self, d_model: int, n_slot: int, o_hi: int) -> None:
        super().__init__()
        self.o_hi = o_hi
        self.n_off = o_hi - O_LO + 1
        self.probe = nn.Linear(d_model, 3, bias=False)
        self.R = nn.Parameter(torch.randn(n_slot, 4, self.n_off) * 0.5)
        self.G = nn.Parameter(torch.randn(n_slot, 4) * 0.5)

    def forward(self, emb: Tensor, mask: Tensor) -> Tensor:
        b, L, _ = emb.shape
        sc = self.probe(emb).transpose(1, 2)
        sc = sc.masked_fill(~mask[:, None, :], NEG)
        a = F.softmax(sc, dim=-1)
        idx = mask.long().sum(-1) - 1
        a = torch.cat([a, F.one_hot(idx, L).to(a.dtype)[:, None]], dim=1)
        rels = []
        for o in range(O_LO, self.o_hi + 1):
            if o >= 0:
                rels.append(F.pad(a[:, :, o:], (0, o)))
            else:
                rels.append(F.pad(a[:, :, : L + o], (-o, 0)))
        rel = torch.stack(rels, dim=-1)
        logit = (torch.einsum("balo,sao->bsl", rel, self.R)
                 + torch.einsum("bal,sa->bsl", a.cumsum(-1), self.G))
        logit = logit.masked_fill(~mask[:, None, :], NEG)
        return torch.einsum("bsl,bld->bsd", F.softmax(logit, dim=-1), emb)


class DigitALU(nn.Module):
    """One squaring step on digit slots, tree:quotient shape.

    A balanced tree sums the S^2 partial products into the full 2S-digit
    product; a long division over the places of that product then removes one
    learned quotient digit times N at each place.  All MAX_QUOT+2 candidate
    subtractions run in ONE scan batched over the multiple index; the final
    borrow state of candidate m is the learned comparison bit, and a learned
    scorer over the adjacent pair picks the largest non-borrowing m.

    The multiples {{m*N}} are built from digits(N) with the SAME learned Tadd,
    so they cost zero new parameters and assert no arithmetic.

    Every learned tensor is indexed by a digit or by a small carry/borrow
    state.  Nothing is indexed by the residue, which is what makes the
    parameter count independent of the modulus -- mandatory on a modulus-split
    dataset where the test moduli never appear in training."""

    def __init__(self, slots: int) -> None:
        super().__init__()
        self.S = slots
        self.W = slots + 1
        self.Ca, self.Cb = N_CARRY, N_BORROW
        self.needed = list(range(MAX_QUOT + 2))
        self.Tmul = nn.Parameter(torch.randn(10, 10, 20) * 0.5)
        self.Tadd = nn.Parameter(torch.randn(10, 10, N_CARRY, 10 + N_CARRY) * 0.5)
        self.Tsub = nn.Parameter(torch.randn(10, 10, N_BORROW, 10 + N_BORROW) * 0.5)
        self.zero = nn.Parameter(torch.randn(10) * 0.5)
        self.carry0 = nn.Parameter(torch.randn(N_CARRY) * 0.5)
        self.borrow0 = nn.Parameter(torch.randn(N_BORROW) * 0.5)
        self.sel = nn.Linear(2 * N_BORROW, 1)
        self.copy_scale = nn.Parameter(torch.tensor(IDENTITY_INIT))
        self.hard = False

    def _sm(self, logits: Tensor) -> Tensor:
        p = F.softmax(logits, -1)
        if self.hard:
            h = F.one_hot(p.argmax(-1), p.shape[-1]).to(p.dtype)
            p = h + p - p.detach()
        return p

    def add_scan(self, r: Tensor, addend: Tensor) -> Tensor:
        """r, addend: (n, Wd, 10) -> (n, Wd, 10), LSB->MSB slot scan."""
        c = self._sm(self.carry0).to(r.dtype).expand(r.shape[0], self.Ca)
        outs = []
        for m in range(r.shape[1]):
            o = torch.einsum("bu,bv,bc,uvco->bo", r[:, m], addend[:, m], c,
                             self.Tadd.to(r.dtype))
            outs.append(self._sm(o[:, :10] + self.copy_scale * r[:, m]))
            c = self._sm(o[:, 10:] + self.copy_scale * c)
        return torch.stack(outs, 1)

    def tree_sum(self, regs: list[Tensor]) -> Tensor:
        while len(regs) > 1:
            carry = [regs[-1]] if len(regs) % 2 else []
            pairs = [(regs[i], regs[i + 1]) for i in range(0, len(regs) - 1, 2)]
            n = regs[0].shape[0]
            out = self.add_scan(torch.cat([a for a, _ in pairs], 0),
                                torch.cat([c for _, c in pairs], 0))
            regs = [out[i * n:(i + 1) * n] for i in range(len(pairs))] + carry
        return regs[0]

    def multiples(self, ndig: Tensor) -> Tensor:
        """(b, W, 10) -> (b, M, W, 10).  m*N = a*N + b*N with a + b = m, so a
        balanced schedule needs ceil(log2 max_m) chained add_scans, paid once
        per forward.  Same learned Tadd, no new parameter."""
        b = ndig.shape[0]
        z = self._sm(self.zero).to(ndig.dtype)
        have = {{0: z.view(1, 1, 10).expand(b, self.W, 10),
                1: ndig}}
        target = set(self.needed)
        while not target <= set(have):
            newly = []
            for t in sorted(target - set(have)):
                cand = [a for a in have if a <= t - a and (t - a) in have]
                if cand:
                    newly.append((t, max(cand), t - max(cand)))
            if not newly:
                mx = max(have)
                newly = [(2 * mx, mx, mx)]
            A = torch.cat([have[a] for _, a, _ in newly], 0)
            B = torch.cat([have[bb] for _, _, bb in newly], 0)
            out = self.add_scan(A, B)
            for i, (t, _, _) in enumerate(newly):
                have[t] = out[i * b:(i + 1) * b]
        return torch.stack([have[m] for m in self.needed], 1)

    def quot_reduce(self, r: Tensor, Tm: Tensor) -> Tensor:
        """One learned quotient digit + one subtraction, all candidates in one
        scan.  `Tm` is the multiples-contracted Tsub, cached per forward: the
        subtrahend digits do not depend on the register, so contracting them
        into the table once is an algebraically identical reassociation."""
        b, M = r.shape[0], Tm.shape[1]
        c = self._sm(self.borrow0).to(r.dtype).expand(b, M, self.Cb)
        outs = []
        for m in range(self.W):
            rw = r[:, m]
            o = torch.einsum("bu,bmc,bmuco->bmo", rw, c, Tm[:, :, m])
            outs.append(self._sm(o[..., :10] + self.copy_scale * rw[:, None]))
            c = self._sm(o[..., 10:] + self.copy_scale * c)
        t = torch.stack(outs, 2)                       # (b, M, W, 10)
        pair = torch.cat([c[:, :-1], c[:, 1:]], dim=-1)
        w = self._sm(self.sel(pair).squeeze(-1))       # (b, M-1)
        return torch.einsum("bm,bmwo->bwo", w, t[:, :-1])

    def forward(self, s: Tensor, ndig: Tensor) -> Tensor:
        b, S, W = s.shape[0], self.S, self.W
        F2 = 2 * S
        z = self._sm(self.zero).to(s.dtype).expand(b, 10)
        mults = self.multiples(ndig)
        Tm = torch.einsum("bmwv,uvco->bmwuco", mults, self.Tsub.to(s.dtype))
        prod = {{}}
        for i in range(S):
            for j in range(S):
                o = torch.einsum("bu,bv,uvo->bo", s[:, i], s[:, j],
                                 self.Tmul.to(s.dtype))
                prod[(i, j)] = (self._sm(o[:, :10]), self._sm(o[:, 10:]))
        buckets: dict[int, list] = {{}}
        for (i, j), lh in prod.items():
            buckets.setdefault(i + j, []).append(lh)
        leaves = []
        for par in (0, 1):
            offs = [k for k in sorted(buckets) if k % 2 == par]
            if not offs:
                continue
            for t in range(max(len(buckets[k]) for k in offs)):
                cols = [z] * F2
                for k in offs:
                    if t < len(buckets[k]):
                        cols[k], cols[k + 1] = buckets[k][t]
                leaves.append(torch.stack(cols, 1))
        Pr = self.tree_sum(leaves)
        r = z[:, None].expand(b, W, 10)
        for t in range(F2 - 1, -1, -1):
            r = torch.cat([Pr[:, t:t + 1], r[:, : W - 1]], dim=1)
            if t <= S:
                r = self.quot_reduce(r, Tm)
        return torch.log(r[:, :S] + 1e-9)


def _one_hot_st(r: Tensor) -> Tensor:
    h = F.one_hot(r.argmax(-1), r.shape[-1]).to(r.dtype)
    return h + r - r.detach()


class Model(nn.Module):
    def __init__(self, spec: ModelSpec) -> None:
        super().__init__()
        self.config = Config(spec.vocab_size, spec.max_seq_len)
        self.vocab = spec.vocab_size
        self.S = max(3, (spec.max_seq_len - 4) // 2)
        self.W = self.S + 1
        self.n_t = 2
        self.train_loops = TRAIN_LOOPS_DEEP
        self.emb = nn.Embedding(spec.vocab_size, D_MODEL)
        nn.init.normal_(self.emb.weight, std=EMB_INIT)
        self.ptr = MarkerPointer(D_MODEL, self.S + self.W + self.n_t,
                                 o_hi=max(9, self.W + 1))
        self.digit = nn.Linear(D_MODEL, 10)
        self.alu = DigitALU(self.S)
        self.sel_one = nn.Parameter(torch.randn(10) * 0.5)
        self.sel_gain = nn.Parameter(torch.tensor(2.0))
        self.sel_thresh = nn.Parameter(torch.tensor(SEL_THRESH_DEEP))
        self.head = nn.Linear(10, spec.vocab_size)

    def _shift_reg(self, c: Tensor, table: Tensor, state0: Tensor,
                   n_state: int) -> Tensor:
        alu = self.alu
        one = alu._sm(self.sel_one).to(c.dtype)
        zer = alu._sm(alu.zero).to(c.dtype)
        opnd = torch.stack([one] + [zer] * (self.n_t - 1), 0)[None].expand(
            c.shape[0], self.n_t, 10)
        st = alu._sm(state0).to(c.dtype).expand(c.shape[0], n_state)
        outs = []
        for m in range(self.n_t):
            o = torch.einsum("bu,bv,bc,uvco->bo", c[:, m], opnd[:, m], st,
                             table.to(c.dtype))
            outs.append(alu._sm(o[:, :10]))
            st = alu._sm(o[:, 10:])
        return _one_hot_st(torch.stack(outs, 1))

    def decrement(self, c: Tensor) -> Tensor:
        return self._shift_reg(c, self.alu.Tsub, self.alu.borrow0, self.alu.Cb)

    def increment(self, c: Tensor) -> Tensor:
        return self._shift_reg(c, self.alu.Tadd, self.alu.carry0, self.alu.Ca)

    def is_zero(self, c: Tensor) -> Tensor:
        z = self.alu._sm(self.alu.zero).to(c.dtype)
        ms = torch.einsum("btd,d->bt", c, z).clamp_min(0.0)
        s = torch.log(ms.float() + SEL_EPS).mean(-1, keepdim=True)
        return torch.sigmoid(self.sel_gain.float()
                             * (s - self.sel_thresh.float())).to(c.dtype)

    def halting(self, c: Tensor, loops: int) -> Tensor:
        rest = self.is_zero(c).new_ones(c.shape[0], 1)
        ws = []
        for _ in range(loops):
            c = self.decrement(c)
            p = self.is_zero(c)
            ws.append(rest * p)
            rest = rest * (1 - p)
        return torch.cat(ws, dim=-1)

    def consistency(self, c: Tensor) -> Tensor:
        r = c[:1]
        w = self.halting(r, CONS_LOOPS)
        tot = w.new_zeros(())
        for _ in range(CONS_J):
            r = self.increment(r)
            w_next = self.halting(r, CONS_LOOPS)
            tgt = torch.cat([torch.zeros_like(w[:, :1]), w[:, :-1]], dim=1)
            tot = tot + ((w_next - tgt.detach()) ** 2).sum(-1).mean()
            w = w_next
        return tot / CONS_J

    def forward(self, input_ids: Tensor, attention_mask: Tensor | None = None):
        b, L = input_ids.shape
        if attention_mask is None:
            mask = torch.ones(b, L, dtype=torch.bool, device=input_ids.device)
        else:
            mask = attention_mask.to(torch.bool)
            if mask.dim() == 3:
                mask = mask[:, 0]
        e = self.emb(input_ids)
        slots = self.ptr(e, mask)
        dg = F.softmax(self.digit(slots) / DIGIT_TAU, dim=-1)
        sx = dg[:, : self.S]
        sn = dg[:, self.S: self.S + self.W]
        st = dg[:, self.S + self.W:]

        if self.training:
            self.alu.hard = False
            loops = self.train_loops
        else:
            self.alu.hard = False
            loops = EVAL_LOOPS

        state, c = sx, st[:, : self.n_t]
        rest = self.is_zero(c).new_ones(b, 1)
        acc = None
        best_w = None
        best_out = None
        for k in range(loops):
            out = self.alu(state, sn)
            state = F.softmax(out, dim=-1)
            c = self.decrement(c)
            p = self.is_zero(c)
            w = (rest * p).to(out.dtype)
            rest = rest * (1 - p)
            if self.training:
                acc = w[:, :, None] * out if acc is None else acc + w[:, :, None] * out
            else:
                if best_w is None:
                    best_w, best_out = w, out
                else:
                    take = (w > best_w).to(out.dtype)
                    best_w = torch.maximum(best_w, w)
                    best_out = take[:, :, None] * out + (1 - take[:, :, None]) * best_out
                if (k & 3) == 3 and float(
                        (rest.to(best_w.dtype) - best_w).max()) <= 0.0:
                    break
        mixed = acc if self.training else best_out

        vals = self.head(mixed)
        logits = input_ids.new_zeros(b, L, self.vocab, dtype=vals.dtype)
        last = mask.long().sum(-1) - 1
        for p_i in range(self.S):
            pos = (last - p_i).clamp(min=0)
            logits.scatter_(1, pos[:, None, None].expand(-1, 1, self.vocab),
                            vals[:, p_i][:, None, :])
        aux = self.consistency(st[:, : self.n_t]) if self.training else None
        return logits, aux


def build_model(spec: ModelSpec) -> Model:
    model = Model(spec)
    assert_model_state(model, spec)
    return model


def training_loss(logits: Tensor, labels: Tensor, aux) -> Tensor:
    loss = F.cross_entropy(logits.float(), labels)
    if aux is not None:
        loss = loss + CONS_W * aux.float()
    return loss


def build_optimizer(model: nn.Module, spec: OptimizerSpec) -> OptimizerBundle:
    easy = spec.training_time_seconds <= 120
    if hasattr(model, "train_loops"):
        model.train_loops = TRAIN_LOOPS_EASY if easy else TRAIN_LOOPS_DEEP
        with torch.no_grad():
            model.sel_thresh.fill_(SEL_THRESH_EASY if easy else SEL_THRESH_DEEP)
    sel = {{id(p) for n, p in model.named_parameters() if n.startswith("sel_")}}
    decay = [p for p in model.parameters() if p.ndim >= 2 and id(p) not in sel]
    no_decay = [p for p in model.parameters() if p.ndim < 2 and id(p) not in sel]
    sel_params = [p for n, p in model.named_parameters() if n.startswith("sel_")]
    return OptimizerBundle(
        torch.optim.AdamW(
            [{{"params": decay, "weight_decay": WD}},
             {{"params": no_decay, "weight_decay": 0.0}},
             {{"params": sel_params, "weight_decay": 0.0, "lr": SEL_LR}}],
            lr=LR, betas=(0.9, 0.95),
            capturable=spec.device_type == "cuda",
        )
    )


SUBMISSION = Submission(
    build_model=build_model,
    build_optimizer=build_optimizer,
    training_loss=training_loss,
    batch_size=_BATCH_SIZE,
    eval_batch_size=_EVAL_BATCH_SIZE,
    max_steps=_MAX_STEPS,
)
'''


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--loops", type=int, default=16)
    ap.add_argument("--eval-loops", type=int, default=64)
    ap.add_argument("--max-quot", type=int, default=10)
    ap.add_argument("--lr", type=float, default=3e-3)
    ap.add_argument("--batch-size", type=int, default=128)
    ap.add_argument("--eval-batch-size", type=int, default=2048)
    ap.add_argument("--max-steps", type=int, default=None)
    ap.add_argument("--out", default="submissions/hard-digitalu-hf1/submission.py")
    args = ap.parse_args()

    code = TEMPLATE.format(
        train_loops=args.loops,
        eval_loops=args.eval_loops,
        max_quot=args.max_quot,
        lr=repr(args.lr),
        batch_size=repr(args.batch_size),
        eval_batch_size=repr(args.eval_batch_size),
        max_steps=repr(args.max_steps),
    )
    path = REPO / args.out
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(code)
    print(path.relative_to(REPO))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
