#!/usr/bin/env python
"""Generate `GRIter` submissions -- the only construction in the group-rotation
family that measurably improved held-out generalisation (lab/probe_iter.py:
0.00 -> 0.24-0.34 exact on held-out x, with perfect T-extrapolation on seen x).

Shape:

  1. a learned attention with S canonical "slot" queries reads the prompt into S
     soft digit distributions -- the model's own working representation of the
     input value;
  2. ONE shared block is applied L times.  The block is a pairwise (outer-product)
     phase map,  theta = sum_{i<=j} Q[i,j] . (s_i (x) s_j),  read out through
     cos/sin -- exactly the structure of  v^2 = sum_ij 10^(i+j) d_i d_j  carried in
     phase, so reduction mod N is free;
  3. between steps the state is decoded back to soft digits and re-encoded.  That
     round trip is what supplies the only training signal that constrains the phase
     to be genuinely periodic mod N;
  4. a learned selector, pooled from the prompt (which contains the T field),
     mixes the L step outputs.  Composition depth is therefore *learned* from the
     prompt rather than set by Python control flow, and the eventual periodicity of
     2^T mod phi can in principle be absorbed by the selector.

Nothing is hard-coded: no modulus, no phi, no discrete log, no modular
exponentiation, no lookup of answers, and no Python control flow reads
`input_ids`.  The digit alphabet, the slot alignment and the step count mixing
are all learned parameters trained from random init.

Usage:
  python lab/make_griter.py --name gi_l4 --loops 4 --slots 4
"""

from __future__ import annotations

import argparse
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

TEMPLATE = '''"""GRIter submission (generated by lab/make_griter.py).

config: slots={slots} loops={loops} K={freqs} H={harm} dattn={dattn}
        temp={temp} lr={lr} wd={wd} batch={batch}
"""

from __future__ import annotations

import torch
import torch.nn.functional as F
from torch import Tensor, nn

from benchmark import (
    ModelSpec,
    OptimizerBundle,
    OptimizerSpec,
    Submission,
    assert_model_state,
)

SLOTS = {slots}
LOOPS = {loops}
N_FREQ = {freqs}
N_HARM = {harm}
D_ATTN = {dattn}
TEMP = {temp}
_LR = {lr}
_WD = {wd}
_BATCH = {batch}
_MAX_STEPS = {steps}


class Config:
    def __init__(self, vocab_size: int, max_seq_len: int) -> None:
        self.vocab_size = vocab_size
        self.max_seq_len = max_seq_len


class SquaringBlock(nn.Module):
    """One shared step: soft digit slots -> pairwise phase -> soft digit slots."""

    def __init__(self, slots: int, n_freq: int, n_harm: int, alphabet: int) -> None:
        super().__init__()
        self.pairs = [(i, j) for i in range(slots) for j in range(i, slots)]
        self.table = nn.Parameter(
            torch.randn(len(self.pairs), alphabet, alphabet, n_freq) * 0.5
        )
        self.n_harm = n_harm
        feat = 2 * n_harm * n_freq
        self.readout = nn.Parameter(torch.randn(slots, feat, alphabet) * feat**-0.5)
        self.bias = nn.Parameter(torch.zeros(slots, alphabet))

    def forward(self, state: Tensor) -> Tensor:
        theta = None
        for n, (i, j) in enumerate(self.pairs):
            term = torch.einsum("ba,bc,acf->bf", state[:, i], state[:, j], self.table[n])
            theta = term if theta is None else theta + term
        parts = []
        for harmonic in range(1, self.n_harm + 1):
            ang = theta * float(harmonic)
            parts.append(torch.cos(ang))
            parts.append(torch.sin(ang))
        feats = torch.cat(parts, dim=-1)
        return torch.einsum("bf,ifa->bia", feats, self.readout) + self.bias


class Model(nn.Module):
    def __init__(self, spec: ModelSpec) -> None:
        super().__init__()
        self.config = Config(spec.vocab_size, spec.max_seq_len)
        V, L = spec.vocab_size, spec.max_seq_len
        self.vocab_size = V
        self.max_seq_len = L
        self.embed = nn.Embedding(L * V, D_ATTN)
        # learned slot queries: where in the prompt each working digit comes from
        self.slot_query = nn.Parameter(torch.randn(SLOTS, D_ATTN) * D_ATTN**-0.5)
        # learned map from the token alphabet to the model's working alphabet
        self.to_alphabet = nn.Parameter(torch.randn(V, V) * V**-0.5)
        self.block = SquaringBlock(SLOTS, N_FREQ, N_HARM, V)
        # learned selector over composition depth, pooled from the prompt
        self.pool_query = nn.Parameter(torch.randn(D_ATTN) * D_ATTN**-0.5)
        self.selector = nn.Sequential(
            nn.Linear(D_ATTN, 4 * D_ATTN), nn.GELU(), nn.Linear(4 * D_ATTN, LOOPS)
        )
        self.slot_bias = nn.Parameter(torch.zeros(L, V))

    def forward(
        self, input_ids: Tensor, attention_mask: Tensor | None = None
    ) -> tuple[Tensor, None]:
        batch, length = input_ids.shape
        device = input_ids.device
        if attention_mask is None:
            keep = torch.ones(batch, length, dtype=torch.bool, device=device)
        elif attention_mask.dim() == 2:
            keep = attention_mask.to(torch.bool)
        else:
            keep = attention_mask.to(torch.bool).any(dim=1)

        positions = torch.arange(length, device=device).clamp(max=self.max_seq_len - 1)
        hidden = self.embed(positions[None, :] * self.vocab_size + input_ids)

        with torch.autocast(device_type=device.type, enabled=False):
            hidden = hidden.float()
            neg = torch.finfo(hidden.dtype).min
            # slot extraction: S learned queries attend over the prompt
            scores = torch.einsum("bld,sd->bsl", hidden, self.slot_query)
            scores = scores.masked_fill(~keep[:, None, :], neg)
            attn = F.softmax(scores, dim=-1)
            tokens = F.one_hot(input_ids, self.vocab_size).float()
            state = torch.einsum("bsl,blv,vw->bsw", attn, tokens, self.to_alphabet)
            state = F.softmax(state, dim=-1)

            outs = []
            for _ in range(LOOPS):
                step = self.block(state)
                outs.append(step)
                state = F.softmax(step / TEMP, dim=-1)
            stacked = torch.stack(outs, dim=1)  # B, LOOPS, SLOTS, V

            pool_scores = (hidden @ self.pool_query).masked_fill(~keep, neg)
            pooled = (F.softmax(pool_scores, dim=-1)[..., None] * hidden).sum(dim=1)
            weights = F.softmax(self.selector(pooled), dim=-1)
            chosen = torch.einsum("bt,btsv->bsv", weights, stacked)

            # answers are tail-aligned: working slot r feeds prompt position
            # (len-1-r), i.e. slot 0 is the least significant answer digit.
            lengths = keep.sum(dim=1, keepdim=True)
            rev = (lengths - 1 - torch.arange(length, device=device)[None, :]).clamp(
                0, self.max_seq_len - 1
            )
            padded = F.pad(chosen, (0, 0, 0, max(0, self.max_seq_len - SLOTS)))
            logits = padded.gather(
                1, rev.clamp(max=padded.shape[1] - 1)[..., None].expand(
                    batch, length, self.vocab_size
                )
            )
            logits = logits + self.slot_bias[rev]
        return logits.contiguous(), None


def build_model(spec: ModelSpec) -> Model:
    model = Model(spec)
    assert_model_state(model, spec)
    return model


def build_optimizer(model: nn.Module, spec: OptimizerSpec) -> OptimizerBundle:
    decay, no_decay = [], []
    for _, param in model.named_parameters():
        (no_decay if param.ndim < 2 else decay).append(param)
    return OptimizerBundle(
        torch.optim.AdamW(
            [
                {{"params": decay, "weight_decay": _WD}},
                {{"params": no_decay, "weight_decay": 0.0}},
            ],
            lr=_LR,
            betas=(0.9, 0.95),
            capturable=spec.device_type == "cuda",
        )
    )


SUBMISSION = Submission(
    build_model=build_model,
    build_optimizer=build_optimizer,
    batch_size=_BATCH,
    max_steps=_MAX_STEPS,
)
'''


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", required=True)
    ap.add_argument("--slots", type=int, default=4)
    ap.add_argument("--loops", type=int, default=4)
    ap.add_argument("--freqs", type=int, default=32)
    ap.add_argument("--harm", type=int, default=8)
    ap.add_argument("--dattn", type=int, default=128)
    ap.add_argument("--temp", type=float, default=1.0)
    ap.add_argument("--lr", type=float, default=3e-3)
    ap.add_argument("--wd", type=float, default=0.1)
    ap.add_argument("--batch", type=int, default=512)
    ap.add_argument("--steps", default="None")
    ap.add_argument("--outdir", default="submissions/group-rotation")
    args = ap.parse_args()

    source = TEMPLATE.format(
        slots=args.slots,
        loops=args.loops,
        freqs=args.freqs,
        harm=args.harm,
        dattn=args.dattn,
        temp=args.temp,
        lr=args.lr,
        wd=args.wd,
        batch=args.batch,
        steps=args.steps,
    )
    out = REPO / args.outdir / args.name / "submission.py"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(source)
    print(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
