#!/usr/bin/env python
"""Generate `GRNet` submissions -- the minimal architecture in which a
group/Fourier solution to modular squaring is *exactly representable*.

Why this shape (all of it derived from the public generator source + elementary
number theory, none of it hard-coded):

  * A value v is carried by additive-character features  cos(w_k v), sin(w_k v).
    Reduction mod N is then FREE: the characters are periodic, so the network
    never has to learn a division.
  * A place-valued decimal string is a *sum*: x = sum_i 10^i d_i.  A pooled
    per-(position, token) embedding is exactly that sum, so the encoder is
    compositional and generalises to unseen x by construction.
  * Squaring is a *product*: x^2 = (sum_i 10^i d_i)(sum_j 10^j d_j).  An explicit
    product of two learned pools realises every cross term at once -- this is the
    bilinear / outer-product feature map, taken to its limit.
  * Digits of the answer are tail-aligned, so the readout is indexed by distance
    from the end of the prompt.

Nothing here implements modular arithmetic: `to_theta`, the pools and the
readout are all learned parameters trained from random init.  There is no
control flow that reads `input_ids`.

Usage:
  python lab/make_grnet.py --name gn_quad --quad 1
"""

from __future__ import annotations

import argparse
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

TEMPLATE = '''"""GRNet submission (generated by lab/make_grnet.py).

config: quad={quad} pos={posmode} W={width} K={freqs} H={harm} tcond={tcond}
        revhead={revhead} attn={attn} lr={lr} wd={wd} batch={batch}
"""

from __future__ import annotations

import torch
import torch.nn.functional as F
from torch import Tensor, nn

from benchmark import (
    ModelSpec,
    OptimizerBundle,
    OptimizerSpec,
    Submission,
    assert_model_state,
)

WIDTH = {width}
N_FREQ = {freqs}
N_HARM = {harm}
USE_QUAD = {quad}
POS_MODE = "{posmode}"
USE_TCOND = {tcond}
REV_HEAD = {revhead}
ATTN_LOOPS = {attn}
D_ATTN = {dattn}
_LR = {lr}
_WD = {wd}
_BATCH = {batch}
_MAX_STEPS = {steps}


class Config:
    def __init__(self, vocab_size: int, max_seq_len: int) -> None:
        self.vocab_size = vocab_size
        self.max_seq_len = max_seq_len


class RMSNorm(nn.Module):
    def __init__(self, width: int) -> None:
        super().__init__()
        self.weight = nn.Parameter(torch.ones(width))

    def forward(self, x: Tensor) -> Tensor:
        return F.rms_norm(x, (x.shape[-1],), self.weight)


class PosTokenPool(nn.Module):
    """sum_p  E[pos_p, tok_p]  -- the exact shape of a place-valued decimal sum.

    Indexing the table by (position, token) rather than adding a position
    embedding to a token embedding is what makes a *product* of position and
    digit (i.e. 10^i * d_i) representable at all.
    """

    def __init__(self, max_seq_len: int, vocab_size: int, width: int, n_out: int) -> None:
        super().__init__()
        self.vocab_size = vocab_size
        self.max_seq_len = max_seq_len
        tables = 2 if POS_MODE == "both" else 1
        self.tables = nn.ModuleList(
            nn.Embedding(max_seq_len * vocab_size, width * n_out) for _ in range(tables)
        )
        for table in self.tables:
            nn.init.normal_(table.weight, std={embstd})
        self.n_out = n_out
        self.width = width

    def forward(self, abs_idx: Tensor, rev_idx: Tensor, fkeep: Tensor) -> Tensor:
        idxs = []
        if POS_MODE in ("abs", "both"):
            idxs.append(abs_idx)
        if POS_MODE in ("rev", "both"):
            idxs.append(rev_idx)
        total = None
        for table, idx in zip(self.tables, idxs):
            term = (table(idx) * fkeep).sum(dim=1)
            total = term if total is None else total + term
        return total.view(-1, self.n_out, self.width)


class AttnStack(nn.Module):
    """Optional small bidirectional attention stack, used only to let the model
    resolve where the x-field and T-field are when the prompt length varies."""

    def __init__(self, max_seq_len: int, vocab_size: int) -> None:
        super().__init__()
        self.embed = nn.Embedding(max_seq_len * vocab_size, D_ATTN)
        self.norm1 = RMSNorm(D_ATTN)
        self.qkv = nn.Linear(D_ATTN, 3 * D_ATTN)
        self.proj = nn.Linear(D_ATTN, D_ATTN)
        self.norm2 = RMSNorm(D_ATTN)
        self.up = nn.Linear(D_ATTN, 4 * D_ATTN)
        self.down = nn.Linear(4 * D_ATTN, D_ATTN)

    def forward(self, abs_idx: Tensor, mask: Tensor) -> Tensor:
        x = self.embed(abs_idx)
        for _ in range(ATTN_LOOPS):
            h = self.norm1(x)
            batch, length, _ = h.shape
            q, k, v = self.qkv(h).chunk(3, dim=-1)
            q = q.view(batch, length, 4, -1).transpose(1, 2)
            k = k.view(batch, length, 4, -1).transpose(1, 2)
            v = v.view(batch, length, 4, -1).transpose(1, 2)
            a = F.scaled_dot_product_attention(q, k, v, attn_mask=mask)
            x = x + self.proj(a.transpose(1, 2).contiguous().view(batch, length, D_ATTN))
            x = x + self.down(F.gelu(self.up(self.norm2(x))))
        return x


class Model(nn.Module):
    def __init__(self, spec: ModelSpec) -> None:
        super().__init__()
        self.config = Config(spec.vocab_size, spec.max_seq_len)
        V, L = spec.vocab_size, spec.max_seq_len
        self.vocab_size = V
        self.max_seq_len = L
        n_pool = 2 if USE_QUAD else 1
        self.pool = PosTokenPool(L, V, WIDTH, n_pool)
        feat_in = WIDTH * (2 if USE_QUAD else 1)
        self.to_theta = nn.Linear(feat_in, N_FREQ)
        # A learned per-frequency log-scale.  The useful frequencies span orders
        # of magnitude (a phase must wrap over the whole value range), which an
        # additive optimizer reaches very slowly through a plain linear weight.
        self.theta_scale = nn.Parameter(torch.zeros(N_FREQ))
        n_feat = 2 * N_HARM * N_FREQ
        rows = L if REV_HEAD else 1
        self.readout = nn.Parameter(torch.randn(rows, n_feat, V) * (n_feat ** -0.5))
        self.readout_bias = nn.Parameter(torch.zeros(rows, V))
        if ATTN_LOOPS:
            self.attn = AttnStack(L, V)
            self.attn_theta = nn.Linear(D_ATTN, N_FREQ)
            nn.init.zeros_(self.attn_theta.weight)
            nn.init.zeros_(self.attn_theta.bias)
            self.attn_head = nn.Linear(D_ATTN, V)
            nn.init.zeros_(self.attn_head.weight)
            nn.init.zeros_(self.attn_head.bias)
        if USE_TCOND:
            # A learned per-frequency angle multiplier, read from the prompt by a
            # learned pooled embedding.  theta -> theta * m turns the state's
            # phase into the phase of a learned power of the group element, which
            # is what makes *any* T reachable at constant depth.
            self.t_pool = PosTokenPool(L, V, WIDTH, 1)
            self.t_mlp = nn.Sequential(
                nn.Linear(WIDTH, 4 * WIDTH), nn.GELU(), nn.Linear(4 * WIDTH, N_FREQ)
            )
            nn.init.zeros_(self.t_mlp[-1].weight)
            nn.init.zeros_(self.t_mlp[-1].bias)

    def forward(
        self, input_ids: Tensor, attention_mask: Tensor | None = None
    ) -> tuple[Tensor, None]:
        batch, length = input_ids.shape
        device = input_ids.device
        if attention_mask is None:
            keep = torch.ones(batch, length, dtype=torch.bool, device=device)
            mask = None
        elif attention_mask.dim() == 2:
            keep = attention_mask.to(torch.bool)
            mask = keep[:, None, None, :]
        else:
            mask = attention_mask.to(torch.bool)[:, None, :, :]
            keep = mask.any(dim=1).any(dim=1)

        positions = torch.arange(length, device=device)
        lengths = keep.sum(dim=1, keepdim=True)
        rev = (lengths - 1 - positions[None, :]).clamp_(0, self.max_seq_len - 1)
        abs_idx = positions[None, :].clamp(max=self.max_seq_len - 1) * self.vocab_size
        abs_idx = abs_idx + input_ids
        rev_idx = rev * self.vocab_size + input_ids

        with torch.autocast(device_type=device.type, enabled=False):
            fkeep = keep.float()[..., None]
            pooled = self.pool(abs_idx, rev_idx, fkeep)  # B, n_pool, WIDTH
            if USE_QUAD:
                u, v = pooled[:, 0], pooled[:, 1]
                feats_in = torch.cat((u * v, u), dim=-1)
            else:
                feats_in = pooled[:, 0]
            theta = self.to_theta(feats_in) * torch.exp(self.theta_scale)  # B, K
            if USE_TCOND:
                t = self.t_pool(abs_idx, rev_idx, fkeep)[:, 0]
                theta = theta * (1.0 + self.t_mlp(t))
            parts = []
            for harmonic in range(1, N_HARM + 1):
                ang = theta * float(harmonic)
                parts.append(torch.cos(ang))
                parts.append(torch.sin(ang))
            feats = torch.cat(parts, dim=-1)  # B, 2*H*K
            if REV_HEAD:
                out = torch.einsum("bf,rfv->brv", feats, self.readout) + self.readout_bias
                gather = rev[..., None].expand(batch, length, self.vocab_size)
                logits = out.gather(1, gather)
            else:
                logits = (feats @ self.readout[0] + self.readout_bias[0])[:, None, :]
                logits = logits.expand(batch, length, self.vocab_size)
            logits = logits.contiguous()
        if ATTN_LOOPS:
            hidden = self.attn(abs_idx, mask)
            logits = logits + self.attn_head(hidden).float()
        return logits, None


def build_model(spec: ModelSpec) -> Model:
    model = Model(spec)
    assert_model_state(model, spec)
    return model


def build_optimizer(model: nn.Module, spec: OptimizerSpec) -> OptimizerBundle:
    decay, no_decay = [], []
    for _, param in model.named_parameters():
        (no_decay if param.ndim < 2 else decay).append(param)
    return OptimizerBundle(
        torch.optim.AdamW(
            [
                {{"params": decay, "weight_decay": _WD}},
                {{"params": no_decay, "weight_decay": 0.0}},
            ],
            lr=_LR,
            betas=(0.9, 0.95),
            capturable=spec.device_type == "cuda",
        )
    )


SUBMISSION = Submission(
    build_model=build_model,
    build_optimizer=build_optimizer,
    batch_size=_BATCH,
    max_steps=_MAX_STEPS,
)
'''


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", required=True)
    ap.add_argument("--width", type=int, default=256)
    ap.add_argument("--freqs", type=int, default=256)
    ap.add_argument("--harm", type=int, default=1)
    ap.add_argument("--quad", type=int, default=1, choices=(0, 1))
    ap.add_argument("--posmode", default="both", choices=("abs", "rev", "both"))
    ap.add_argument("--tcond", type=int, default=0, choices=(0, 1))
    ap.add_argument("--revhead", type=int, default=1, choices=(0, 1))
    ap.add_argument("--attn", type=int, default=0, help="attention loops (0 disables)")
    ap.add_argument("--dattn", type=int, default=128)
    ap.add_argument("--embstd", type=float, default=0.2)
    ap.add_argument("--lr", type=float, default=1e-3)
    ap.add_argument("--wd", type=float, default=0.1)
    ap.add_argument("--batch", type=int, default=512)
    ap.add_argument("--steps", default="None")
    ap.add_argument("--outdir", default="submissions/group-rotation")
    args = ap.parse_args()

    source = TEMPLATE.format(
        width=args.width,
        freqs=args.freqs,
        harm=args.harm,
        quad=args.quad,
        posmode=args.posmode,
        tcond=args.tcond,
        revhead=args.revhead,
        attn=args.attn,
        dattn=args.dattn,
        embstd=args.embstd,
        lr=args.lr,
        wd=args.wd,
        batch=args.batch,
        steps=args.steps,
    )
    out = REPO / args.outdir / args.name / "submission.py"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(source)
    print(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
