#!/usr/bin/env python
"""LAB ONLY -- the ADD-ONLY transducer as a differentiable model with a
POPULATION of independent replicas (the `alu-population` instrument).

HYPOTHESIS.  `alu-relational` proved `Tmul`'s ~200 cells unidentifiable from
anything legal.  So delete `Tmul` from the hypothesis class rather than try to
identify it: accumulate `x^2` from the digits of `x` over a chain of multiples
of `x` generated by the LEARNED adder.  Every learned arithmetic tensor is then
an adder cell (or, under `--tie-sub`, an adder cell read backwards).

The reduction, the place-value shifts and the tree summation are `alu-depth`'s
verified `tree:quotient` schedule, unchanged.  The ONLY difference from
`probe_pop.PopALU` is that the S^2 `Tmul` digit products are replaced by S
full-width multiples of `x` drawn from the adder chain.

VARIANTS (see lab/reports/hard-add-only.md section 2 for the compliance ruling)
  --pick learned  PRIMARY / conservative.  A learned 10x10 table maps the input
                  digit to a chain element.  The architecture asserts only that
                  the leaf at place i is SOME element of the chain generated by
                  repeatedly applying the learned binary op to x -- the same
                  assertion `DigitALU.multiples()` already makes about N.
  --pick fixed    BORDERLINE.  The digit one-hot indexes the chain directly,
                  i.e. `d*x = x added d times` is asserted by the architecture.

COMPLIANCE.  `--construct` (sets tables to truth) and `--tf` (teacher forcing
off a constructed tape) are LAB DIAGNOSTICS and can never be a submission
(rules 2, 7).  `--tf 0` with `--construct` absent is the LEGAL objective.
Self-generated operands only; nothing under data/generated/ is opened.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import sys
import time

import torch
import torch.nn.functional as F
from torch import nn

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from probe_addsearch import (  # noqa: E402
    add_depth, digits_le, sample_semiprime,
)

BIG = 30.0


class PopAddALU(nn.Module):
    """Add-only tree:quotient transducer with a leading replica dimension."""

    def __init__(self, P: int, slots: int, n_carry: int = 2, n_borrow: int = 2,
                 max_quot: int = 10, tau: float = 1.0, hard: bool = False,
                 tie: bool = False, tie_sub: bool = False,
                 init_scale: float = 0.5, pick: str = "learned"):
        super().__init__()
        self.P, self.S = P, slots
        self.W = slots + 1
        self.Fw = 2 * slots
        self.Ca, self.Cb = n_carry, n_borrow
        self.Q = max_quot
        self.tau, self.hard = tau, hard
        self.tie, self.tie_sub = tie, tie_sub
        self.pick_mode = pick
        self.needed = list(range(max_quot + 2))
        self.xneeded = list(range(10))
        sc = torch.full((P,), float(init_scale))
        self.register_buffer("init_scale", sc, persistent=False)

        def rp(*shape):
            t = torch.randn(P, *shape)
            return nn.Parameter(t * sc.view(P, *([1] * len(shape))))

        self.Tadd = rp(10, 10, n_carry, 10 + n_carry)
        self.Tsub = rp(10, 10, n_borrow, 10 + n_borrow)
        self.Tpick = rp(10, 10)
        self.zero = rp(10)
        self.carry0 = rp(n_carry)
        self.borrow0 = rp(n_borrow)
        self.sel_w = rp(2 * n_borrow)
        self.sel_b = nn.Parameter(torch.zeros(P))
        self.copy_scale = nn.Parameter(torch.zeros(P))
        self.alpha = nn.Parameter(torch.zeros(P))
        self.sel_tau = 1.0
        self.sel_hard = False
        self.mode = None            # None | 'record' | 'force'
        self.tape: list = []
        self.tpos = 0
        self.tf_loss = None
        self.tf_n = 0
        self.tf_p = 1.0

    def replica_params(self):
        ps = [self.Tadd, self.Tsub, self.zero, self.carry0, self.borrow0,
              self.sel_w, self.sel_b, self.copy_scale]
        if self.pick_mode == "learned":
            ps.append(self.Tpick)
        return ps

    # ---- ties (reparameterisation only; no value is supplied) ----
    @property
    def Tadd_eff(self):
        return 0.5 * (self.Tadd + self.Tadd.transpose(1, 2)) if self.tie \
            else self.Tadd

    @property
    def Tsub_eff(self):
        if not self.tie_sub:
            return self.Tsub
        dig = self.Tadd_eff[..., :10].permute(0, 4, 2, 3, 1)   # (P,w,v,c,u)
        return torch.cat([dig, self.Tsub[..., 10:]], -1)

    # ---------------- construction (LAB DIAGNOSTIC ONLY) ----------------
    @torch.no_grad()
    def construct(self):
        t = torch.full((10, 10, self.Ca, 10 + self.Ca), -BIG)
        for u in range(10):
            for v in range(10):
                for c in range(2):
                    s = u + v + c
                    t[u, v, c, s % 10] = BIG
                    t[u, v, c, 10 + s // 10] = BIG
        self.Tadd.copy_(t.to(self.Tadd).expand_as(self.Tadd))
        t = torch.full((10, 10, self.Cb, 10 + self.Cb), -BIG)
        for u in range(10):
            for v in range(10):
                for c in range(2):
                    s = u - v - c
                    t[u, v, c, s % 10] = BIG
                    t[u, v, c, 10 + (1 if s < 0 else 0)] = BIG
        self.Tsub.copy_(t.to(self.Tsub).expand_as(self.Tsub))
        t = torch.full((10, 10), -BIG)
        for d in range(10):
            t[d, d] = BIG
        self.Tpick.copy_(t.to(self.Tpick).expand_as(self.Tpick))
        for P_, n in ((self.zero, 10), (self.carry0, self.Ca),
                      (self.borrow0, self.Cb)):
            v = torch.full((n,), -BIG)
            v[0] = BIG
            P_.copy_(v.to(P_).expand_as(P_))
        w = torch.zeros(2 * self.Cb)
        w[0], w[1] = BIG / 2, -BIG / 2
        w[self.Cb + 0], w[self.Cb + 1] = -BIG / 2, BIG / 2
        self.sel_w.copy_(w.to(self.sel_w).expand_as(self.sel_w))
        self.sel_b.zero_()
        self.copy_scale.zero_()

    # ---------------- machinery ----------------
    def _sm(self, logits):
        p = F.softmax(logits / self.tau, -1)
        if self.hard:
            h = F.one_hot(p.argmax(-1), p.shape[-1]).to(p.dtype)
            p = h + p - p.detach()
        return p

    def _tap(self, x):
        if self.mode == 'record':
            self.tape.append(x.detach())
            return x
        if self.mode == 'force':
            truth = self.tape[self.tpos]
            self.tpos += 1
            tgt = truth.argmax(-1)
            lg = x.clamp_min(1e-9).log()
            ce = F.cross_entropy(lg.reshape(-1, 10),
                                 tgt.expand(x.shape[0], *tgt.shape[1:])
                                    .reshape(-1), reduction="none")
            self.tf_loss = self.tf_loss + ce.view(x.shape[0], -1).mean(1)
            self.tf_n += 1
            if self.tf_p >= 1.0:
                return truth.expand_as(x)
            m = torch.rand(x.shape[0], x.shape[1],
                           *([1] * (x.dim() - 2)), device=x.device) < self.tf_p
            return torch.where(m, truth.expand_as(x), x)
        return x

    def add_scan(self, r, addend):
        """r, addend: (P, n, W, 10) -> (P, n, W, 10)."""
        P, n = r.shape[0], r.shape[1]
        cs = self.copy_scale.view(P, 1, 1)
        c = self._sm(self.carry0)[:, None].expand(P, n, self.Ca)
        outs = []
        Ta = self.Tadd_eff
        for m in range(r.shape[2]):
            o = torch.einsum("pnu,pnv,pnc,puvco->pno",
                             r[:, :, m], addend[:, :, m], c, Ta)
            outs.append(self._sm(o[..., :10] + cs * r[:, :, m]))
            c = self._sm(o[..., 10:] + cs * c)
        return self._tap(torch.stack(outs, 2))

    def tree_sum(self, regs):
        while len(regs) > 1:
            carry = [regs[-1]] if len(regs) % 2 else []
            pairs = [(regs[i], regs[i + 1]) for i in range(0, len(regs) - 1, 2)]
            n = regs[0].shape[1]
            out = self.add_scan(torch.cat([a for a, _ in pairs], 1),
                                torch.cat([c for _, c in pairs], 1))
            regs = [out[:, i * n:(i + 1) * n] for i in range(len(pairs))] + carry
        return regs[0]

    def _chain(self, zero_reg, one_reg, needed):
        """{m * one_reg} by repeated LEARNED addition -- DigitALU.multiples()."""
        have = {0: zero_reg, 1: one_reg}
        target = set(needed)
        while not target <= set(have):
            newly = []
            for t in sorted(target - set(have)):
                cand = [a for a in have if a <= t - a and (t - a) in have]
                if cand:
                    newly.append((t, max(cand), t - max(cand)))
            if not newly:
                mx = max(have)
                newly = [(2 * mx, mx, mx)]
            A = torch.cat([have[a] for _, a, _ in newly], 1)
            B = torch.cat([have[b] for _, _, b in newly], 1)
            out = self.add_scan(A, B)
            k = A.shape[1] // len(newly)
            for i, (t, _, _) in enumerate(newly):
                have[t] = out[:, i * k:(i + 1) * k]
        return have

    def multiples(self, ndig):
        """{m*N} from digits(N) with the learned Tadd.  (P,M,W,10)"""
        P, W = self.P, self.W
        z = self._sm(self.zero)
        zr = z[:, None, None, :].expand(P, 1, W, 10)
        one = ndig[None, None].expand(P, 1, W, 10)
        have = self._chain(zr, one, self.needed)
        return torch.cat([have[m] for m in self.needed], 1)

    def x_multiples(self, s):
        """{m*x} for m = 0..9, per example.  s (P,b,S,10) -> (P,b,10,W,10)"""
        P, b, S, W = self.P, s.shape[1], self.S, self.W
        z = self._sm(self.zero)[:, None].expand(P, b, 10)
        zr = z[:, :, None].expand(P, b, W, 10)
        xr = torch.cat([s, z[:, :, None].expand(P, b, W - S, 10)], 2)
        have = self._chain(zr, xr, self.xneeded)
        return torch.stack([have[m] for m in self.xneeded], 2)

    def quot_reduce(self, r, mults):
        P, b, M = r.shape[0], r.shape[1], mults.shape[1]
        W = self.W
        Tm = self._Tm                                # (P,M,W,10,Cb,10+Cb)
        cs = self.copy_scale.view(P, 1, 1, 1)
        c = self._sm(self.borrow0)[:, None, None].expand(P, b, M, self.Cb)
        outs = []
        for m in range(W):
            rw = r[:, :, m]                          # (P,b,10)
            o = torch.einsum("pbu,pbmc,pmuco->pbmo", rw, c, Tm[:, :, m])
            outs.append(self._sm(o[..., :10] + cs * rw[:, :, None]))
            c = self._sm(o[..., 10:] + cs * c)
        t = self._tap(torch.stack(outs, 3))          # (P,b,M,W,10)
        pair = torch.cat([c[:, :, :-1], c[:, :, 1:]], dim=-1)
        w = self._sm(torch.einsum("pbmk,pk->pbm", pair, self.sel_w)
                     + self.sel_b[:, None, None])
        self.last_q = w
        return self._tap(torch.einsum("pbm,pbmwo->pbwo", w, t[:, :, :-1]))

    def forward(self, s, ndig):
        """s: (b, S, 10).  ndig: (W, 10).  -> log-probs (P, b, S, 10)."""
        P, S, W, Fw = self.P, self.S, self.W, self.Fw
        b = s.shape[0]
        self.tpos = 0
        z = self._sm(self.zero)[:, None].expand(P, b, 10)
        mults = self.multiples(ndig)
        self._Tm = torch.einsum("pmwv,puvco->pmwuco", mults, self.Tsub_eff)
        se = s[None].expand(P, b, S, 10)
        Xm = self.x_multiples(se)                       # (P,b,10,W,10)
        if self.pick_mode == "learned":
            pk = self._sm(self.Tpick)                   # (P,10,10) [digit,chain]
        leaves = []
        for i in range(S):
            si = se[:, :, i]                            # (P,b,10)
            w = si if self.pick_mode == "fixed" else \
                torch.einsum("pbu,pum->pbm", si, pk)
            v = torch.einsum("pbm,pbmwo->pbwo", w, Xm)  # (P,b,W,10)
            cols = [z] * Fw
            for j in range(W):
                if i + j < Fw:
                    cols[i + j] = v[:, :, j]
            leaves.append(torch.stack(cols, 2))
        Pr = self.tree_sum(leaves)                      # (P,b,Fw,10)
        r = z[:, :, None].expand(P, b, W, 10)
        for t in range(Fw - 1, -1, -1):
            r = torch.cat([Pr[:, :, t:t + 1], r[:, :, :W - 1]], dim=2)
            if t <= S:
                r = self.quot_reduce(r, mults)
        return torch.log(r[:, :, :S] + 1e-9)

    def mix_probs(self, logits):
        w = F.softmax(self.alpha / self.sel_tau, 0)
        if self.sel_hard:
            h = F.one_hot(w.argmax(0), w.shape[0]).to(w.dtype)
            w = h + w - w.detach()
        return torch.einsum("p,pbso->bso", w, logits.exp())

    def depth(self):
        """Chained soft steps on the critical path, in `DigitALU.depth()`'s
        convention so the two are directly comparable.  `main` is the x -> y
        path; `prefix` is the N-only multiples tree (shared across examples)."""
        return add_depth(self.S, self.W, self.Fw, self.needed, self.xneeded)


# ---------------------------------------------------------------- diagnostics
@torch.no_grad()
def struct_scores(model, p, ndigits):
    out = {}
    for nm, T, cols in (("add_shift", model.Tadd_eff[p], range(10)),
                        ("sub_shift", model.Tsub_eff[p], sorted(set(ndigits)))):
        k = n = 0
        for v in cols:
            for c in range(T.shape[2]):
                a = T[:, v, c, :10].argmax(-1)
                k += max(sum(1 for u in range(10) if int(a[u]) == (u + s) % 10)
                         for s in range(10))
                n += 10
        out[nm] = round(k / n, 3)
    sh = set()
    T = model.Tadd_eff[p]
    for v in range(10):
        for c in range(T.shape[2]):
            a = T[:, v, c, :10].argmax(-1)
            best, bs = -1, 0
            for s in range(10):
                m = sum(1 for u in range(10) if int(a[u]) == (u + s) % 10)
                if m > best:
                    best, bs = m, s
            sh.add(bs)
    out["n_shifts"] = len(sh)
    pkam = model.Tpick[p].argmax(-1)
    out["pick_ok"] = round(sum(1 for d in range(10)
                               if int(pkam[d]) == d) / 10, 3)
    return out


@torch.no_grad()
def eval_pop(model, inp, tgt, nd, discrete=False, chunk=256, diversity=False):
    model.eval()
    was, model.hard = model.hard, True if discrete else model.hard
    P = model.P
    ok = torch.zeros(P, device=inp.device)
    ok_mix = 0.0
    ce_p = torch.zeros(P, device=inp.device)
    n = inp.shape[0]
    answers = []
    for i in range(0, n, chunk):
        lg = model(inp[i:i + chunk], nd)                    # (P,c,S,10)
        t = tgt[i:i + chunk]
        ok += (lg.argmax(-1) == t[None]).all(-1).float().sum(1)
        ce_p += -lg.gather(-1, t[None].expand(P, *t.shape)[..., None]) \
            .squeeze(-1).sum((1, 2))
        mp = model.mix_probs(lg)
        ok_mix += (mp.argmax(-1) == t).all(-1).float().sum().item()
        if diversity:
            answers.append(mp.argmax(-1).cpu())
    model.hard = was
    model.train()
    acc = (ok / n)
    star = int(model.alpha.argmax().item())
    ce = ce_p / (n * tgt.shape[1])
    cstar = int(ce.argmin().item())
    out = {"per": acc, "mix": ok_mix / n, "argmax": float(acc[star]),
           "best": float(acc.max()), "star": star,
           "ce": ce, "ce_star": cstar, "ce_argmin": float(acc[cstar])}
    if diversity:
        a = torch.cat(answers, 0)
        keys = set(tuple(r.tolist()) for r in a)
        out["diversity"] = len(keys) / a.shape[0]
    return out


def pop_clip_(model, max_norm):
    ps = [p for p in model.replica_params() if p.grad is not None]
    if not ps:
        return
    sq = torch.stack([p.grad.reshape(p.shape[0], -1).pow(2).sum(1) for p in ps])
    nrm = sq.sum(0).sqrt()
    scale = (max_norm / (nrm + 1e-6)).clamp(max=1.0)
    for p in ps:
        p.grad.mul_(scale.view(-1, *([1] * (p.dim() - 1))))


# ---------------------------------------------------------------- main
def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pop", type=int, default=8)
    ap.add_argument("--modulus", type=int, default=10403)
    ap.add_argument("--modulus-bits", type=int, default=0)
    ap.add_argument("--modulus-seed", type=int, default=7)
    ap.add_argument("--slots", type=int, default=5)
    ap.add_argument("--train-x", type=int, default=8000)
    ap.add_argument("--held-x", type=int, default=1024)
    ap.add_argument("--max-quot", type=int, default=10)
    ap.add_argument("--pick", default="learned", choices=["learned", "fixed"])
    ap.add_argument("--tie", action="store_true")
    ap.add_argument("--tie-sub", action="store_true")
    ap.add_argument("--tf", type=float, default=0.0,
                    help="DIAGNOSTIC teacher-forced local CE weight; 0 = LEGAL")
    ap.add_argument("--tf-p", type=float, default=1.0)
    ap.add_argument("--sel", type=float, default=1.0)
    ap.add_argument("--sel-tau", type=float, default=1.0)
    ap.add_argument("--sel-hard", action="store_true")
    ap.add_argument("--sel-lr", type=float, default=None)
    ap.add_argument("--steps", type=int, default=1000)
    ap.add_argument("--batch", type=int, default=512)
    ap.add_argument("--lr", type=float, default=3e-2)
    ap.add_argument("--wd", type=float, default=0.0)
    ap.add_argument("--init-scale", type=float, default=0.5)
    ap.add_argument("--clip", type=float, default=1.0)
    ap.add_argument("--global-clip", action="store_true")
    ap.add_argument("--sthard", action="store_true",
                    help="straight-through hard states during TRAINING")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--split-seed", type=int, default=0)
    ap.add_argument("--log-every", type=int, default=250)
    ap.add_argument("--eval-chunk", type=int, default=256)
    ap.add_argument("--eval-n", type=int, default=1024)
    ap.add_argument("--device", default="cuda:0")
    ap.add_argument("--tag", default="")
    ap.add_argument("--construct", action="store_true")
    ap.add_argument("--timing-only", action="store_true")
    ap.add_argument("--jsonl", default="")
    args = ap.parse_args()

    torch.manual_seed(args.seed)
    N, S, P = args.modulus, args.slots, args.pop
    if args.modulus_bits:
        import random
        N, p_, q_ = sample_semiprime(args.modulus_bits,
                                     random.Random(args.modulus_seed))
        print(f"[{args.tag}] sampled N={N} ({args.modulus_bits} bits) "
              f"= {p_}*{q_}", flush=True)
    units = [x for x in range(1, N) if math.gcd(x, N) == 1]
    g = torch.Generator().manual_seed(args.split_seed)
    perm = torch.randperm(len(units), generator=g).tolist()
    tr_x = [units[i] for i in perm[: args.train_x]]
    he_x = [units[i] for i in perm[args.train_x: args.train_x + args.held_x]]
    dev = torch.device(args.device)

    def tens(xs):
        inp = torch.zeros(len(xs), S, 10)
        tgt = torch.zeros(len(xs), S, dtype=torch.long)
        for r, x in enumerate(xs):
            for i, d in enumerate(digits_le(x, S)):
                inp[r, i, d] = 1.0
            for i, d in enumerate(digits_le((x * x) % N, S)):
                tgt[r, i] = d
        return inp.to(dev), tgt.to(dev)

    xin, xt = tens(tr_x)
    hin, ht = tens(he_x)
    W = S + 1
    nd = torch.zeros(W, 10)
    for i, d in enumerate(digits_le(N, W)):
        nd[i, d] = 1.0
    nd = nd.to(dev)
    nd_dig = digits_le(N, W)

    model = PopAddALU(P, S, 2, 2, args.max_quot, 1.0, False, args.tie,
                      args.tie_sub, args.init_scale, args.pick).to(dev)
    ref = PopAddALU(1, S, 2, 2, args.max_quot, 1.0, False, args.tie,
                    args.tie_sub, pick=args.pick).to(dev)
    model.sel_hard = args.sel_hard
    ref.construct()
    for p in ref.parameters():
        p.requires_grad_(False)

    n_par = sum(p.numel() for p in model.parameters())
    per_rep = (n_par - P) // P
    print(f"[{args.tag}] POP={P} N={N} S={S} ADD-ONLY pick={args.pick} "
          f"tie={args.tie} tie_sub={args.tie_sub} params={n_par:,} "
          f"(~{per_rep:,}/replica) train={len(tr_x)} held={len(he_x)} "
          f"units={len(units)} depth={model.depth()}", flush=True)

    try:
        from benchmark import ModelSpec, assert_model_state
        spec = ModelSpec(vocab_size=17, max_seq_len=64,
                         maximum_model_state_elements=500_000_000)
        n_state = assert_model_state(model, spec)
        print(f"[{args.tag}] assert_model_state OK: {n_state:,} / 500,000,000 "
              f"({100 * n_state / 5e8:.4f}%)", flush=True)
    except Exception as exc:                       # pragma: no cover
        print(f"[{args.tag}] assert_model_state FAILED: {exc}", flush=True)
        return 1

    if args.construct:
        model.construct()
        rs = eval_pop(model, xin[:args.eval_n], xt[:args.eval_n], nd, False,
                      args.eval_chunk)
        r = eval_pop(model, xin[:args.eval_n], xt[:args.eval_n], nd, True,
                     args.eval_chunk)
        rh = eval_pop(model, hin, ht, nd, True, args.eval_chunk,
                      diversity=True)
        print(f"[{args.tag}] CONSTRUCTED train_exact_soft={rs['best']:.4f} "
              f"train_exact_hard={r['best']:.4f} "
              f"held_exact_hard={rh['best']:.4f} mix={r['mix']:.4f} "
              f"held_diversity={rh['diversity']:.4f}", flush=True)
        if args.jsonl:
            with open(args.jsonl, "a") as fh:
                fh.write(json.dumps({
                    "tag": args.tag, "argv": sys.argv[1:], "mode": "construct",
                    "N": N, "slots": S, "pick": args.pick,
                    "train_exact_soft": round(rs["best"], 4),
                    "train_exact_hard": round(r["best"], 4),
                    "held_exact_hard": round(rh["best"], 4),
                    "held_diversity_ref": round(rh["diversity"], 4),
                    "depth": model.depth(), "params_per_replica": per_rep,
                }) + "\n")
        return 0

    groups = [{"params": [p for p in model.parameters() if p is not model.alpha],
               "lr": args.lr},
              {"params": [model.alpha],
               "lr": args.sel_lr if args.sel_lr is not None else args.lr}]
    opt = torch.optim.AdamW(groups, weight_decay=args.wd, betas=(0.9, 0.95))

    # measured collapse reference: the EXACT solution's output diversity on the
    # same held-out cohort under the same detector (RESUME: do not assume 1.0)
    with torch.no_grad():
        cref = PopAddALU(1, S, 2, 2, args.max_quot, 1.0, False, args.tie,
                         args.tie_sub, pick=args.pick).to(dev)
        cref.construct()
        div_ref = eval_pop(cref, hin, ht, nd, True, args.eval_chunk,
                           diversity=True)["diversity"]
        del cref
    print(f"[{args.tag}] MEASURED collapse reference (exact solution, this "
          f"cohort, this detector): held_diversity={div_ref:.4f}", flush=True)

    hist = []
    t0 = time.time()
    tstep = 0.0
    for step in range(1, args.steps + 1):
        model.sel_tau = args.sel_tau
        idx = torch.randint(0, xin.shape[0], (args.batch,), device=dev)
        bi, bt = xin[idx], xt[idx]
        if step == 11:
            torch.cuda.synchronize()
            tstep = time.time()
        model.hard = args.sthard
        loss = torch.zeros((), device=dev)
        if args.tf > 0:
            with torch.no_grad():
                ref.mode, ref.tape = 'record', []
                ref(bi, nd)
                ref.mode = None
            model.mode, model.tape = 'force', ref.tape
            model.tf_loss = torch.zeros(P, device=dev)
            model.tf_n, model.tf_p = 0, args.tf_p
            model(bi, nd)
            model.mode = None
            loss = loss + args.tf * (model.tf_loss / max(model.tf_n, 1)).mean()
        if args.sel > 0 or args.tf == 0:
            logits = model(bi, nd)
            mp = model.mix_probs(logits).clamp_min(1e-9)
            mix_ce = F.nll_loss(mp.log().reshape(-1, 10), bt.reshape(-1))
            loss = loss + max(args.sel, 0.0 if args.tf > 0 else 1.0) * mix_ce
            if args.tf == 0:
                loss = loss + F.cross_entropy(
                    logits.reshape(-1, 10),
                    bt[None].expand(P, *bt.shape).reshape(-1))
        model.hard = False
        opt.zero_grad(set_to_none=True)
        loss.backward()
        if args.clip:
            if args.global_clip:
                torch.nn.utils.clip_grad_norm_(model.parameters(), args.clip)
            else:
                pop_clip_(model, args.clip)
                torch.nn.utils.clip_grad_norm_([model.alpha], args.clip)
        opt.step()
        if step == 1 or step % args.log_every == 0 or step == args.steps:
            r = eval_pop(model, xin[:args.eval_n], xt[:args.eval_n], nd, True,
                         args.eval_chunk)
            rsoft = eval_pop(model, xin[:args.eval_n], xt[:args.eval_n], nd,
                             False, args.eval_chunk)
            w = F.softmax(model.alpha / model.sel_tau, 0)
            hist.append({"step": step, "loss": round(loss.item(), 4),
                         "train_exact": round(rsoft["best"], 4),
                         "train_exact_hard": round(r["best"], 4)})
            print(f"[{args.tag}] step={step:>6} loss={loss.item():.4f} "
                  f"train_exact={rsoft['best']:.4f} "
                  f"train_exact_hard={r['best']:.4f} mix={r['mix']:.4f} "
                  f"argmax={r['argmax']:.4f} "
                  f"n_basin={(r['per'] > 0.5).sum().item()}/{P} "
                  f"wmax={w.max().item():.3f} ({time.time()-t0:.0f}s)",
                  flush=True)
    torch.cuda.synchronize()
    ms = 1000 * (time.time() - tstep) / max(args.steps - 10, 1) \
        if args.steps > 10 else float('nan')

    out = {"tag": args.tag, "argv": sys.argv[1:], "pop": P, "N": N, "slots": S,
           "pick": args.pick, "lr": args.lr, "steps": args.steps,
           "ms_per_step": round(ms, 2), "secs": round(time.time() - t0, 1),
           "legal": bool(args.tf == 0), "hist": hist,
           "collapse_ref_diversity": round(div_ref, 4)}
    if not args.timing_only:
        tr = eval_pop(model, xin[:args.eval_n], xt[:args.eval_n], nd, True,
                      args.eval_chunk)
        trs = eval_pop(model, xin[:args.eval_n], xt[:args.eval_n], nd, False,
                       args.eval_chunk)
        he = eval_pop(model, hin, ht, nd, True, args.eval_chunk,
                      diversity=True)
        hes = eval_pop(model, hin, ht, nd, False, args.eval_chunk)
        with torch.no_grad():
            ref.mode, ref.tape = 'record', []
            ref(xin[:256], nd)
            ref.mode = None
            model.mode, model.tape = 'force', ref.tape
            model.tf_loss, model.tf_n, model.tf_p = \
                torch.zeros(P, device=dev), 0, 1.0
            model(xin[:256], nd)
            model.mode = None
            lce = (model.tf_loss / max(model.tf_n, 1)).cpu()
        acc = tr["per"].cpu()
        hacc = he["per"].cpu()
        order = torch.argsort(acc, descending=True)
        out.update({
            "train_exact_hard_best": round(float(acc.max()), 4),
            "train_exact_hard_mix": round(tr["mix"], 4),
            "train_exact_hard_argmax": round(tr["argmax"], 4),
            "train_exact_soft_best": round(trs["best"], 4),
            "train_exact_soft_mix": round(trs["mix"], 4),
            "held_exact_hard_best": round(float(hacc.max()), 4),
            "held_exact_hard_mix": round(he["mix"], 4),
            "held_exact_soft_mix": round(hes["mix"], 4),
            "held_diversity": round(he["diversity"], 4),
            "n_basin": int((acc > 0.5).sum()),
            "local_ce_best": round(float(lce.min()), 5),
            "local_ce_med": round(float(lce.median()), 5),
            "acc_sorted": [round(float(v), 3) for v in acc[order][:16]],
        })
        out.update(struct_scores(model, int(order[0]), nd_dig))
        print(f"[{args.tag}] FINAL " + " ".join(
            f"{k}={v}" for k, v in out.items()
            if k not in ("argv", "tag", "hist")), flush=True)
    else:
        print(f"[{args.tag}] TIMING ms_per_step={ms:.2f} pop={P} "
              f"batch={args.batch} "
              f"peak_mem={torch.cuda.max_memory_allocated()/2**30:.2f}GiB",
              flush=True)
    out["peak_gib"] = round(torch.cuda.max_memory_allocated() / 2 ** 30, 2)
    if args.jsonl:
        with open(args.jsonl, "a") as fh:
            fh.write(json.dumps(out) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
