#!/usr/bin/env python
"""LAB ONLY -- the ADD-ONLY transducer as a pure INTEGER simulator, plus the
repair-basin protocol that `discrete-search` and `alu-relational` used.

WHY THIS FILE EXISTS
--------------------
`alu-relational` closed `DigitALU` with a structural argument: `Tmul`'s 200
cells are unidentifiable -- not from the end-of-chain label, not from any
generic algebraic law -- and the only law that WOULD identify them
(multiplication as repeated addition) is the definition of the arithmetic.
Meanwhile the adder's laws have the widest repair basin measured anywhere in
the project (50/400 cells) against the label's 0/5 at k=20 of 337.

The ADD-ONLY hypothesis class removes `Tmul` from the model instead of trying
to identify it.  `x * x` is accumulated as

    x^2 = sum_i  d_i(x) * x * 10^i           (place value -- fixed structure)
    d * x        = element `d` of the chain  x, x+x, (x+x)+x, ...
                   generated by the LEARNED adder                (the schedule)

so every learned tensor is an adder cell, a subtractor cell (or, under the
`inv` tie, an adder cell read backwards), or one of ~17 selector/constant
cells.  The reduction, the place-value shifts and the tree summation are
byte-for-byte `alu-depth`'s verified `tree:quotient` schedule; the ONLY change
is that the S^2 `Tmul` digit products are replaced by S full-width multiples of
`x` drawn from the adder chain.

COMPLIANCE.  See lab/reports/hard-add-only.md section 2 for the full ruling.
Two variants are implemented and both are reported:
  --pick learned  (PRIMARY, conservative)  the map digit -> chain element is a
                  LEARNED 10-cell table.  The architecture asserts only "the
                  leaf contributed at place i is SOME element of the chain
                  generated by repeatedly applying the learned binary op to x",
                  which is the same assertion `DigitALU`'s already-accepted
                  `multiples()` makes about N, with a learned selector on top.
  --pick fixed    (BORDERLINE)  the input digit one-hot indexes the chain
                  directly, i.e. `d*x = x added d times` is asserted.

`--construct` sets the learned tables to the truth: a LAB DIAGNOSTIC ceiling,
never a submission (rule 7).

Self-generated operands only; nothing under data/generated/ is opened.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import sys
import time

import torch

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from probe_search import search, _flog  # noqa: E402


def digits_le(value: int, slots: int) -> list[int]:
    out = []
    for _ in range(slots):
        out.append(value % 10)
        value //= 10
    return out


def is_prime(n: int) -> bool:
    if n < 2:
        return False
    for p in (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37):
        if n % p == 0:
            return n == p
    d, r = n - 1, 0
    while d % 2 == 0:
        d //= 2
        r += 1
    for a in (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37):
        x = pow(a, d, n)
        if x in (1, n - 1):
            continue
        for _ in range(r - 1):
            x = x * x % n
            if x == n - 1:
                break
        else:
            return False
    return True


def sample_semiprime(bits: int, rng) -> tuple[int, int, int]:
    """A p*q with exactly `bits` bits, p != q, both prime.  Mirrors the
    generator's _sample_rsa_factors shape; we NEVER read its output."""
    pb = bits // 2
    qb = bits - pb
    while True:
        p = rng.randrange(1 << (pb - 1), 1 << pb) | 1
        while not is_prime(p):
            p = rng.randrange(1 << (pb - 1), 1 << pb) | 1
        q = rng.randrange(1 << (qb - 1), 1 << qb) | 1
        while not is_prime(q) or q == p:
            q = rng.randrange(1 << (qb - 1), 1 << qb) | 1
        if (p * q).bit_length() == bits:
            return p * q, p, q


def _chain_rounds(needed):
    """Batched rounds of `_chain` needed to reach every element of `needed`."""
    have, target, n = {0, 1}, set(needed), 0
    while not target <= have:
        newly = [t for t in sorted(target - have)
                 if any(a <= t - a and (t - a) in have for a in have)]
        if not newly:
            newly = [2 * max(have)]
        have |= set(newly)
        n += 1
    return n


def add_depth(S, W, Fw, needed, xneeded):
    """Critical-path soft-step count in `DigitALU.depth()`'s own convention.

    `adds` = the x-multiples chain (per example, so it IS on the x->y path)
    plus the tree summation of the S leaves.  `reduce` = (S+1) quotient
    reductions, each one W-wide scan plus one select.  `prefix` = the N-only
    multiples chain, shared across examples exactly as DigitALU's is.
    """
    adds = _chain_rounds(xneeded) * W
    n_leaf = S
    if n_leaf > 1:
        adds += math.ceil(math.log2(n_leaf)) * Fw
    red = (S + 1) * (W + 1)
    return {"main": adds + red, "adds": adds, "reduce": red,
            "prefix": _chain_rounds(needed) * W}


# ------------------------------------------------------------------- the model
CELLS = (                      # (name, shape, n_candidates)
    ("add_d", (10, 10, 2), 10),
    ("add_c", (10, 10, 2), 2),
    ("sub_d", (10, 10, 2), 10),
    ("sub_b", (10, 10, 2), 2),
    ("zero", (1,), 10),
    ("carry0", (1,), 2),
    ("borrow0", (1,), 2),
    ("sel", (2, 2), 2),
    ("pick", (10,), 10),
)


class IntAddALU:
    """`tree:quotient` reduction schedule with an ADD-ONLY product, as an
    integer transducer batched over a population of table assignments."""

    def __init__(self, P, slots, ndig, n_carry=2, n_borrow=2, max_quot=10,
                 device="cuda:0", pick="learned"):
        self.P, self.S = P, slots
        self.W = slots + 1              # reduce register / multiple width
        self.F = 2 * slots              # product register width
        self.Ca, self.Cb, self.Q = n_carry, n_borrow, max_quot
        self.needed = list(range(max_quot + 2))
        self.M = len(self.needed)
        self.xneeded = list(range(10))
        self.pick_mode = pick
        self.dev = torch.device(device)
        self.ndig = ndig.to(self.dev)                      # (W,) int
        self.t = {}
        for name, shape, _ in CELLS:
            dt = torch.float32 if name == "sel" else torch.int64
            self.t[name] = torch.zeros((P,) + shape, dtype=dt, device=self.dev)
        self._eps = torch.arange(self.M - 1, device=self.dev,
                                 dtype=torch.float32) * 1e-6
        self.ties = set()

    # ---- LEGAL hypothesis-class ties (weight sharing, no value supplied) ----
    def set_ties(self, ties):
        self.ties = set(t for t in ties if t)
        idx = torch.zeros(100, dtype=torch.long)
        for u in range(10):
            for v in range(10):
                idx[u * 10 + v] = min(u, v) * 10 + max(u, v)
        self.sym200 = (idx[:, None] * 2
                       + torch.arange(2)[None]).reshape(-1).to(self.dev)

    def canon(self):
        if not self.ties:
            return
        P = self.P
        if "sym" in self.ties:
            for nm in ("add_d", "add_c"):
                f = self.t[nm].reshape(P, -1)
                f.copy_(f.gather(1, self.sym200[None].expand(P, -1)))
        if "inv" in self.ties:
            ad, ac = self.t["add_d"], self.t["add_c"]
            u = torch.arange(10, device=self.dev).view(1, 10, 1, 1).expand_as(ad)
            self.t["sub_d"].zero_().scatter_(1, ad, u)
            self.t["sub_b"].zero_().scatter_(1, ad, ac)

    # ---- population plumbing ------------------------------------------------
    def flat(self, name):
        return self.t[name].reshape(self.P, -1)

    def snapshot(self, member=0):
        return {k: v[member].clone() for k, v in self.t.items()}

    def load(self, snap):
        for k, v in snap.items():
            self.t[k].copy_(v.unsqueeze(0).expand_as(self.t[k]))

    def randomize(self, gen):
        for name, shape, n in CELLS:
            if name == "sel":
                v = torch.randint(0, n, (self.P,) + shape, generator=gen).float()
            else:
                v = torch.randint(0, n, (self.P,) + shape, generator=gen)
            self.t[name].copy_(v.to(self.dev))
        if self.pick_mode == "fixed":
            self.t["pick"].copy_(torch.arange(10, device=self.dev)
                                 .view(1, 10).expand(self.P, 10))

    def construct(self):
        """LAB DIAGNOSTIC -- the exact solution, as integers."""
        ad = torch.zeros(10, 10, 2, dtype=torch.int64)
        ac = torch.zeros(10, 10, 2, dtype=torch.int64)
        sd = torch.zeros(10, 10, 2, dtype=torch.int64)
        sb = torch.zeros(10, 10, 2, dtype=torch.int64)
        for u in range(10):
            for v in range(10):
                for c in range(2):
                    s = u + v + c
                    ad[u, v, c], ac[u, v, c] = s % 10, s // 10
                    d = u - v - c
                    sd[u, v, c], sb[u, v, c] = d % 10, (1 if d < 0 else 0)
        sel = torch.zeros(2, 2)
        sel[0, 1] = 1.0
        snap = {"add_d": ad, "add_c": ac, "sub_d": sd, "sub_b": sb,
                "zero": torch.zeros(1, dtype=torch.int64),
                "carry0": torch.zeros(1, dtype=torch.int64),
                "borrow0": torch.zeros(1, dtype=torch.int64), "sel": sel,
                "pick": torch.arange(10, dtype=torch.int64)}
        self.load({k: v.to(self.dev) for k, v in snap.items()})

    # ---- table reads ---------------------------------------------------------
    def G2(self, name, i, j):
        tab = self.t[name]
        P, A, B = tab.shape
        return tab.reshape(P, A * B).gather(1, i * B + j)

    def G3(self, name, i, j, k):
        tab = self.t[name]
        P, A, B, C = tab.shape
        return tab.reshape(P, A * B * C).gather(1, (i * B + j) * C + k)

    # ---- scans ---------------------------------------------------------------
    def add_scan(self, r, a):
        """r,a (P,N,W) -> (P,N,W)."""
        P, N, W = r.shape
        c = self.t["carry0"][:, 0:1].expand(P, N)
        outs = []
        for m in range(W):
            u, v = r[:, :, m], a[:, :, m]
            outs.append(self.G3("add_d", u, v, c))
            c = self.G3("add_c", u, v, c)
        return torch.stack(outs, -1)

    def sub_scan(self, r, a):
        P, N, W = r.shape
        c = self.t["borrow0"][:, 0:1].expand(P, N)
        outs = []
        for m in range(W):
            u, v = r[:, :, m], a[:, :, m]
            outs.append(self.G3("sub_d", u, v, c))
            c = self.G3("sub_b", u, v, c)
        return torch.stack(outs, -1), c

    def tree_sum(self, regs):
        while len(regs) > 1:
            carry = [regs[-1]] if len(regs) % 2 else []
            pairs = [(regs[i], regs[i + 1]) for i in range(0, len(regs) - 1, 2)]
            n = regs[0].shape[1]
            out = self.add_scan(torch.cat([a for a, _ in pairs], 1),
                                torch.cat([b for _, b in pairs], 1))
            regs = [out[:, i * n:(i + 1) * n] for i in range(len(pairs))] + carry
        return regs[0]

    def _chain(self, zero_reg, one_reg, needed):
        """Build {m * one_reg} for m in `needed` by repeated LEARNED addition.

        This is byte-for-byte `DigitALU.multiples()`; the only difference is
        that AddOnly also applies it to `x`, not just to `N`.
        """
        have = {0: zero_reg, 1: one_reg}
        target = set(needed)
        while not target <= set(have):
            newly = []
            for t in sorted(target - set(have)):
                cand = [a for a in have if a <= t - a and (t - a) in have]
                if cand:
                    newly.append((t, max(cand), t - max(cand)))
            if not newly:
                mx = max(have)
                newly = [(2 * mx, mx, mx)]
            A = torch.cat([have[a] for _, a, _ in newly], 1)
            B = torch.cat([have[b] for _, _, b in newly], 1)
            out = self.add_scan(A, B)
            k = A.shape[1] // len(newly)
            for i, (t, _, _) in enumerate(newly):
                have[t] = out[:, i * k:(i + 1) * k]
        return have

    def n_multiples(self):
        P, W = self.P, self.W
        z = self.t["zero"][:, 0:1, None].expand(P, 1, W).contiguous()
        one = self.ndig.view(1, 1, W).expand(P, 1, W).contiguous()
        have = self._chain(z, one, self.needed)
        return torch.cat([have[m] for m in self.needed], 1)          # (P,M,W)

    def x_multiples(self, s):
        """{m * x} for m = 0..9, per example, width W = S+1.  (P,B,10,W)"""
        P, B, S, W = self.P, s.shape[0], self.S, self.W
        zc = self.t["zero"][:, 0:1].expand(P, B)                      # (P,B)
        z = zc[:, :, None].expand(P, B, W).contiguous()
        xr = torch.cat([s.view(1, B, S).expand(P, B, S), zc[:, :, None]], 2)
        have = self._chain(z, xr.contiguous(), self.xneeded)
        return torch.stack([have[m] for m in self.xneeded], 2)        # (P,B,10,W)

    def quot_reduce(self, r, mults):
        P, B, W = r.shape
        M = mults.shape[1]
        rr = r[:, :, None].expand(P, B, M, W).reshape(P, B * M, W)
        ss = mults[:, None].expand(P, B, M, W).reshape(P, B * M, W)
        t, c = self.sub_scan(rr, ss)
        t = t.view(P, B, M, W)
        c = c.view(P, B, M)
        a = c[:, :, :-1].reshape(P, B * (M - 1))
        b = c[:, :, 1:].reshape(P, B * (M - 1))
        score = self.G2("sel", a, b).view(P, B, M - 1) - self._eps
        w = score.argmax(-1)
        return t.gather(2, w[:, :, None, None].expand(P, B, 1, W)).squeeze(2)

    @torch.no_grad()
    def forward(self, s):
        """s (B,S) int digits of x, LSB first -> (P,B,S) predicted digits."""
        self.canon()
        P, B, S, W, F = self.P, s.shape[0], self.S, self.W, self.F
        z = self.t["zero"][:, 0:1].expand(P, B)
        mults = self.n_multiples()
        Xm = self.x_multiples(s)                                    # (P,B,10,W)
        leaves = []
        for i in range(S):
            di = s[:, i].view(1, B).expand(P, B)
            m = self.t["pick"].gather(1, di)                        # (P,B)
            v = Xm.gather(2, m[:, :, None, None].expand(P, B, 1, W)).squeeze(2)
            cols = [z] * F
            for j in range(W):
                if i + j < F:
                    cols[i + j] = v[:, :, j]
            leaves.append(torch.stack(cols, 2))
        Pr = self.tree_sum(leaves)                                   # (P,B,F)
        r = z[:, :, None].expand(P, B, W)
        for t in range(F - 1, -1, -1):
            r = torch.cat([Pr[:, :, t:t + 1], r[:, :, :W - 1]], 2)
            if t <= S:
                r = self.quot_reduce(r, mults)
        return r[:, :, :S]

    @torch.no_grad()
    def score(self, s, tgt, chunk=0):
        """-> (digit_acc (P,), exact_acc (P,))"""
        B = s.shape[0]
        chunk = chunk or B
        dg = torch.zeros(self.P, device=self.dev)
        ex = torch.zeros(self.P, device=self.dev)
        for i in range(0, B, chunk):
            p = self.forward(s[i:i + chunk])
            hit = (p == tgt[i:i + chunk].unsqueeze(0))
            dg += hit.float().sum((1, 2))
            ex += hit.all(-1).float().sum(1)
        return dg / (B * self.S), ex / B

    def depth(self):
        return add_depth(self.S, self.W, self.F, self.needed, self.xneeded)


# ----------------------------------------------------------- structure scores
def structure_scores(snap, ndigits):
    out = {}
    for nm, T, cols in (("add_shift", snap["add_d"], range(10)),
                        ("sub_shift", snap["sub_d"], sorted(set(ndigits)))):
        k = n = 0
        T = T.cpu()
        for v in cols:
            for c in range(T.shape[2]):
                a = T[:, v, c]
                k += max(sum(1 for u in range(10) if int(a[u]) == (u + s) % 10)
                         for s in range(10))
                n += 10
        out[nm] = round(k / n, 3)
    sh = set()
    T = snap["add_d"].cpu()
    for v in range(10):
        for c in range(T.shape[2]):
            a = T[:, v, c]
            best, bs = -1, 0
            for s in range(10):
                m = sum(1 for u in range(10) if int(a[u]) == (u + s) % 10)
                if m > best:
                    best, bs = m, s
            sh.add(bs)
    out["n_shifts"] = len(sh)
    pk = snap["pick"].cpu()
    out["pick_ok"] = round(sum(1 for d in range(10)
                               if int(pk[d]) == d) / 10, 3)
    return out


def cell_agreement(snap, truth):
    out = {}
    tot = agr = 0
    for name, shape, _ in CELLS:
        a, b = snap[name], truth[name]
        k = int((a == b).sum())
        n = a.numel()
        out[name] = round(k / n, 3)
        tot += n
        agr += k
    out["all"] = round(agr / tot, 3)
    return out


# --------------------------------------------------------------------- cells
ALIAS = {"add": ("add_d", "add_c"), "sub": ("sub_d", "sub_b"),
         "const": ("zero", "carry0", "borrow0"), "sel": ("sel",),
         "pick": ("pick",)}


def free_cols(name, ties, pick_mode):
    shape = dict((a, b) for a, b, _ in CELLS)[name]
    k = 1
    for d in shape:
        k *= d
    if name == "pick" and pick_mode == "fixed":
        return []
    if "inv" in ties and name in ("sub_d", "sub_b"):
        return []
    if "sym" in ties and name in ("add_d", "add_c"):
        return [(u * 10 + v) * 2 + c for u in range(10)
                for v in range(u, 10) for c in range(2)]
    return list(range(k))


def cell_index(only=None, ties=(), pick_mode="learned"):
    out = []
    for name, shape, n in CELLS:
        if only is not None and name not in only:
            continue
        for c in free_cols(name, ties, pick_mode):
            out.append((name, c, n))
    return out


# ----------------------------------------------------------------------- main
def build_task(modulus, slots, train_x, held_x, split_seed, device):
    units = [x for x in range(1, modulus) if math.gcd(x, modulus) == 1]
    g = torch.Generator().manual_seed(split_seed)
    perm = torch.randperm(len(units), generator=g).tolist()
    tr = [units[i] for i in perm[:train_x]]
    he = [units[i] for i in perm[train_x:train_x + held_x]] if held_x \
        else [units[i] for i in perm[train_x:]]

    def tens(xs):
        inp = torch.tensor([digits_le(x, slots) for x in xs], dtype=torch.long)
        tgt = torch.tensor([digits_le((x * x) % modulus, slots) for x in xs],
                           dtype=torch.long)
        return inp.to(device), tgt.to(device)

    W = slots + 1
    nd = torch.tensor(digits_le(modulus, W), dtype=torch.long)
    return tens(tr), tens(he), nd, tr, he


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--modulus", type=int, default=323)
    ap.add_argument("--modulus-bits", type=int, default=0,
                    help="sample a semiprime of this many bits instead")
    ap.add_argument("--modulus-seed", type=int, default=7)
    ap.add_argument("--slots", type=int, default=3)
    ap.add_argument("--train-x", type=int, default=250)
    ap.add_argument("--held-x", type=int, default=0)
    ap.add_argument("--max-quot", type=int, default=10)
    ap.add_argument("--split-seed", type=int, default=0)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--device", default="cuda:0")
    ap.add_argument("--block", type=int, default=64)
    ap.add_argument("--sweeps", type=int, default=40)
    ap.add_argument("--obj", default="digit", choices=["digit", "exact", "mix"])
    ap.add_argument("--restarts", type=int, default=1)
    ap.add_argument("--pick", default="learned", choices=["learned", "fixed"])
    ap.add_argument("--construct", action="store_true")
    ap.add_argument("--basin", action="store_true")
    ap.add_argument("--basin-reps", type=int, default=5)
    ap.add_argument("--repair", type=int, default=0)
    ap.add_argument("--repair-reps", type=int, default=1)
    ap.add_argument("--repair-ks", default="",
                    help="comma list of k values; runs the whole ladder")
    ap.add_argument("--time-budget", type=float, default=0.0)
    ap.add_argument("--chunk", type=int, default=0)
    ap.add_argument("--tie", default="")
    ap.add_argument("--modules", default="")
    ap.add_argument("--tag", default="")
    ap.add_argument("--jsonl", default="")
    args = ap.parse_args()

    device = torch.device(args.device)
    N = args.modulus
    if args.modulus_bits:
        import random
        N, p, q = sample_semiprime(args.modulus_bits,
                                   random.Random(args.modulus_seed))
        print(f"[{args.tag}] sampled N={N} ({args.modulus_bits} bits) "
              f"= {p}*{q}", flush=True)
    (xin, xt), (hin, ht), nd, tr, he = build_task(
        N, args.slots, args.train_x, args.held_x, args.split_seed, device)
    only = None
    if args.modules:
        only = set()
        for part in args.modules.split(","):
            only |= set(ALIAS.get(part.strip(), (part.strip(),)))
    ties = tuple(t for t in args.tie.split(",") if t)
    cells = cell_index(only, ties, args.pick)
    CMAX = max(n for _, _, n in cells)
    P = args.block * CMAX
    model = IntAddALU(P, args.slots, nd, 2, 2, args.max_quot, device, args.pick)
    model.set_ties(ties)
    ndl = nd.tolist()
    print(f"[{args.tag}] ADD-ONLY N={N} S={args.slots} pick={args.pick} "
          f"ties={ties or '-'} train={len(tr)} held={len(he)} "
          f"cells={len(cells)} candidates={sum(n for _, _, n in cells)} "
          f"pop={P} depth={model.depth()}", flush=True)

    model.construct()
    truth = model.snapshot(0)
    d, e = model.score(xin, xt, args.chunk)
    dh, eh = model.score(hin, ht, args.chunk)
    print(f"[{args.tag}] CONSTRUCTED train_digit={d[0]:.4f} "
          f"train_exact_hard={e[0]:.4f} held_exact_hard={eh[0]:.4f} "
          f"struct={structure_scores(truth, ndl)}", flush=True)
    if args.construct:
        row = {"tag": args.tag, "argv": sys.argv[1:], "mode": "construct",
               "N": N, "slots": args.slots, "pick": args.pick,
               "train_exact_hard": round(e[0].item(), 4),
               "held_exact_hard": round(eh[0].item(), 4),
               "depth": model.depth(), "n_cells": len(cells)}
        if args.jsonl:
            with open(args.jsonl, "a") as fh:
                fh.write(json.dumps(row) + "\n")
        return 0

    gen = torch.Generator().manual_seed(args.seed)

    if args.basin:
        import statistics as _st
        ks = [k for k in (0, 1, 2, 3, 5, 10, 20, 50, 100, 200, 500)
              if k <= len(cells)] + [len(cells)]
        for k in sorted(set(ks)):
            ds, es = [], []
            for rep in range(1 if k == 0 else args.basin_reps):
                model.construct()
                g = torch.Generator().manual_seed(1000 * k + rep)
                pick = torch.randperm(len(cells), generator=g)[:k].tolist()
                for ci in pick:
                    name, col, n = cells[ci]
                    v = int(torch.randint(0, n, (1,), generator=g))
                    model.flat(name)[:, col] = float(v) if name == "sel" else v
                d, e = model.score(xin, xt, args.chunk)
                ds.append(d[0].item())
                es.append(e[0].item())
            print(f"[{args.tag}] basin k={k:>4}/{len(cells)} "
                  f"digit={sum(ds)/len(ds):.4f} "
                  f"sd={_st.pstdev(ds) if len(ds) > 1 else 0.0:.4f} "
                  f"exact={sum(es)/len(es):.4f}", flush=True)
        return 0

    rows = []
    ks = [int(v) for v in args.repair_ks.split(",")] if args.repair_ks \
        else [args.repair]
    for k in ks:
        n_exact = 0
        reps = args.repair_reps if k else args.restarts
        for rep in range(reps):
            g = torch.Generator().manual_seed(args.seed * 100 + rep + 7919 * k)
            if k:
                model.construct()
                pk = torch.randperm(len(cells), generator=g)[:k].tolist()
                for ci in pk:
                    name, col, n = cells[ci]
                    v = int(torch.randint(0, n, (1,), generator=g))
                    model.flat(name)[:, col] = float(v) if name == "sel" else v
                base = model.snapshot(0)
                model.load(base)
                d0, e0 = model.score(xin, xt, args.chunk)
                print(f"[{args.tag}] k={k} rep={rep} corrupted "
                      f"digit={d0[0]:.4f} exact={e0[0]:.4f} "
                      f"cell_agree={cell_agreement(base, truth)['all']}",
                      flush=True)
            elif only is not None:
                # LAB DIAGNOSTIC: every table outside --modules is set to the
                # CONSTRUCTION; only the named ones start random and are
                # searched.  Measures which modules the end-of-chain label can
                # identify on its own.
                model.construct()
                base = model.snapshot(0)
                rnd = IntAddALU(1, args.slots, nd, 2, 2, args.max_quot,
                                device, args.pick)
                rnd.set_ties(ties)
                rnd.randomize(g)
                rs = rnd.snapshot(0)
                for name in only:
                    base[name] = rs[name]
                model.load(base)
                d0, e0 = model.score(xin, xt, args.chunk)
                print(f"[{args.tag}] modules={sorted(only)} random, rest "
                      f"CONSTRUCTED: digit={d0[0]:.4f} exact={e0[0]:.4f}",
                      flush=True)
            else:
                model.randomize(g)
                base = model.snapshot(0)
                model.load(base)
                d0, e0 = model.score(xin, xt, args.chunk)
                print(f"[{args.tag}] random init digit={d0[0]:.4f} "
                      f"exact={e0[0]:.4f}", flush=True)
            t0 = time.time()
            best, d1, e1 = search(model, xin, xt, cells, args.obj, args.block,
                                  args.sweeps, gen, tag=f"{args.tag}/k{k}r{rep}",
                                  time_budget=args.time_budget, chunk=args.chunk)
            model.load(best)
            d, e = model.score(xin, xt, args.chunk)
            dh, ehd = model.score(hin, ht, args.chunk)
            best = model.snapshot(0)      # after canon(), so ties are resolved
            ss = structure_scores(best, ndl)
            ca = cell_agreement(best, truth)
            exact_recovery = (ca["all"] == 1.0) or (e[0].item() == 1.0
                                                    and ehd[0].item() == 1.0)
            n_exact += int(exact_recovery)
            row = {"tag": args.tag, "k": k, "rep": rep, "argv": sys.argv[1:],
                   "N": N, "slots": args.slots, "pick": args.pick,
                   "ties": list(ties), "n_cells": len(cells),
                   "train_digit": round(d[0].item(), 4),
                   "train_exact_hard": round(e[0].item(), 4),
                   "held_digit": round(dh[0].item(), 4),
                   "held_exact_hard": round(ehd[0].item(), 4),
                   "exact_recovery": bool(exact_recovery),
                   "secs": round(time.time() - t0, 1),
                   "struct": ss, "cell_agree": ca}
            rows.append(row)
            print(f"[{args.tag}] k={k} rep={rep} FINAL train_digit={d[0]:.4f} "
                  f"train_exact_hard={e[0]:.4f} held_exact_hard={ehd[0]:.4f} "
                  f"RECOVERED={exact_recovery} cell_agree={ca['all']} "
                  f"struct={ss}", flush=True)
        print(f"[{args.tag}] === k={k}: exact recoveries {n_exact}/{reps} "
              f"of {len(cells)} cells ===", flush=True)

    if args.jsonl:
        with open(args.jsonl, "a") as fh:
            for r in rows:
                fh.write(json.dumps(r) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
